### ISSUE TITLE
Recovering from MultipartUploadException during S3ClientTrait::uploadDirectory()

### ISSUE THREAD

**Issue by joecwallace** [aws/aws-sdk-php#1015]
Hello! Thank you so much for this library. It's been very helpful and a pleasure to work with so far, but I've hit a bit of a snag...

I'm trying to upload a directory to a bucket. The directory contains some large files that result in a multipart upload. Sometimes, this throws a `MultipartUploadException`.

At that point, how do I recover from the exception, since I don't have an explicit source path? (My current `composer.lock` version of the SDK is `3.18.9`, if that's helpful at all.)

Code sample of what I am trying / would like to do:
```php
$directory = '/path/to/my/dir';
$client = new S3Client($config);

try {
    $client->uploadDirectory($directory, 'my-bucket');
} catch (MultipartUploadException $e) {
    $source = '???'; // Is there some way to get this from $client or $e?

    $uploader = new MultipartUploader($client, $source, ['state' => $e->getState()]);
    $uploader->upload();
}
```

**Comment by cjyclaire** [comment]
@joecwallace Thanks for the information!

`$source` (except streams) passed to a `MultipartUploader` will be automatically rewound before uploading. The `UploadState` object can be used to resume an upload that failed to complete. It will only attempt to upload parts that are not already uploaded. 

When tracing the file when exception occurs, you could try `$e->getFile()`

Meanwhile, since SDK V3 is used, I'd suggest using [Transfer Manager](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-transfer.html) instead of `uploadDirectory()`(Though we still support it ;) ).  [Configuration](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-transfer.html#configuration) for `Transfer Manager` is more flexible in many ways.

**Comment by joecwallace** [comment]
@cjyclaire - Thank you for the reply. :-)

I think my question is still open though: how do I recover from the `MultipartUploadException` in the `catch` block above?

To provide a more concrete example:

1. I have a directory `/foo/bar`
1. In `/foo/bar` are 3 files: `x.txt`, `y.txt`, & `z.txt`
1. I execute `$client->uploadDirectory('/foo/bar', 'my-bucket')`
1. A `MultipartUploadException` is thrown while uploading `y.txt`
1. I catch the exception and wish to call `(new MultipartUploader($client, '/foo/bar/y.txt', ['state' => $e->getState()]))->upload()`

But how do I know that `y.txt` is the file that was being uploaded when the exception was thrown? As far as my code is aware, it could have been `x.txt` or `z.txt`. Is the filename provided by the exception?

I see that you've mentioned `$e->getFile()`, but my understanding is that `getFile()` will return the name of the PHP file in which the exception was created/thrown. Is that incorrect?

**Comment by cjyclaire** [comment]
@joecwallace That's true, thanks for follow-up clarification, I'd tag it as a feature request, it would be nice if SDK could provide more information in S3 Transfer Exceptions, and will work on it soon.

**Comment by cjyclaire** [comment]
Closing, tracking this with PR under review instead :).
