### ISSUE TITLE
missing eu-central-1 for autoscaling in 2.8

### ISSUE THREAD

**Issue by robgil** [aws/aws-sdk-php#1021]
aws-sdk-php/src/Aws/AutoScaling/Resources/autoscaling-2011-01-01.php doesnt reference eu-central-1. Is 2.8 supported anymore? We want to upgrade, but cant right now, and need to use this region. 

Thanks!

**Comment by cjyclaire** [comment]
@robgil, thanks for catching, SDK does maintain V2, yet strongly recommends migrating to V3.

Working on the fix, will follow up with PR.

**Comment by robgil** [comment]
Thanks @cjyclaire. We're planning to move, but need to go live first in a new region.

**Comment by cjyclaire** [comment]
@robgil In v2, SDK doesn't provided region endpoint list or expose that, and resource files are deprecated and no longer used. It's a feature of v3 that supports new `endpoint.json` file and introduces `PartitionEndpointProvider `.

There is no changes that SDK v2 can make to enable a region support without breaking backwards compatibility. The `eu-central-1` should be already rendered since it's [supported](http://docs.aws.amazon.com/general/latest/gr/rande.html#as_region). Apologies for the confusion, closing and please feel free to reopen if you have further questions.
