### ISSUE TITLE
S3ClientTrait:doesBucketExist returns false on error 403 (was true in 2.8)

### ISSUE THREAD

**Issue by n0rbyt3** [aws/aws-sdk-php#1029]
I have upgraded the SDK from 2.8 to 3.x and now whenever I try to read or write a file to S3, I get an error with "CreateBucket":

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>...</RequestId>
  <HostId>...</HostId>
</Error>
```

I have found out, that the read operation internally calls ```ensureBucketExists()``` which will finally get handled by ```S3ClientTrait:checkExistenceWithCommand```:

```php
private function checkExistenceWithCommand(CommandInterface $command)
{
    try {
        $this->execute($command);
        return true;
    } catch (S3Exception $e) {
        if ($e->getAwsErrorCode() == 'AccessDenied') {
            return true;
        }
        if ($e->getStatusCode() >= 500) {
            throw $e;
        }
        return false;
    }
}
```

I assumed that $e->getAwsErrorCode() will return ```AccessDenied``` but unfortunately, it is ```null```. The exception:

```
Error executing "HeadBucket" on "https://s3-eu-west-1.amazonaws.com/<mybucket>"; AWS HTTP error: Client error: `HEAD https://s3-eu-west-1.amazonaws.com/<mybucket>` resulted in a `403 Forbidden` response:

  (client): 403 Forbidden (Request-ID: xxxxxxxxxxxxxxx) - 
```

**Comment by n0rbyt3** [comment]
In 2.8 it worked because of an extra flag ```accept403``` in ```doesBucketExist```, which is true by default:

```php
public function doesBucketExist($bucket, $accept403 = true, array $options = array())
{
    return $this->checkExistenceWithCommand(
        $this->getCommand('HeadBucket', array_merge($options, array(
            'Bucket' => $bucket
        ))), $accept403
    );
}
```

Why has this been removed?

**Comment by cjyclaire** [comment]
@n0rbyt3 , could you try `$s3->waitUntil('BucketExists', ['Bucket' => $bucket]);` after create bucket?

**Comment by n0rbyt3** [comment]
@cjyclaire That is not what I want to do. I want to read a file from an existing bucket but I don't have the permission to create a bucket.

In 2.8:

```read()``` -> (calls) ```ensureBucketExists()``` -> ```HeadBucket``` command -> AccessDeniedError (403) is thrown and catched and because ```$accept403``` is true, *true is returned*, so the bucket exists and the file could get read

In 3.0:
```read()``` -> (calls) ```ensureBucketExists()``` -> ```HeadBucket``` command -> AccessDeniedError (403) is thrown and cactched and *false is returned*, so the bucket does not exist and ```CreateBucket``` command is executed which also throws AccessDeniedError (403) and that exception is not caught, so ```read()``` fails

**Comment by n0rbyt3** [comment]
I should have mentioned that I use knplabs/gaufrette package which provides the ```read()``` method. And that uses the ```ensureBucketExists()```method internally which calls ```S3Client::doesBucketExist``` of the aws/aws-sdk-php package. But the behaviour of ```doesBucketExist``` has changed internally as described if an error 403 occurs.

I hope, it will clarify the confusion with the method names.

**Comment by cjyclaire** [comment]
@n0rbyt3 Thanks for the information and explanation!

If `HeadBucket` returns `AccessDeniedError`, it doesn't make sense for SDK to allow `createBucket` without enough permission. It's true that there is Api behavior change because SDK V3 exposes 4XX errors to users for troubleshooting intention, yet it doesn't hurt usage, avoids using `$accept403`, checking `false` value instead makes more logical sense, perhaps open a PR in `knplabs/gaufrette` could fix that.

```
if (!$client->doesBucketExist($bucket)) {
       // or try catch exception here
        $client->createBucket($bucket);
}
```

**Comment by cjyclaire** [comment]
Closing due to ages, yet feel free to reopen if you have further questions :)

**Comment by dmolnarqu** [comment]
I ran into this issue as well. When checking if bucket exists, I always get false.
I created S3Client and could successfully store and retrieve objects, but doesBucketExist() always returns false. 
I noticed there's a check for 'AccessDenied' aws error code, but it still fails, because I am getting NULL as aws error code with 403 response.
Is there more robust alternative to that check?

**Comment by SteffenDE** [comment]
How can this be closed? doesBucketExist fails when HeadBucket returns 403, even if the bucket exists and getting/putting objects works fine. This is a critical issue for me...

**Comment by dmolnarqu** [comment]
@SteffenDE 
I managed to work around the issue by implementing custom bucketExists method.
```PHP
public function bucketExists($bucket) {
    // $client->doesBucketExist() returns false on denied access since 3.X, we don't want that
    try {
        $client = My_Aws_Client::get();
        $command = $client->getCommand('HeadBucket', ['Bucket' => $bucket]);
        $client->execute($command);
        return true;
    } catch (S3Exception $e) {
        if ($e->getAwsErrorCode() == 'AccessDenied' || $e->getStatusCode() == 403) {
            return true;
        }
        if ($e->getStatusCode() >= 500) {
            throw $e;
        }
        return false;
    }
}
```

**Comment by SteffenDE** [comment]
@dmolnarqu 
Replacing this single line:
https://github.com/aws/aws-sdk-php/blob/ab1cf3e90aa5ad04946e9de3978a339d64528bb1/src/S3/S3ClientTrait.php#L289
With `if ($e->getAwsErrorCode() == 'AccessDenied' || $e->getStatusCode() == 403)` fixes this for me.
The problem is that Nextcloud (I'm trying to use a bucket for external storage) seems to have another location where it tries to do a HeadBucket call, which also fails (https://forums.aws.amazon.com/thread.jspa?threadID=130203).
