### ISSUE TITLE
Using a mock handler in conjunction with an S3 client

### ISSUE THREAD

**Issue by msencenb** [aws/aws-sdk-php#1043]
I'm hoping to use mock handlers as described [here](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/handlers-and-middleware.html), in conjunction with the S3 client. 

I'm using Laravel and calling the constructor like this, where mock corresponds to my previously configured mockHandler:

`App::make('aws')->createClient('s3', ['handler' => $mock]);`

This does not work, and after digging into the code, it appears that the S3Client.php constructor doesn't accept the handler parameter. Am I missing something in the setup?

The mock handler described by the doc above is perfect for the unit tests I want to write... is there something like it that works with S3 specifically? If not, what do you recommend for unit tests involving the aws sdk using s3?

**Comment by cjyclaire** [comment]
@msencenb , the way you configure `'handler'` option looks good to me, could you try also add the [`'region'`](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#region) and [`'version'`](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#version) information here?

**Comment by msencenb** [comment]
Actually, I misspoke; the constructor calls parent::__construct which appears to accept handler as a valid option, although I haven't traced through the code to find out how the handler is getting setup up. 

Unfortunately my test case does not work when I pass handler in as a constructor argument. But, if I explicitly call setHandler with my mock it fires correctly. 

`$s3->getHandlerList()->setHandler($this->mock);`

**Comment by cjyclaire** [comment]
@msencenb thanks for the information, it looks like a `aws-sdk-php-laravel` issue actually.

Dive deeper into the issue, because a SDK object is [constructed](https://github.com/aws/aws-sdk-php-laravel/blob/master/src/AwsServiceProvider.php#L50) before calling [`createClient()`](https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Sdk.html#_createClient), which contains default configuration for `http_handler` of a `GuzzleHandler`. Since [`http_handler`](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#http-handler) supersedes any provided `handler` option, passing `handler` option later will not work. 

Applying the mock at handler list is a sufficient workaround because it force overwrite the HandlerList after a `S3Client` is initialized.
