### ISSUE TITLE
Make \Aws\Signature\SignatureV4::convertExpires public or accessible through a trait

### ISSUE THREAD

**Issue by deviantintegral** [aws/aws-sdk-php#1052]
In order to properly support cache metadata for pages, the [Flysystem S3 Drupal module](https://www.drupal.org/node/2772847) needs to know how long a presigned URL is valid for. For now, we're just going to copy the method to our code, but it seems to me this logic should either be in a public static method, or in a trait that we can pull into our class.

**Comment by cjyclaire** [comment]
@deviantintegral , thank your for the feedback! 

This method is marked private since it's called when computing the value for `x-amz-expires` field which needs to be included in the query string part of a pre-signed URL. I don't feel it appropriate to make this method alone public or a trait since from SDK side, because it just lives inside the signature lifecycle.

Meanwhile I totally understand your need, instead if calling the same method, how about parsing the pre-signed URL instead? 

Since you could get a pre-signed URL with `presign()` method which is public. Then you could also taking advantage of [`\GuzzleHttp\Psr7\Uri`](https://github.com/guzzle/psr7/blob/master/src/Uri.php) class where you could call `getQuery()` to get query string from a Uri object with ease. After that, extracting the value for `X-Amz-Expires` would work.

Thoughts?

**Comment by deviantintegral** [comment]
I thought about that, but I wasn't sure how stable the query parameters would be. It felt kind of hacky to be parsing them like that from outside the SDK. But if you think that's fine, then it works for me.
