### ISSUE TITLE
Issue with ELB client API (Could not resolve hostname)

### ISSUE THREAD

**Issue by fideloper** [aws/aws-sdk-php#1071]
Hello!

Since [methods on the ElasticLoadBalancer client are not documented](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.ElasticLoadBalancing.ElasticLoadBalancingClient.html), and the Console in the web app appears to use the ElasticLoadBalancerV2 API internally ([which are documented](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.ElasticLoadBalancingV2.ElasticLoadBalancingV2Client.html)), **I'm assuming we should be using the V2 ELB client**.

> Of course let me know if I'm wrong - perhaps V2 is meant for ALB instead of ELB? The lack of documentation for the "v1" client makes it hard to know how to get around this.

## Error:

When I use that, I receive the following error:

> Aws\ElasticLoadBalancingV2\Exception\ElasticLoadBalancingV2Exception with message 'Error executing "DescribeLoadBalancers" on "https://elasticloadbalancingv2.us-east-1.amazonaws.com"; AWS HTTP error: cURL error 6: Could not resolve host: elasticloadbalancingv2.us-east-1.amazonaws.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)'

## Info / Code:

**Package Tried:** 

* `aws/aws-sdk-php` @ `3.18.39`, commit `85f1fddaeb40b95106b2a2764268e9c89fc258ce`
* `aws/aws-sdk-php` @ `3.19.0`, commit `204337efe872a0207781089833de0f8594fc5fd7`

**Code**

```php
<?php

require_once('vendor/autoload.php');

$elb = new Aws\ElasticLoadBalancingV2\ElasticLoadBalancingV2Client([
    'version' => 'latest', // Also tried '2015-12-01'
    'region' => 'us-east-1',
]);

// http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-elasticloadbalancingv2-2015-12-01.html#describeloadbalancers
$balancers = $elb-> describeLoadBalancers();

// Throws Aws\ElasticLoadBalancingV2\Exception\ElasticLoadBalancingV2Exception 
```

Let me know if I'm using the SDK incorrectly for ELB!

Thanks

**Comment by fideloper** [comment]
Using the latest AWS CLI tool (which has elb and elbv2 commands):

This is on my account which has one "classic" ELB (no ALB's):

```bash
# No v2 ELB's here
aws elbv2 --profile=helpspot --region=us-east-1 describe-load-balancers
{
    "LoadBalancers": []
}
```

```bash
# Our ELB listed here
aws elb --profile=helpspot --region=us-east-1 describe-load-balancers 
{
    "LoadBalancerDescriptions": [ /* LB's listed here */ ]
}
```

Using the **--debug** option, I can see the end point used in v2 and regular ELB commands is `https://elasticloadbalancing.us-east-1.amazonaws.com/`



Thanks

**Comment by fideloper** [comment]
And, finally, I see the documentation for `2012-06-01` within the V2 client API. That doesn't work with the V2 client, but this DOES work with that documented version:

This works, note the API version and class name is not V2 (although it's documented under the v2 client):

```
<?php

require_once('vendor/autoload.php');

$elb = new Aws\ElasticLoadBalancing\ElasticLoadBalancingClient([
    'version' => '2012-06-01',
    'region' => 'us-east-1',
    'profile' => 'helpspot',
]);

// http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-elasticloadbalancingv2-2015-12-01.html#describeloadbalancers
$balancers = $elb->describeLoadBalancers();

dd($balancers->get('LoadBalancerDescriptions'));
```

Just to test this doesn't work, with error `The elasticloadbalancing service does not have version: 2015-12-01.`:

```php
<?php

require_once('vendor/autoload.php');

$elb = new Aws\ElasticLoadBalancing\ElasticLoadBalancingClient([
    'version' => '2015-12-01', // Also tried '2015-12-01'
    'region' => 'us-east-1',
    'profile' => 'helpspot',
]);

// http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-elasticloadbalancingv2-2015-12-01.html#describeloadbalancers
$balancers = $elb->describeLoadBalancers();

dd($balancers->get('LoadBalancers'));

// Throws Aws\Exception\UnresolvedApiException 
```

## Conclusion

1. There may be an bug or missing endpoint for the v2 client
2. Documentation "issue" with the non-v2 client documentation "hiding" in the V2 client docs


Thanks!

**Comment by cjyclaire** [comment]
@fideloper Thanks for reporting! working on the fix.

**Comment by cjyclaire** [comment]
@fideloper PR contains the fix is out and under review.

I looked into the Documentation confusion here. Each API version block in SDK documentation class page is automatically generated based on the `serviceFullName` based on API models. Both [`ElasticLoadBalancing`](https://github.com/aws/aws-sdk-php/blob/master/src/data/elasticloadbalancing/2012-06-01/api-2.json#L7) and [`ElasticLoadBalancingV2`](https://github.com/aws/aws-sdk-php/blob/master/src/data/elasticloadbalancingv2/2015-12-01/api-2.json#L8) uses full name as `ElasticLoadBalancing`, that's why they showed up [here](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.ElasticLoadBalancingV2.ElasticLoadBalancingV2Client.html) (since V2 is a newer model).

Since models decisions are made from service team with design concerns and is unified across SDKs, it's not appropriate to change that from SDK side. Fortunately, detail method page with instructions is correct here [[1]](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-elasticloadbalancing-2012-06-01.html) [[2]](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-elasticloadbalancingv2-2015-12-01.html). I'll add more documentation in PHP SDK guide for it.

Apology for the confusion and thank you for your patience :)

**Comment by cjyclaire** [comment]
@fideloper PR contains the fix is out and under review.

I looked into the Documentation confusion here. Each API version block in SDK documentation class page is automatically generated based on the serviceFullName based on API models. Both ElasticLoadBalancing and ElasticLoadBalancingV2 uses full name as ElasticLoadBalancing, that's why they showed up here (since V2 is a newer model). Working on the doc fix right now.
 
Fortunately, detail method page with instructions is correct here [1] [2]. I'll add more documentation in PHP SDK guide for it.

Apology for the confusion and thank you for your patience :)

**Comment by cjyclaire** [comment]
PR containing Doc fix and endpoint fix has been merged, this fix will be tagged in today's release.

**Comment by fideloper** [comment]
Thank you! Appreciate the feedback and updates!

**Comment by cjyclaire** [comment]
Release contains the fix is out, closing, yet feel free to reopen if you have further comments or questions :)
