### ISSUE TITLE
Is possible to hook into the Iterator implementation?

### ISSUE THREAD

**Issue by tiagobrito** [aws/aws-sdk-php#1076]
I want to build an on-demand collection that hydrate the objects returned by the Generator iterator.  
Is it possible?

**Comment by cjyclaire** [comment]
@tiagobrito Could you share more about the generator mentioned and what do you expect to do with each object?

I'm guessing that you are talking about the generator object that [`MultipartUploader`](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-multipart-upload.html#customizing-a-multipart-upload) returns or a [`CommandPool`](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/commands.html?#commandpool). The usage of both allows flexible customization, so it would be nice to shared more about your needs first before we go further.

**Comment by tiagobrito** [comment]
@cjyclaire I'm doing `$dynamoDbClient->getIterator('scan' [...])` and this will return an Iterator that will make a call on Dynamodb for more than 1000 items or when the data > 1MB. I want to be able to create an Hydrator to convert the items on demand.

**Comment by cjyclaire** [comment]
@tiagobrito Apology for the late reply on this.

In terms of enhancing the performance of ['scan'](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-dynamodb-2012-08-10.html#scan) API, first you could try the `ScanFilter` parameter in filtering the result. Then, 'Limit' parameter would also be helpful. Since `LastEvaluatedKey` is included in each request result,  using that value as 'ExclusiveStartKey' in the next call and repeat could do the work. With those approaches, the number of items return per call could be reduced.

Also in searching `Result` object, you might also be interested in [JMESPath](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/jmespath.html).

**Comment by cjyclaire** [comment]
Closing due to ages, yet please feel free to reopen if you have further question or comments :)

**Comment by tiagobrito** [comment]
The `ScanFilter` or `FilterExpression` isn't recommended for "big exclusions" from the original scan, right ?
So my option is to implement the logic using the `LastEvaluatedKey` and `ExclusiveStartKey` and `Limit`.
Thanks for your help
