### ISSUE TITLE
cross account access

### ISSUE THREAD

**Issue by tomnijboer** [aws/aws-sdk-php#1092]
We're trying to accomplish a cross account s3 upload within iam role for ec2. 
Is this even possible? 

We're getting the following response back:

<?xml version="1.0" encoding="UTF-8"?> <Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided (truncated...)  InvalidAccessKeyId (client): The AWS Access Key Id you provided does not exist in our records. - <?xml version="1.0" encoding="UTF-8"?> <Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>(truncated...)</AWSAccessKeyId><RequestId>2E06BAFED1DC08B5</RequestId><HostId>(truncated...)</HostId>  

When I run the aws cli I need to supply a session token, but I don't know where to put in with the php code.

``
       $stsClient = new StsClient([
            'region' => $this->region,
            'version' => $this->version,
            'credentials' => $this->credentialProvider,
        ]);

        $result = $stsClient->assumeRole([
            'RoleArn' => $this->arn,
            'RoleSessionName' => uniqid(),
        ]);

        return new S3Client([
            'region' => $this->region,
            'version' => $this->version,
            'credentials' => [
                'key' => $result['Credentials']['AccessKeyId'],
                'secret' => $result['Credentials']['SecretAccessKey'],
            ],
        ]);
``

**Comment by cjyclaire** [comment]
@tomnijboer It is possible definitely and you are on the right track. The way that you use [`assumeRole`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-sts-2011-06-15.html#assumerole) looks good to me, and I couldn't reproduce the error there. Could you double check those parameter values? Also, instead of extract `AccessKeyId` or `SecretAccessKey` manually by yourself, SDK also has a [`createCredentials`](https://github.com/aws/aws-sdk-php/blob/master/src/Sts/StsClient.php#L36) method that help create a valid `Credential` object for you.

>When I run the aws cli I need to supply a session token, but I don't know where to put in with the php code.

I'm a bit confused, referring to cli [examples](http://docs.aws.amazon.com/cli/latest/reference/sts/assume-role.html#examples), required parameters appear same. Could you explain a bit here? Are you suggesting general session token parameter as part of a credential content that used to initialize a `StsClient`?

Furthermore, #1077 PR is under review, which adds an AssumeRoleCredentialProvider that make this much easier. :)

**Comment by tomnijboer** [comment]
@cjyclaire thanks for your reply.
I will try the [createCredentials](https://github.com/aws/aws-sdk-php/blob/master/src/Sts/StsClient.php#L36) instead.

What I mean with the session token, is that the assumeRole from the cli is providing a "SessionToken".
And you need it to pass trough the api to use the temporary credentials.

> SessionToken  -> (string)
> The token that users must pass to the service API to use the temporary credentials. 

But I see the [createCredentials](https://github.com/aws/aws-sdk-php/blob/master/src/Sts/StsClient.php#L36) is setting them as well. 
Will let you know

**Comment by tomnijboer** [comment]
That did the trick, 

I will close the ticket

**Comment by cjyclaire** [comment]
Great！
