### ISSUE TITLE
Issue S3 uploadDirectory with removing directory after upload on S3

### ISSUE THREAD

**Issue by peterkomar** [aws/aws-sdk-php#1097]
Hello. 

In my code I need to move directory on S3  and I use method `uploadDirectory` but I can't remove directory immediately after uploading  on S3, code says 'Directory not empty' but directory actually empty. 

Calling `gc_collect_cycles` after `uploadDirectory` fixes this issue.

**Comment by cjyclaire** [comment]
@peterkomar Glad that you work out the problem by yourself, 
> calling `gc_collect_cycles` before remove file 

This works because `GuzzleHttp\Stream` object holds onto a resource handle until its `__destruct` method is called. Normally, this means that resources are freed as soon as a stream falls out of scope, but sometimes, depending on the PHP version and whether a script has yet filled the garbage collector's buffer, garbage collection can be deferred. `gc_collect_cycles` will force the collector to run and call `__destruct` on all unreachable stream objects.

**Comment by peterkomar** [comment]
Thanks for explanations
