### ISSUE TITLE
Can't multi-delete in S3 keys with XML characters in them

### ISSUE THREAD

**Issue by WilliamMayor** [aws/aws-sdk-php#1106]
I can't delete objects where the keys contain XML reserved characters. I have a function that does something like this:

```php
$objects = $s3->getIterator('ListObjects', array('Bucket'=>$bucket, 'Prefix'=>$prefix));
$deleteables = array();
foreach($objects as $object) {
    $deleteables[] = array('Key' => $object['Key']);
}
// Can only delete 1000 objects at a time
$chunks = array_chunk($deleteables, 1000);
foreach ($chunks as $chunk) {
    $s3->deleteObjects(array(
        'Bucket' => $bucket,
        'Delete' => array('Objects' => $chunk)
    ));
}
```

If `$prefix` is something like this: `/parent-folder/>` then I see this error:

```
Next exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "DeleteObjects" on "https://s3.amazonaws.com/BUCKET?delete"; AWS HTTP error: Client error: `POST https://s3.amazonaws.com/BUCKET?delete` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>MalformedXML</Code><Message>The XML you provided was not well-formed (truncated...)
 MalformedXML (client): The XML you provided was not well-formed or did not validate against our published schema - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>MalformedXML</Code><Message>The XML you provided was not well-formed or did not validate against our published schema</Message><RequestId>456EB42C266A71E5</RequestId><HostId>BTYOhuWh2XOXqWfrWHWCiec8JpGA9uqUMFspCNCqbjp9cnJCnkTdCo2Z+6pGTflk1a81kOywTks=</HostId></Error>' in /vagrant/api/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:192
```

I also get this error if `$prefix` is `/parent-folder/` when there are objects with XML characters in their keys that match this prefix.

I also can't delete these objects using the AWS console so this may be a larger issue?

I'm using SDK version 3.18.15 on PHP version 5.6.23.

**Comment by cjyclaire** [comment]
@WilliamMayor SDK accepts the path style in prefix, however there might be some problem with your code snippet, looks like in your each `chunk` loop, `deleteObjects` is called every time, which means the `'Object' => []'` array never get appended. To fix that, you need to do something like:
``` php
$param = [
    'Bucket' => $bucket,
    'Delete' => [
        'Objects' => [],
    ],
];
foreach ($chunks as $chunk) {
    $param['Delete']['Objects'] []= $chunk;
}

$res = $s3->deleteObjects($param);
var_dump($res);
```
In this way, `deleteObjects` is called only once to delete batch of objects with same prefix.

Also, regrading `$prefix` param used in your code, if you are trying to representing a folder path, you need to use `parent-folder/` instead of `/parent-folder/`.

Finally, for the `>` character, for example, it's true that for those XML characters that doesn't conform to the published xsd schema will fail the validation, I'd suggest some work around. Since the file name contains special characters, could you try `rawurlencode(SPECIAL_FILE_KEY)` for those files?

**Comment by WilliamMayor** [comment]
Hi @cjyclaire, thanks for the response.

I was under the impression that you could only send 1000 objects at a time to the deleteObjects endpoint. That's why I had the chunking. If I read it right your code sends an array of arrays of 1000 keys to the function. Does that do the queued calls for me?

I'll check the spurious leading slash in our code but I think we're doing the right thing. We have a global path prefix that I omitted in the example code. So the actual prefix would look like `$PREFIX/parent-folder/`. If we're doing this incorrectly, wouldn't we see a 404 instead of a malformed XML error?

Finally (and thanks again), is the suggestion to change the keys of the objects in S3 or to URL encode the keys in the delete request? We have a feature that allows public upload of files so we cannot guarantee that the file names would conform to any rules we set. We discovered this bug after a penetration test discovered some mishandling of special characters on our end. We're trying to write some tests for these cases so we avoid regression.

**Comment by cjyclaire** [comment]
@WilliamMayor Oh I see, thanks for clarification on those. That's true, then it should be fine, good to know about the path style is taken care. If you see further trouble with that, please let me know.

Then for those special characters, so, an XML parsing exception due to unescaped XML characters in the XML response is a server side issue that cannot be fixed by the SDK, sorry to know if that is something cannot change on your side. However, it would be great if you could let the Amazon S3 team know that this is important to you by posting to their  [forum](https://forums.aws.amazon.com/forum.jspa?forumID=24). Thank you again for your feedback on this.

**Comment by cjyclaire** [comment]
Closing due to ages, yet feel free to reopen with further comments or questions :)

**Comment by haoxi911** [comment]
For anyone met this issue, you may want to encode your S3 object keys with `htmlspecialchars($key, ENT_XML1 | ENT_QUOTES, 'UTF-8');`.

`deleteObjects` is a little bit different from other S3 APIs, that it sends payload as XML text, hence we need to escape characters like & < > " before composing the request.
