### ISSUE TITLE
SWF ignores page maximumPageSize parameter in pollForDecisionTask

### ISSUE THREAD

**Issue by ppaulis** [aws/aws-sdk-php#1113]
Hello!

We are using SWF through the PHP SDK and are doing the following call:

```
$result = $this->getClient()->pollForDecisionTask([
            'identity' => $this->getIdentity(),
            'domain' => $this->getDomain(),
            'maximumPageSize' => 200,
            'taskList' =>
            [
                'name' => $this->getTaskListName()
            ]
        ]);
```

However, the SWF client only returns the first 100 events. I could handle this using the pagination, but I'd prefer having also bigger pages, especially because AWS states in the docs, that the default page size is 1.000.

Is this just bad usage or is there perhaps a bug..?
Thanks for the help!

Pascal

**Comment by cjyclaire** [comment]
@ppaulis SDK doesn't build customization upon that API, taking a look to see if I could reproduce the issue ...

**Comment by ppaulis** [comment]
Great, thank you! Don't hesitate to post me your code snippet even if it
works. Perhaps this will give me more indications.

Sent from my Phone

Am 27.10.2016 6:59 nachm. schrieb "cjyclaire" <notifications@github.com>:

**Comment by cjyclaire** [comment]
@ppaulis Apology for getting back late on this, yet I couldn't reproduce the issue with `maximumPageSize` parameter, I didn't do anything different with your code snippet in calling the API. Thus I'm curious about why it goes wrong on your side.

May I ask is there other error thrown when you notice this behavior? Could you double check that `maximumPageSize` is spelled correctly? Because non-required typo parameters won't make it to server side in SDK.

**Comment by cjyclaire** [comment]
Closing due to ages, yet feel free to reopen with further questions or updates! :)
