### ISSUE TITLE
EcsCredentialProvider introduces 1sec latency for each request on EC2 instances

### ISSUE THREAD

**Issue by saintberry** [aws/aws-sdk-php#1132]
I think there is a bug with the logic in the `CredentialProvider::defaultProvider()` chain on EC2 instances.

If no credentials are passed into the client _and_ there is no credential cache configured, I believe 1sec (a default timeout) of latency is being introduced due to the order of the chain on EC2 instances.

If no credentials are found in the environment or ini the EcsCredentialProvider is called [before the InstanceProfileProvider](https://github.com/aws/aws-sdk-php/blob/master/src/Credentials/CredentialProvider.php#L78). The issue here is that in the EcsCredentialProvider a request is made to [http://169.254.170.2 with a 1sec timeout](https://github.com/aws/aws-sdk-php/blob/master/src/Credentials/EcsCredentialProvider.php#L45). On EC2 instances this request is just going to hang.

I think this bug was introduced in [this pull request](https://github.com/aws/aws-sdk-php/pull/1126/files) which removed a check to see if `getenv(self::ENV_URI)` was empty or not. I think this check was trying to determine if the instance was ECS or EC2.

Can someone else confirm this is the case?

I think it would be good for `EcsCredentialProvider` to fail early if the instance is not ECS and avoid that Guzzle request.

**Comment by cjyclaire** [comment]
@saintberry Thanks for noticing, so that PR doesn't remove the check, it lets the request to fall when wrapped in promise instead of throw exception immediately. Appreciate pointing out the latency there, `timeout` is configurable via provider now. However since the ecs credential is not cached correctly, it causes the latency. The  PR #1133 looks like making the correct fix by caching the ecs credentials properly. I'll take a deeper look into that and deliver the fix shortly. Thank you for your patients.

**Comment by anniballo** [comment]
Hello,

We are using the DynamoDB Session Handler in our PHP application and just noticed this same 1sec delay in every request to our application. Doing some digging we also found that the DynamoDB client when using the EC2 IAM role (instead of directly passing credentials in the config) was the culprit. We just moved our production infrastructure to hardcoded credentials but would like to move back to using the IAM role (for obvious security and simplicity) when fixed. Do you have any more information on this?

Thanks

Diego

**Comment by cjyclaire** [comment]
@anniballo Thanks for the information and appreciate your patience there, the PR is in progress, and I'm keeping a close eye on it. Could you try pass in the `timeout` parameter as a quick work around for this? Or as another workaround, could you use them directly instead of calling `defaultProvider()` currently?

**Comment by anniballo** [comment]
Is a bit complex make some tests currently, we are an e-commerce company and December is a nightmare ;)
I'll let you know if I can try these workarounds.
Thank you so much for your answer.

**Comment by cjyclaire** [comment]
The fix PR has been merged, will be tagged in the next release :), free free to reopen if that fix doesn't work :)

**Comment by saintberry** [comment]
Thanks @vasanthperiyasamy for the PR / fix.

@cjyclaire do you have a rough timeframe on when this will get tagged? At work we're happy waiting on this fix before doing a deployment so we don't have to push out any workarounds.

**Comment by cjyclaire** [comment]
@saintberry Just Out. :)
