### ISSUE TITLE
Region parameter support for Rekognition

### ISSUE THREAD

**Issue by pavankumarkatakam** [aws/aws-sdk-php#1159]
Hi,
 Im working with rekognition, While creating the RekognitionClient object I have passed region as `us-west-2` So it is checking S3 Object in that region when doing the detectFaces operation. I think it's better to have a Region parameter in detect faces to specify a different region S3 Object.

**Comment by imshashank** [comment]
Hi,

Thanks a lot for the feedback. We will look into the request and will update this thread once the feature has been implemented. 

Thanks

**Comment by pavankumarkatakam** [comment]
Actually, my application is in production stage and used by several members. I'm using S3 (region: ap-souteast-1) to upload the images as well as documents. Now if I want to make use of Rekognition the S3 object should be in the same region  because the credentials are given to create the RekognitionClient it is taking to the S3 credentials But rekognition is only available in the three regions im using `us-east-2`. So my intention is to make the rekognition such that it can take the s3 object from other region also.

**Comment by cjyclaire** [comment]
@pavankumarkatakam Thanks for the information, I heard your request, our services never stop launching new regions : ), which would relieve the pain there. Because initializing a client for a region is handy and easy, making cross region calls from server side might be expensive.

Meanwhile, since this is a feature that should be considered by service side instead of SDK side. I'll contact service team internally to let them know about this request. Thank you again for the feedback.

**Comment by cjyclaire** [comment]
Closing, yet feel free to reopen with further questions or adding more comments. : )
