### ISSUE TITLE
How to set DynamoDB Endpoint to connect to dynamodb-local?

### ISSUE THREAD

**Issue by sanfx** [aws/aws-sdk-php#1164]
I am running dynamo local on server already running apache2/php/MySql:

this machine is accessible on local network with `ceres.local` so in that case

will I have a end point `http://loclhost:8000` or `http://ceres.local:8000` ?

the problem is when I try to run `php MoviesCreateTable.php`

I get 500 Server error:;

> Unable to create table:
> Error executing "CreateTable" on "http://localhost:8000"; AWS HTTP error: Server error: `POST http://localhost:8000` resulted in a `500 Server Error` response:
> {"__type":"com.amazonaws.dynamodb.v20120810#InternalFailure","message":"The request processing has failed because of an  (truncated...)
>  InternalFailure (server): The request processing has failed because of an unknown error, exception or failure. - {"__type":"com.amazonaws.dynamodb.v20120810#InternalFailure","message":"The request processing has failed because of an unknown error, exception or failure."}
>

**Comment by mtdowling** [comment]
That looks like you were able to connect to localhost, but got an error from the local web service. Perhaps it's failing due to a signature error. Can you try passing in a `region` of "local" instead of overriding the `endpoint`?

**Comment by sanfx** [comment]
still the same error.

if I just change it to `local` , however I open the url `http://ceres.local:8000` (ceres.local is name on my local network) in browser , downloads the file `ceres.local` which has this in it:

`{"__type":"com.amazonaws.dynamodb.v20120810#MissingAuthenticationToken","message":"Request must contain either a valid (registered) AWS access key ID or     X.509 certificate."}`

is it due to missing credentials ? however I did saved my creditential file `~/.aws/creditentials` with private key and secret key !

**Comment by imshashank** [comment]
@sanfx  Can you please provide us with more details on how are you setting up the browser. Also how are you trying to reach to your server. It will be helpful if you can share any code snippets you are using to talk to the dynamo local.

**Comment by cjyclaire** [comment]
@sanfx Also, we have updated our [`Getting Help`](https://github.com/aws/aws-sdk-php#getting-help) section recently, feel free to engaged in other channel for help. 

I did a quick check for dynamoDB local, and couldn't reproduce the issue. Since your error message indicates `MissingAuthenticationToken`, are you using session token in your credentials? is it valid as well? Is using dynamoDB local the only situation that you have this error with? Could you double check your credentials in the file are valid and sourced correctly? Above are some quick troubleshooting suggestion that you might want to look at.

If you still finds this might be a bug for this repo, could you provide more background information that could help us reproduce the issue? For example, is SDK used directly or integrated with other frameworks? etc.

Closing due to ages, yet feel free to reopen with further question and details :)

**Comment by avinash8083** [comment]
getting below error when trying to save in dynamodb

{
    "__type": "com.amazonaws.dynamodb.v20120810#MissingAuthenticationToken",
    "Message": "Request must contain either a valid (registered) AWS access key ID or X.509 certificate."
}
