### ISSUE TITLE
How to set Proxy settings?

### ISSUE THREAD

**Issue by oaksu** [aws/aws-sdk-php#1175]
I have tried to use the following settings and have tried changing the @http to request.options and have had no success? How do I pass in proxy settings to the SDK? Note: All my configuration that i've removed is within the <> brackets.

            $sharedConfig = [
            'region'  => 'eu-central-1',
            'version' => 'latest',
            'endpoint' => 'http://<endpoint address>:<endpoint port>/',
            'endpointScheme' => 'http',
            '@http' => array(
                'proxy' => 'http://<user>:<password>@<proxy address>:<proxy port>/',
            ),
            'secret'  => '<secret key>',
            'credentials' => array(
            'key' => '<Access Key>',
            'secret'  => '<Secret Key>',
            )
        ];`

        // Create an SDK class used to share configuration across clients.
        $sdk = new \Aws\Sdk($sharedConfig);

**Comment by cjyclaire** [comment]
@oaksu Thanks for the info, if this is the configuration shared across client, you could try
``` php
'http' => [
    'proxy' => ...
]
```
instead of `@http`, `@http` is the configure that passed per command.
More [proxy](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#proxy) documentation.

Also, we have updated our [getting help](https://github.com/aws/aws-sdk-php#getting-help) section recently, feel free to engaged in other channel as well. If you still finds this might be a bug for this repo, feel free to reopen, and it would be great if you could provide some code snippet or logs that helps reproducing : )
