### ISSUE TITLE
Retry delays are too short when throttling errors occur

### ISSUE THREAD

**Issue by joshdifabio** [aws/aws-sdk-php#1186]
As far as I can tell, when a throttling error occurs, the SDK will delay for between 0 and 100 ms before retrying the request. In the case of DynamoDB, delays are half of this, so, between 0 and 50 ms. These delays will be used both for the first and second retries as far as I can tell. This means that, when a throttling error occurs, the SDK might attempt to retry the request twice more near-instantly, further increasing the request rate which is already too high. These default delay values seem way too low, especially the minimum values of 0ms, when dealing with throttling errors.

It would be great if `RetryMiddleware` was modified to pass the error to the delay callback such that the delay could be varied based on the type of error which occurred (e.g., wait longer after throttling errors). I would also like to see the default delays changed to something more practical.

See [`RetryMiddleware`](https://github.com/aws/aws-sdk-php/blob/3.22.6/src/RetryMiddleware.php) and [`DynamoDbClient`](https://github.com/aws/aws-sdk-php/blob/3.22.6/src/DynamoDb/DynamoDbClient.php).

Edit: I just realised that the delays are even shorter than I thought: the first retry will always happen instantly! This definitely needs to change for throttling errors.

**Comment by jeskew** [comment]
Hi @joshdifabio,

The SDK's retry middleware uses a "full jitter" strategy to minimize both the number of retries that must be made and the amount of time a request takes to succeed after factoring in retries. A more detailed explanation of the approach taken and some of the advantages it poses can be found on [the AWS architecture blog](https://www.awsarchitectureblog.com/2015/03/backoff.html).

The delay decider function only takes account of the number of retries already attempted because the type of error isn't a reliable indicator of when a retry might succeed. A `ProvisionedThroughputExceededException` exception might be immediately retryable (if the request arrived 2ms before a throttling window ended), and a 503 or 504 might represent a server state that isn't actually retryable for another 30 seconds. FWIW, the retry delay strategy implemented in the SDK for DynamoDB is based on [that service's official recommendation](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html#Programming.Errors.RetryAndBackoff).

**Comment by joshdifabio** [comment]
Thanks for the prompt reply! That makes sense, however, as far as I can tell, the full jitter delay implementation in the PHP SDK is broken: the first retry always happens instantly, whereas there should be an upper limit of 100ms for the first retry delay and 50ms for DynamoDB.

Here's a table comparing the delay upper limits for the PHP and Java SDKs.

| Retry no. | Java upper limit | PHP upper limit | PHP upper limit for DynamoDB
| - | - | - | - |
| 1 | 100ms | 0ms | 0ms |
| 2 | 200ms | 100ms | 50ms |
| 3 | 400ms | 200ms | 100ms |
| 4 | 800ms | 400ms | 200ms |

So, unless I'm missing something, the PHP SDK is not behaving the same as the Java SDK, nor is it behaving in line with the DynamoDB docs, which recommend an initial delay of _up to 50ms_.

[Java upper limit](https://github.com/aws/aws-sdk-java/blob/7844c64cf248aed889811bf2e871ad6b276a89ca/aws-java-sdk-core/src/test/java/com/amazonaws/retry/PredefinedBackoffStrategiesTest.java#L33)
[PHP upper limit](https://3v4l.org/KuSYU)

**Comment by cjyclaire** [comment]
@joshdifabio Looks this this is a bug that we need to fix, I'll open a PR soon the address the fix
Thank you for reporting : )

**Comment by cjyclaire** [comment]
@joshdifabio Actually, not. PHP does have the [same behavior](https://github.com/aws/aws-sdk-php/blob/master/tests/RetryMiddlewareTest.php#L137) with java.
The php example provided gives `$retries` from 0, that's the correct behavior for no retries.
When looking at it from 1, it matches.

Though the `initial delay of up to 50ms.` is not caught, taking a look at the docs right now ...

**Comment by jeskew** [comment]
@cjyclaire I think there's an extra `- 1` in the [default delay decider](https://github.com/aws/aws-sdk-php/blob/master/src/RetryMiddleware.php#L100) that causes the first retry to only be delayed by network round trip time. The delay function is meant to be called with the number of retries that have already been attempted rather than the ordinal of the current retry.

**Comment by cjyclaire** [comment]
@jeskew Ah I see, thanks for pointing that out. I'll open a PR to fix that.

**Comment by cjyclaire** [comment]
The fix PR has been merged, the fix will be tagged in next release. Closing, yet feel free to reopen with further question and details : )

**Comment by joshdifabio** [comment]
Thanks guys!
