### ISSUE TITLE
missing Sns code and examples

### ISSUE THREAD

**Issue by madduci** [aws/aws-sdk-php#1193]
The SnsClient.php is empty and no test is given, to understand the API in PHP

**Comment by cjyclaire** [comment]
@madduci That's expected, our service clients are automatically generated instead of hand written. 

Our API docs can be found [here](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Sns.SnsClient.html), also we have a [SNS Message Validator](https://github.com/aws/aws-php-sns-message-validator)  which could be used solo as well : )
