### ISSUE TITLE
Pre signed URL content length range

### ISSUE THREAD

**Issue by Fanda36** [aws/aws-sdk-php#1202]
Hi,

how can add file size condition to pre signed URL [doc](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html#sigv4-ConditionMatching) ?

```
public static function getPresignedURL() {
        $cmd = self::$client->getCommand('PutObject', [
            'Bucket' => 'MY_BUCKET',
            'Key' => 'test.png',
            'content-length-range' => [0, 10485760]
        ]);

        $request = self::$client->createPresignedRequest($cmd, '+10 minutes');
        $url = (string) $request->getUri();

        return $url;
}
```

Thanks.

**Comment by cjyclaire** [comment]
@Fanda36 Thanks for the information, looks like you might be looking for [`Presign-Post`](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-presigned-post.html) instead of `Presigned Url`. The Link I provided contains instruction for usage : )

Also, we have updated our [`#getting help`](https://github.com/aws/aws-sdk-php#getting-help) sections recently, feel free to get involved in other channels as well. Happy to help with any possible SDK bugs and feature requests : )

**Comment by cjyclaire** [comment]
Closing due to ages, yet feel free to reopen with further comments or questions : )
