### ISSUE TITLE
fopen - failed to open stream

### ISSUE THREAD

**Issue by generak13** [aws/aws-sdk-php#1215]
Hi.
I want to download files from S3 through my site. I use S3 Stream Wrappers, read data by chunks and send to client.
So at first I use fopen in order to create stream. In 99% it works fine. But sometimes I receive **[PHP] fopen(s3://bucket_name/dir/archive.zip): failed to open stream: "Aws\S3\StreamWrapper::stream_open" call failed**. I can not reproduce it with my custom script. I just see this message in my logs. The size of these files are about 500 bytes (not so big). How to fix this?

I use AWS SDK v2.
PHP 5.3.

Thanks.

**Comment by imshashank** [comment]
@generak13  I would recommend using the latest version of our SDK (v3).

Also, these errors can be caused by a lot of factors including network issues, timeouts etc. Also, you can probably catch the error and retry the request if it fails but that will depend on your use case.

I guess it will be hard to reproduce this error you can, however, turn on the debug mode and that will help us figure out the problem behind the error.
