### ISSUE TITLE
ECS task command argument

### ISSUE THREAD

**Issue by ankitsam** [aws/aws-sdk-php#1290]
How can i pass command line arguments using CommandOverrides?
It works when running via shell like this on cluster:
`docker run repo /bin/bash -c 'cd repo && chmod +x run.sh && bash run.sh "arg1"'`

but the task remains in running state when started via php

```
$result = $client->runTask([
    'cluster' => 'repo',
    'count' => 1,
    'overrides' => [
        'containerOverrides' => [
            [
                'command' => ['/bin/bash','-c','cd repo && chmod +x run.sh && bash run.sh "arg1"'],
                'name' => 'repo',
            ],
        ],
    ],
    'taskDefinition' => 'scripts:6',
]);
```

**Comment by imshashank** [comment]
@ankitsam This is more of a docker question. I would recommend simplifying the command or better use `ENTRYPOINT` in your docker image to run this so that you don't have to override at runtime.

You can do this in your Dockerfile

```
WORKDIR /repo
RUN chmod +x /repo/run.sh 
CMD ["<path to run.sh>"]
```
or better replace CMD with
```
ENTRYPOINT ["/repo/run.sh", "arg1"]
```
Besides that this is documentation for ecs run task-> http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-ecs-2014-11-13.html#runtask

In any case, you can simplify the command as such:

```
'command' => ['/repo/run.sh arg1']
```
Docker will run any command on the default shell `sh`

Another way to debug is to ssh into the EC2 box and look at running containers and you can see their output by running

```
docker logs <container-id>
```

I will be able to help you better if you share what is the error you are getting. Please let me know if there is something I can help you with.

**Comment by ankitsam** [comment]
@imshashank  i need to pass the parameter to docker image as the docker  image functionality is based on parameter, so i cant use the entrypoint/command in docker image as well as cant use fixed parameter values in  entrypoint/command in task definition, 

I logged in via ssh and ran the docker run command above & it worked, but it didnt worked via both task or ecs api, so its not necessarily related to just sdk.

**Comment by imshashank** [comment]
@ankitsam  I suspect this has to do something with the way parameters are passed to ECS task. I would recommend looking at DockerFile 'CMD' usage:
 https://docs.docker.com/engine/reference/builder/#cmd

You can simplify the command as ->
```
'command' => ['/repo/run.sh', "arg1"]
```

Please let me know if this fixes the issue. Since this is a usage question, we recommend asking this on StackOverflow as described in [ReadMe](https://github.com/aws/aws-sdk-php#getting-help) file.

**Comment by ankitsam** [comment]
I read more about it, turns out the parameteres are passed properly and script is getting executed but giving error after some time. The .sh file calls a python python script which uses selenium/firefox and is giving error on line `driver = webdriver.Firefox()` as 
`selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette`

But its working when i run via `docker-run`, i m not sure if its related to [No TTY issue](https://github.com/aws/amazon-ecs-agent/issues/462)? or any other permission issue?

**Comment by nswarnkar** [comment]
Any resolution met so far?
