### ISSUE TITLE
Expired security token

### ISSUE THREAD

**Issue by bakura10** [aws/aws-sdk-php#1307]
Hi,

Im not sure if this is related to the Aws sdk, as I didn't have any issue for more than one year, but this morning I had requests failing when hitting dynamoDB.

It says that the security token included in the request is expired (400 bad request). The instance is deployed using beanstalk and is using an IAM profile. The only change is that yesterday's I've activated the auto scaling new feature for our synamodb tables but je it was the culprit it should have failed on a larger scale.

Could this be related to the PHP SDK ?

Thanks

**Comment by imshashank** [comment]
@bakura10 This doesn't look like something caused by the PHP SDK.

I would recommend having a look at your IAM keys and policies. Some keys/assumed roles can be set to expire after a certain period of time.

Closing this issue since it looks more related to service teams and not the SDK. Please feel free to open the issue if you think the problem is being caused by the PHP SDK.
