### ISSUE TITLE
Set SNS Sender ID?

### ISSUE THREAD

**Issue by gohanman** [aws/aws-sdk-php#1321]
Is there a way to set the sender ID ([AWS.SNS.SMS.SenderID](http://docs.aws.amazon.com/sns/latest/dg/sms_publish-to-phone.html)) via the `SnsClient`?

I tried two different ways and in both cases I got an HTTP 200 response and the message was delivered but it was listed as from a numeric code rather than the specified senderID.

Using setSMSAttributes:
```php
$sns = new Aws\Sns\SnsClient(/* ... */);
$sns->setSMSAttributes([
    'attributes' => ['DefaultSenderID' => 'ABC'],
]);
$result = $sns->publish([
    'Message' => 'Test sending msg from SNS',
    'PhoneNumber' => '+15558675309',
]);
```

and using MessageAttributes
```php
$sns = new Aws\Sns\SnsClient(/* ... */);
$result = $sns->publish([
    'Message' => 'Test sending msg from SNS',
    'PhoneNumber' => '+15558675309',
    'MessageAttributes' => [
        'AWS.SNS.SMS.SenderID' => [
            'DataType' => 'String',
            'StringValue' => 'ABC',
        ],
    ],
]);
```

**Comment by kstich** [comment]
Hi @gohanman, it looks like you're trying to use a `SenderID` for a country that might not support it. [Please see this documentation for restrictions on `SenderID`](http://docs.aws.amazon.com/sns/latest/dg/sms_supported-countries.html).

**Comment by gohanman** [comment]
D'oh. Sorry for not reading closely enough.

**Comment by arvindsharma4** [comment]
@kstich I have used the same code of MessageAttributes to send SMS
Now  I want to set SenderID for Indian Phone number
Also I checked supports SenderID country here https://docs.aws.amazon.com/sns/latest/dg/sms_supported-countries.html

message receiving successfully but with HP-NOTICE sender not custom set SenderID

**Comment by janamcroods** [comment]
i am facing same issue.

**Comment by janamcroods** [comment]
> Hi @gohanman, it looks like you're trying to use a `SenderID` for a country that might not support it. [Please see this documentation for restrictions on `SenderID`](http://docs.aws.amazon.com/sns/latest/dg/sms_supported-countries.html).

India is supported country yet Message delivering with HP-NOTICE

**Comment by RAsija11** [comment]
Facing same issue for India phone number. 
Message delivered successfully with sender as HP-NOTICE. 
Though I set below attributes using setSMSAttributes.

var params = {
  attributes: { /* required */
    'DefaultSMSType': 'Transactional', /* highest reliability */
    'DefaultSenderID': 'ABC', 
  }
};

**Comment by RAsija11** [comment]
Any solution available ?

**Comment by diehlaws** [comment]
@arvindsharma4 @janamcroods @RAsija11 This behavior stems from the service API rather than the AWS SDK for PHP. As a result, the most effective method of troubleshooting this behavior would be reaching out to our Premium Support team by opening a [new support case](https://console.aws.amazon.com/support/cases#/create) under the SNS service, or via the [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=72) for this service.

**Comment by diehlaws** [comment]
Searching for this behavior online reveals that other SNS users are encountering the [same issue](https://stackoverflow.com/questions/46953243/when-does-aws-sns-sms-senderid-gets-changed-from-custom-id-to-awss-default-id/47563117#47563117) for destination phone numbers in India. A member of the AWS team for Mobile Messaging mentions in this post:

> If your destination phone number is in India, your Sender ID must be registered to be able to work. You can request to register a Sender ID by opening a support ticket with AWS support (which has no cost).

Since this can be considered an official solution to this behavior, I'll be locking this issue to prevent further confusion on this topic.
