### ISSUE TITLE
Slow GuzzleHttp\Handler\CurlMultiHandler::tick() with SQS

### ISSUE THREAD

**Issue by moeseth** [aws/aws-sdk-php#1351]
Hi,

<img width="997" alt="29181702-2500f8d0-7e22-11e7-9c71-61d2246b4fab" src="https://user-images.githubusercontent.com/534443/29183809-fea14f0c-7e29-11e7-96aa-05381b484b12.png">

I'm having problem with SQS.

I'm getting the following

`60 calls to GuzzleHttp\Handler\CurlMultiHandler::tick`

My curl version is
`curl 7.38.0 (x86_64-pc-linux-gnu) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3 Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP`

It happens very often.

How can I debug it?

Thanks.

**Comment by kstich** [comment]
As it was stated over on the [Guzzle issue](https://github.com/guzzle/guzzle/issues/1898), this means you're waiting for a response from SQS - either due to not using the [promise based `*Async()` operations](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/promises.html) or having no other work to do while waiting for the response to an `*Async` request.

If this happens consistently, we'd encourage you to [post on the SQS forum](https://forums.aws.amazon.com/forum.jspa?forumID=12) or [contact support via one of the methods provided on the AWS Contact Us page](https://aws.amazon.com/contact-us/).
