### ISSUE TITLE
Random empty response from SQS 

### ISSUE THREAD

**Issue by nexik** [aws/aws-sdk-php#1364]
From time to time I got **Aws\Sqs\Exception\SqsException** it's normal or I should fix my code?

Error executing "ReceiveMessage" on "https://sqs.eu-central-1.amazonaws.com/{account-id}/{queue-name}"; AWS HTTP error: cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Curl got nothing** looks like ok response for me because there is no items in the queue, but before catching this exception I want to make sure it's just no items in queue instead of some other serious problem.

This happens on php 7.1 with aws-sdk v3

**Comment by kstich** [comment]
cURL error 52 in this context that no response was received by cURL after completely sending your request. It does not mean that there were no items in the queue. This is usually due to a network or service issue, I'd recommend that you open a support ticket with [AWS Support](https://console.aws.amazon.com/support/home/).

**Comment by nexik** [comment]
Thanks,

I will create ticket on AWS Support
