### ISSUE TITLE
content-type: binary/octet-stream

### ISSUE THREAD

**Issue by mexitek** [aws/aws-sdk-php#138]
I am using a very small script to keep my image folders in sync with s3. 

```
$client->uploadDirectory('/local/directory', 'my-bucket');
```

I am noticing that the content-type for all my images are being uploaded as "binary/octet-stream". All the images have appropriate extensions. Not really sure where to start looking.

![screen shot 2013-08-23 at 4 18 24 pm](https://f.cloud.github.com/assets/515706/1018747/3b29b636-0c31-11e3-80f6-86bf53eeb435.png)

Any advise is appreciated.

**Comment by fireproofsocks** [comment]
Not an issue, but related: if you are using this package to bind the PHP internals (file_exists, getimagesize, etc) and you're using those to determine MIME type, your server will download the file locally during some of those requests, and if your server fills up, it may report the mime-type as application/octet-stream instead of the file's true MIME type.  Clean up your server, and the functions will report accurately again.
