### ISSUE TITLE
S3 file upload error using AWS php sdk. 

### ISSUE THREAD

**Issue by gerryats** [aws/aws-sdk-php#1390]
Hi 

I am using Laravel 5.4 and using S3 for file upload i am getting this Open SSL error while uploading file. 

Here is the error Log from laravel debugger. 

[06:42:17] LOG.error: exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "PutObject" on "https://elevatecds.s3.amazonaws.com/4/elevatedashbaord_1507185737"; AWS HTTP error: Error creating resource: [message] fopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
[file] /var/www/laravel/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 324
[message] fopen(): Failed to enable crypto
[file] /var/www/laravel/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 324
[message] fopen(https://elevatecds.s3.amazonaws.com/4/elevatedashbaord_1507185737): failed to open stream: operation failed
[file] /var/www/laravel/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php

Thanks 
Gerry

**Comment by kstich** [comment]
It looks like OpenSSL is having trouble verifying your certificates. Check out [this thread](https://github.com/requests/requests/issues/4247) and the specific error you receive "error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed" to work on solving it.

Closing since this isn't an issue with the SDK.
