### ISSUE TITLE
Crash on S3Client instantiation

### ISSUE THREAD

**Issue by axettone** [aws/aws-sdk-php#1421]
Version: 3.36
Error: PHP Fatal error:  Uncaught InvalidArgumentException: The service "s3" is not provided by the AWS SDK for PHP.

Code:
...
```
use Aws\S3\S3Client;
...
$s3ClientArgs = [
            'version'   => 'latest',
            'region'    => $s3Region,
            'signature_version' => 'v4',
            'credentials' => [
                'key'       => $s3Key,
                'secret'    => $s3Secret
            ]
        ];
        $this->s3Client = new S3Client($s3ClientArgs);
```

**Comment by axettone** [comment]
Tried with 3.30, it works.

**Comment by kstich** [comment]
I'm not able to reproduce this issue on version 3.36.35. Do you know what specific version of 3.36 you received the error on? Does an entry for `'s3'` exist in your `src/data/manifest.json[.php]` file?

**Comment by axettone** [comment]
Thank you kstich! I re-installed via composer and now I have 3.36.37 that works! I didn't remember the specific version I tried 2 days ago. I don't know what to say... :-(
I'm sorry!

**Comment by kstich** [comment]
Let us know if you recover the version that wasn't working for you so we can investigate.

**Comment by davelassanske** [comment]
I'm getting an error trying to instantiate S3Client - I'm on 3.109.1 with this code sample:

`use Aws\Common\Aws;
use Aws\S3\S3Client;
use Aws\S3\Iterator;
use Aws\S3\Exception\S3Exception;
use Aws\CloudFront\CloudFrontClient;
use Aws\CloudFront\Exception\CloudFrontException;
use Aws\Common\Exception\InvalidArgumentException;
use Aws\Common\Exception\RequiredExtensionNotLoadedException;

try{
	$this->s3Client = new S3Client([
		'credentials' => array(
			'key' => $this->config->item('aws_key'),
			'secret' => $this->config->item('aws_secret')
		),
		'region' => $this->config->item('aws_region'),
		'version' => '2006-03-01'
	]);
} catch (ServiceResponseException $e) {
	print_r($e->getMessage());
} catch (S3Exception $e) {
	print_r($e->getMessage());
} catch (InvalidArgumentException $e) {
	print_r($e->getMessage());
} catch (RequiredExtensionNotLoadedException $e) {
	print_r($e->getMessage());
}`

I don't get any kind of error back - the page just dies and returns a 504.

Oddly enough we have a second, seemingly identical environment that does NOT crash with the same codebase. Is there a way to catch the error because what we have isn't spitting out anything - no logs, no catches...
