### ISSUE TITLE
S3Client throws Invalid configuration value provided for "api_provider" error

### ISSUE THREAD

**Issue by larsbo** [aws/aws-sdk-php#1483]
I cannot create a S3Client. I tried the code examples from https://docs.aws.amazon.com/aws-sdk-php/v3/guide/examples/s3-examples-configuring-a-bucket.html but always got 
`Invalid configuration value provided for \"api_provider\". Expected callable, but got array(2)\n\napi_provider: (callable)\n\n  An optional PHP callable that accepts a type, service, and version\n  argument, and returns an array of corresponding configuration data. The\n  type value can be one of api, waiter, or paginator."`

My code ist just as in the example (only changed region): 
```
$client = new S3Client([
    'region' => 'eu-central-1',
    'version' => '2006-03-01'
]);
```

**Comment by kstich** [comment]
I am not able to reproduce your issue on v3.52.1. That error message reads like you're passing an array of `['api_provider' => (callable)]` as the value for `'api_provider'` instead of just the callable.

* What version of the AWS SDK for PHP are you using?
* What was your method for installing?
* Have you set any other configuration related to the SDK or the client?
* Have you made any changes to the S3Client file or others?

**Comment by larsbo** [comment]
Hi Kevin,
Thank you for the answer.

I'm using version `3.52.0` installed with composer (`composer require aws/aws-sdk-php`).
I didn’t add any other params (like the mentioned `api_provider`). Just `region` and `version`.
I didn’t change anything of the package files, of course.
There are no other packages directly involved but there are other project files that will be loaded before the autoload function. Maybe there has been set any other global things that could manipulate the aws package?

**Comment by larsbo** [comment]
Ok, it works fine as a stand-alone project without the other project files. But I still wonder what could cause the error. Any suggestions maybe? 😃
