### ISSUE TITLE
[CloudFront] Signer getSignature() accepts string but doesn't actually work when giving it as a parameter

### ISSUE THREAD

**Issue by IlCallo** [aws/aws-sdk-php#1499]
[Here](https://github.com/aws/aws-sdk-php/blob/4baba19877e363b971a4600a4bc3b3fa94fdfbba/src/CloudFront/Signer.php#L48) it's written that both integer and string are valid types for `$expires` parameter.
Following this I used a string representation of the timestamp, but the generated URLs where wrong even tought no exception/error was risen.
This is due to the fact that the `$expires` parameter is directly passed to `createCannedPolicy` method which is then encoded as a json.
The problem here is that integers are encoded without quotes, whereas strings are encoded with quotes.

    ['AWS:EpochTime' => 1519031281]
    ['AWS:EpochTime' => '1519031281']

When encoded, the difference between those two notations influences the signature generation

    {"AWS:EpochTime": 1519031281}
    {"AWS:EpochTime": "1519031281"}

URLs generated when `$expires` is a string won't be recognized as valid by CloudFront.

IMO, there can be two ways to deal with this:

- easy way: remove `string` as accepted parameter type for `$expire` and return an exception if anything other than an integer or null is given;

- hard way: accept integer, string and maybe even DateTime and internally manage the conversion to an integer timestamp, adding some validation login. If you want to follow this path, I already did something for my [Laravel adapter](https://github.com/dreamonkey/laravel-cloudfront-url-signer) and Spatie did something similar with [their package](https://github.com/spatie/url-signer) from which mine derivates. Expecially the `isFuture()` and `getExpirationTimestamp()` methods.

In AWS docs, [only integer values are accepted](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-creating-signed-url-canned-policy.html#private-content-canned-policy-statement-example):

> "AWS:EpochTime":ending date and time in Unix time format and UTC

> Do not enclose the value in quotation marks.

**Comment by kstich** [comment]
Thanks for the report here.

I think, since the `$expires` annotation of `string|integer|null` comes along with the comment of `UTC Unix timestamp used when signing with a canned policy.`, that the better first pass here is to cast this to an `int`. This allows for no new exception being necessary while still fulfilling the expectations on both ends.

After that, we can take a task for improving the interface to allow for passing a `DateTime` like [SigV4's `->presign()` functionality](https://github.com/aws/aws-sdk-php/blob/master/src/Signature/SignatureV4.php#L79).
