### ISSUE TITLE
Understanding retry logic in the AWS PHP SDK

### ISSUE THREAD

**Issue by jonathanbull** [aws/aws-sdk-php#1520]
It seems that only the DynamoDB and S3Clients have [retry logic enabled][1].

It seems like the `retries` config value has no effect on other services. Is there an easy way to enable this on others (e.g. SQS), or have I misunderstood this functionality?

I've located the `clientConfig.setUseThrottleRetries(true);` [option][2] in the Java SDK, but have yet to find an equivalent in the PHP SDK.

  [1]: https://github.com/aws/aws-sdk-php/search?utf8=%E2%9C%93&q=%24args%5B%27retries%27%5D%5B%27fn%27%5D%20%3D%20&type=
  [2]: https://aws.amazon.com/blogs/developer/introducing-retry-throttling/

**Comment by kstich** [comment]
The AWS SDK for PHP sets up 3 retries by default. The Dynamo and S3 clients both have some customization around their retry strategy. You can read more about the [`'retries'` parameter here](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#retries).

Retries are handled by the [`RetryMiddleware`](https://github.com/aws/aws-sdk-php/blob/master/src/RetryMiddleware.php). When a response is received, the middleware runs its `$decider`, usually [the default](https://github.com/aws/aws-sdk-php/blob/master/src/RetryMiddleware.php#L58) unless configured otherwise, to determine if the request should be retried. Unless it's configured otherwise, the [default backoff method](https://github.com/aws/aws-sdk-php/blob/master/src/RetryMiddleware.php#L132) uses a ["Full Jitter"](https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/) strategy.

**Comment by jonathanbull** [comment]
Great, my mistake. Thank you for the detailed reply.
