### ISSUE TITLE
AWS HTTP error: cURL error 7

### ISSUE THREAD

**Issue by evtnlife** [aws/aws-sdk-php#1537]
Hello, i am trying to use SES in my website, but when i try to send a mail i receive that error: `Error executing "SendRawEmail" on "https://email.us-east-2.amazonaws.com"; AWS HTTP error: cURL error 7: Failed to connect to email.us-east-2.amazonaws.com port 443: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

can someone help me in this inssue? thanks!

**Comment by kstich** [comment]
I am unable to reproduce your issue. It looks like your connection to SES is being refused when cURL initially attempts to establish it. I found [this similar thread](https://forums.aws.amazon.com/thread.jspa?threadID=264500) on [the Amazon SES forums](https://forums.aws.amazon.com/forum.jspa?forumID=90&start=0). I'd suggest posting there or opening a ticket with [AWS Support](https://console.aws.amazon.com/support/home/). You may wish to try updating OpenSSL as well, since this is an HTTPS connection.
