### ISSUE TITLE
Random AWS HTTP error: cURL error 35

### ISSUE THREAD

**Issue by neoacevedo** [aws/aws-sdk-php#1546]
Hi. I ma randomly receiving the following error:
`AWS HTTP error: cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to s3.amazonaws.com:443`

Credentials are ok but since some days this error is happening.It occurs on any S3 operation.

I'm using aws.phar 3.54.3 but it happens too with 3.55.12

**Comment by kstich** [comment]
This is caused by a problem with the underlying I/O, not the SDK itself. Try using [`openssl_error_string`](http://php.net/manual/en/function.openssl-error-string.php) or [`curl_strerror`](http://php.net/manual/en/function.curl-strerror.php) to find more information. You may also try updating your version of OpenSSL or cURL.

**Comment by liudhzhyym** [comment]
Same problem here

**Comment by byb37** [comment]
same problem here
 @vaibhavdhanawade  @liudhzhyym  did you find solution for that?
