### ISSUE TITLE
Aws s3 connection timeouts sometimes

### ISSUE THREAD

**Issue by vishal-akg** [aws/aws-sdk-php#1565]
I sometimes get the following error while downloading a video file from s3 to ec2 instance, my ec2 instance is in north virginia and s3 bucket in pacific mumbai -

> PHP Warning:  Error executing "GetObject" on "https://s3.ap-south-1.amazonaws.com/bucket/file.MP4"; AWS HTTP error: Error creating resource: [message] fopen(https://s3.ap-south-1.amazonaws.com/bucket/file.MP4): failed to open stream: Connection timed out

and i am using following php code snippet-
```php
$fp = fopen($filename, 'wb');
if($stream = fopen('s3://'.$bucket.'/'. $data['key'], 'rb')) {
    while(!feof($stream)) {
        stream_copy_to_stream($stream, $fp, 1024);
    }
    fclose($stream);
    fclose($fp);
}
```

I haven't tweeked in any of the configuration regarding timeout

**Comment by kstich** [comment]
The [`StreamWrapper` will perform a `trigger_error` call](https://github.com/aws/aws-sdk-php/blob/master/src/S3/StreamWrapper.php#L727) instead of throwing an exception. If you need to handle these cases, I'd recommend moving to [using `S3Client::getObject` and using the `SaveAs` parameter](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#getobject), where you can wrap it in a try/catch block

```php
try {
    $client->getObject([
        'Bucket' => $bucket,
        'Key' => $data['key'],
        'SaveAs' => $filename,
    ]);
} catch (S3Exception $e) {
    ...
}
```

**Comment by vishal-akg** [comment]
this method isn't suitable for downloading large files and i didn't get how using SaveAs parameter is going to prevent from connection timeout issue?

**Comment by kstich** [comment]
When using the `StreamWrapper`, exceptions like this `Connection timed out` issue are turned in to warnings due to PHP limitations. The SDK attempts to retry connection errors by default, but you may have reached the retry attempt limit. If you wish to be able to catch these exceptions, you'll need to use the `S3Client` directly.
