### ISSUE TITLE
not possible to write in bucket via stream with binary mode

### ISSUE THREAD

**Issue by douglasjam** [aws/aws-sdk-php#1576]
Currently I write into a bucket via stream handler that is very convenient. But now I have the necessity to write a gzipped file, that leads me to use the binary mode, 'wb' and currently the library does not support it.

The current workaround is to write in disk gzipped, and then upload it, what leads me to double reading/writing.

```
$s3Client->registerStreamWrapper();

$bucketPath = sprintf('s3://%s/%s', getenv('MYBUCKET'), $filename);
$handler = gzopen($bucketPath, 'wb9');

while ($record = $cursor-> #getNext()) {
    gzwrite($handler, implode("\t", $record->toArray()) . PHP_EOL);
 }

gzclose($handler);
```

> Mode not supported: wb9. Use one 'r', 'w', 'a', or 'x'.
>  /var/www/php/vendor/aws/aws-sdk-php/src/S3/StreamWrapper.php:738
>  /var/www/php/vendor/aws/aws-sdk-php/src/S3/StreamWrapper.php:140

**Comment by kstich** [comment]
The StreamWrapper [removes the 'b' and 't' mode settings](https://github.com/aws/aws-sdk-php/blob/master/src/S3/StreamWrapper.php#L137) because the operation is binary safe. What it doesn't do is pull the compression level, causing a `Mode not supported` failure. In looking at this, I tried making that update only to hit a `stream_cast` issue to generate a File Descriptor, which we're not capable of generating from what I've found.

----

The default 'w' stream should be safe for gzipped content if it comes in gzipped. I'm able to write gz files using only a 'w' stream this way:

```php
$textContents = str_repeat('This is a test string' . PHP_EOL, 512);

$handler = fopen($textBucketPath, 'w');
fwrite($handler, gzencode($textContents, 9));
fclose($handler);

echo 'Generated .gz file: ';
var_dump($textContents === gzdecode(file_get_contents($textBucketPath)));
// Generated .gz file: bool(true)
```

The final file is 87B and decompresses back to the original size.

If you're on PHP >= 7.0, you can use the [`deflate_init`](http://php.net/manual/en/function.deflate-init.php)/[`deflate_add`](http://php.net/manual/en/function.deflate-add.php) functions like so:

```php
$handler = fopen($textBucketPath, 'w');
$deflateContext = deflate_init(ZLIB_ENCODING_GZIP, ['level' => 9]);
for ($i = 0; $i < 512; $i++) {
    fwrite($handler, deflate_add($deflateContext, $textPortion, ZLIB_NO_FLUSH));
}
fwrite($handler, deflate_add($deflateContext, '', ZLIB_FINISH));
fclose($handler);
```

Then use [the matching function](http://php.net/manual/en/ref.zlib.php) for your `ZLIB_ENCODING_*` constant or the [`inflate_init`](http://php.net/manual/en/function.inflate-init.php)/[`inflate_add`](http://php.net/manual/en/function.inflate-add.php) functions to un-gzip.

**Comment by douglasjam** [comment]
Doing a foreach and writing with gzencode does not work.
But deflat_init and deflat_add works properly, thank you.

`$handler = fopen('/tmp/test.csv', 'w');
$deflateContext = deflate_init(ZLIB_ENCODING_GZIP, ['level' => 9]);


$strings = [
    'Hello, how are you?' . PHP_EOL,
    'I am fine thanks' . PHP_EOL,
    'Hello, how are you?' . PHP_EOL,
];

foreach ($strings as $string) {
    fwrite($handler, deflate_add($deflateContext, $string, ZLIB_NO_FLUSH));
}

fwrite($handler, deflate_add($deflateContext, '', ZLIB_FINISH));
fclose($handler);

echo gzdecode(file_get_contents('/tmp/test.csv'));`
