### ISSUE TITLE
Generating signed CloudFront URLs is not working

### ISSUE THREAD

**Issue by martinbean** [aws/aws-sdk-php#1578]
Using the SDK to generate CloudFront URLs is not working. I’ve dug through the code and AWS guides on how to generate a signed URL, but I still get an “AccessDenied” error message in the browser. Because there’s no other information, I can’t diagnose the issue.

Here is my code:

```php
<?php

require realpath(__DIR__.'/../vendor/autoload.php');

use Aws\CloudFront\CloudFrontClient;

$cloudfront = new CloudFrontClient([
    'credentials' => [
        'key' => '[redacted]',
        'secret' => '[redacted]',
    ],
    'region' => 'eu-west-1',
    'version' => 'latest',
]);

$resource = 'https://[redacted].cloudfront.net/[redacted]';

$expires = time() + 600;

$signedUrl = $cloudfront->getSignedUrl([
    'url' => $resource,
    'expires' => $expires,
    'key_pair_id' => '[redacted]',
    'private_key' => realpath(__DIR__ . '/../storage/pk-[redacted].pem'),
]);
```

* I’m using the access key ID and secret access key of an IAM user that has the Administrator policy applied.
* The distribution ID is a CloudFront distribution in my AWS account.
* The path is correct.
* The key pair ID is the ID of a CloudFront key pair from the “Security” section of my AWS account settings.
* The private key file is the private key file corresponding to the above key pair ID, and the path to the file is correct.

Where am I going wrong?

**Comment by kstich** [comment]
I'm unable to reproduce your issue here - I can use both the `UrlSigner` class and the `->getSignedUrl` method to sign urls. I don't see anything obvious wrong with your inputs either.

I'd recommend verifying each piece of the configuration you're using, including [specifying the trusted signer for the distribution](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-trusted-signers.html) and that you're accessing the signed url before it expires as you didn't list these above. [Amazon CloudFront - Serving Private Content with Signed URLs and Signed Cookies](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/PrivateContent.html)

If you're still having issues, I'd recommend asking a question on [StackOverflow](https://stackoverflow.com/), opening a support ticket with [AWS Support](https://console.aws.amazon.com/support/home/), or reaching out on the [CloudFront Forum](https://forums.aws.amazon.com/forum.jspa?forumID=46).

**Comment by martinbean** [comment]
Thanks for getting back to me. I did open a [Stack Overflow issue][1]; AWS support said they couldn’t help me as I don’t have a support plan, and the only response I got on the [AWS forums][2] was a support agent asking me to private message them further details but never heard back when I did.

Nonetheless, I have since diagnosed the issue. The objects in my S3 bucket weren’t publicly-accessible, and I hadn’t added an Origin Access Identity to allow CloudFront to access the objects.

[1]: https://stackoverflow.com/q/51152615/102205
[2]: https://forums.aws.amazon.com/thread.jspa?threadID=285238#jive-message-857092
