### ISSUE TITLE
permission-denied in 2.8.dev-x

### ISSUE THREAD

**Issue by syed1994** [aws/aws-sdk-php#1579]
HEAD is now at 64fa4b07 2.8.31 release
error: unable to create file src/Aws/S3/Exception/RequestTorrentOfBucketErrorException.php: Permission denied

**Comment by howardlopez** [comment]
If you're using composer, this should work within your composer file to get v2.8.x of the SDK:

```
    "require": { 
        "aws/aws-sdk-php": "~2.8" 
    }
```

This option lets you specify checking out the 2.8 branch directly, which should lead to the same result.

```
    "require": { 
        "aws/aws-sdk-php": "2.8.x-dev" 
    }
```

If this is not what you're asking, please elaborate with the code or command sample that you're using.

**Comment by syed1994** [comment]
i try to use composer.json as you mentioned above but getting same error.Am using php 5.3.8 . I have attached screen shots for your reference.
![error](https://user-images.githubusercontent.com/41457552/43033668-1a4be05c-8ceb-11e8-9fa0-f7976e18c833.PNG)
![composer](https://user-images.githubusercontent.com/41457552/43033669-1cf097b2-8ceb-11e8-89b8-2b9333906774.PNG)

**Comment by howardlopez** [comment]
I used your exact composer file and was able to successfully run `composer update` on a new project, so I suspect you may be having an issue with local repo changes or config settings. Have you tried running `composer update` in an empty directory with that composer file? 

There are a variety of errors in that log. Since you are getting a message about outdated packages, you can try running the following to update composer itself and clear package cache:

```
composer self-update
composer clear-cache
```

Since there are permissions errors as well, I'd verify that the relevant directories have the proper write access. 

If you're still having Composer issues, the [Composer Github repo](https://github.com/composer/composer/issues) may be a good resource for further troubleshooting.
