### ISSUE TITLE
Error on credetials using sample.php

### ISSUE THREAD

**Issue by ranrinc** [aws/aws-sdk-php#1617]
I'm a new user trying to have S3 working with aws-sdk-php

This is my enviroment:
* macbook
* composer installed
* aws bundle installed
* MAMP webserver running Apache2 and MySQL and PHP 7.1.12

So, I'm making new iAM called new-user with **Programmatic access** using **AdministratorAccess**.
Off course having **access key id** and **secret key**.

Then create my credentials using `aws configure` at my home directory.

follow this guide  https://aws.amazon.com/developers/getting-started/php/ to have git + composer to have it properly install.

Then run it on my localhost and hope for the best.

This is what I get on the browser:
<img width="1050" alt="screen shot 2018-08-31 at 10 26 03 pm" src="https://user-images.githubusercontent.com/15801696/44921947-2a26e500-ad6e-11e8-87e2-ef594b81b387.png">

This is appear on my php_error logs:
<img width="649" alt="error" src="https://user-images.githubusercontent.com/15801696/44922447-9e15bd00-ad6f-11e8-902b-590e3288dcc8.png">

What did I do wrong?

**Comment by diehlaws** [comment]
Hi @ranrinc, thanks for reaching out. It sounds like the AWS SDK for PHP is unable to locate the [AWS credentials file](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_profiles.html) in your home directory. If ~/.aws/credentials is present and readable you should be able to run sample.php via your terminal (`php sample.php`) with successful results. If your web server is running as a different user than the one used to run `aws configure` then it's possible your web server does not have read access to your credentials file.

**Comment by ranrinc** [comment]
@diehlaws 

Yes you are right... my webserver will not have access to reach my home folder. Is there away to change the location of .aws/ to somewhere within the reach of the webserver? How should I change the code in order to do this? Thanks

**Comment by diehlaws** [comment]
Supplying credentials to the AWS SDK for PHP can be done in [several different ways](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials.html): 
1. Set the environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` for the user you're using for your web server
2. Create a new shared credentials file (or copy your existing one and change its permissions accordingly) in the home directory of the user you're using for your web server so that it can access this file
3. Assume an IAM role (best used when running your application in EC2)
4. Use a credential provider
5. Generate temporary credentials from AWS STS

Each of the options above has an example shown in the documentation page I linked. You can also hard-code credentials into your application per the example shown below, however this method is not recommended since it is surprisingly easy to forget to remove credentials from code before committing it to a repository. This can result in your AWS credentials being exposed to more people than you intend, which often results in a compromised AWS account. As such, this method should be used as a last resort or when testing code locally that will never be accessible to others.

```php
$key = 'AKIAIOSFODNN7EXAMPLE'
$secret = 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
$s3 = new S3Client([
    'region' => 'us-east-1',
    'version' => '2011-06-15',
    'credentials' => new Credentials($key, $secret)
]);
```
