### ISSUE TITLE
ELBv2 addListenerCertificates() fails with ValidationError in sdk-php, but works in aws-cli

### ISSUE THREAD

**Issue by dawolf** [aws/aws-sdk-php#1632]
I am having trouble adding a ACM certificate to my ALB using the PHP SDK.

Seeing the following error with sdk-php version 3.62.9 and latest 3.67.15:
```
ValidationError (client): You cannot set the isDefault parameter for a certificate. - <ErrorResponse xmlns="http://elasticloadbalancing.amazonaws.com/doc/2015-12-01/"
```

This is the code used:
```
      $result = $this->elb->addListenerCertificates([
        'Certificates' => [
          ['CertificateArn' => $arn, 'IsDefault' => false],
        ],
        'ListenerArn' => $this->lb_arn,
      ]);
```
Omitting the 'IsDefault' parameter does not help.
Other operations, like DescribeListenerCertificates() return the expected results.

The same certificate can be installed on the LB using the cli without a problem.

Using the same IAM credentials on the aws-cli works (tested on aws-cli/1.16.17 Python/3.5.2 Windows/10 botocore/1.12.7 and aws-cli/1.15.35 Python/3.5.2 Windows/10 botocore/1.10.35)
```
aws elbv2 add-listener-certificates --listener-arn {my_listener_arn} --certificates CertificateArn={cert_arn}
```

works as expected, returns a OK message and installs the certificate on the ALB:
```
CERTIFICATES    {cert_arn} False
```

Region tested in: eu-west-1

**Comment by dawolf** [comment]
Turns out the documentation does list the parameter `IsDefault` with a capital i, while the code works only with a lower case i and `isDefault`

Maybe somebody can point me in the right direction to update the doc or fix the i. Thanks.

**Comment by diehlaws** [comment]
Thanks for bringing this to our attention @dawolf. The reason `isDefault` works when `IsDefault` doesn't is because `isDefault` is not getting sent in the API call since it is not included in the `Certificates` shape - you can test this by swapping the lowercase i with any other letter and watch the request succeed. As for the error you're receiving when including a properly capitalized `IsDefault` in your `addListenerCertificates` input, it looks like the [ELB API docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_Certificate.html) state not to include this property in the Certificate data type when specifying a certificate as an input parameter.

I'll be reaching out internally to the ELB team about improving this data type, as the current iteration seems pretty counter-intuitive from the end user's perspective.
