### ISSUE TITLE
CloudFront Create Distribution Required Fields

### ISSUE THREAD

**Issue by jschwarzwalder** [aws/aws-sdk-php#1634]
When reviewing the AWS SDK for PHP documentation for the CloudFront Client, there are inaccuracies in the list of required fields for the [Distribution Config](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-cloudfront-2018-06-18.html#shape-distributionconfig) when calling Create Distribution.

I can successfully create a distribution with the following parameters:
`'CallerReference' ,
'Comment',
'DefaultCacheBehavior',
'Enabled',
'Origins',
`

When I view the PHP API Documentation, some of these fields are marked as not required (like CallerReference), and some that are optional are marked as required (like Aliases, and CachedBehaviors). However, when I view the [CloudFront API documentation](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CreateDistribution.html) it states that the fields I successfully used are the only fields required. I do not know the origin of this error.

**Comment by howardlopez** [comment]
The way the `// REQUIRED` comment works on the parameter syntax examples is that they signify requirement if its parent is being used. For example, here's the beginning part of the `CreateDistribution` syntax:

```
$result = $client->createDistribution([
    'DistributionConfig' => [ // REQUIRED
        'Aliases' => [
            'Items' => ['<string>', ...],
            'Quantity' => <integer>, // REQUIRED
        ],
        ...
    ]
)
```

`Quantity` within `Aliases` is marked as required because if `Aliases` is supplied, then `Quantity` within `Aliases` must be supplied. `Aliases` itself is not required, and thus if `Aliases` is not supplied, then `Quantity` is not required.

**Comment by howardlopez** [comment]
With respect to the `DistributionConfig` shape, it looks like there is a bug in the docs generation for the `Required` flag there. We'll post back here when a fix is in place.

**Comment by howardlopez** [comment]
The API documentation is now updated with the corrected logic for `Required` members in shapes.
