### ISSUE TITLE
CloudwatchClient::putMetricDataAsync() doesn't resolve promise unless wait() is called. 

### ISSUE THREAD

**Issue by ricardofiorani** [aws/aws-sdk-php#1646]
With the following simple example:
```php
$cloudWatchClient = new CloudWatchClient([...]); //Omitted
$metricData = [...]; //Omitted

echo 'starting' . PHP_EOL;
$promise = $cloudWatchClient->putMetricDataAsync($metricData);

$promise->then(function () {
    echo 'send successfully';
}, function ($data) {
    echo 'there was a problem' . PHP_EOL;
    var_dump($data);
});

while ($promise->getState() != Promise::FULFILLED) {
    echo 'waiting...' . PHP_EOL;
    sleep(1);
}

return;
```
It hangs on `waiting...` forever and never fulfils the promise unless I call `wait()` on the promise.
Since the SDK uses Guzzle, according to Guzzle Documentation of promises, it should resolve by itself asynchronously without having to call the method `wait()` : https://github.com/guzzle/promises.

My credentials and metricData array are correct since I can see the metrics put on Cloudwatch when I use the synchronous way.

Tested on:
SDK version 3.69.4
PHP 7.2.9

**Comment by diehlaws** [comment]
Thanks for reaching out to us @ricardofiorani. I am able to reproduce this, however this behavior looks to be expected from Guzzle - you'll want to invoke `tick` manually for the API call to actually be sent rather than relying on `wait()` to do so for you. 

As explained [here](https://github.com/guzzle/guzzle/issues/1127), asynchronous calls involving `promise` do not automatically call `tick` as this could unintentionally resolve other promises, leading to unforseen consequences depending on what `promises` are involved within your use case. Further discussion on this topic can be found in [this thread](https://github.com/aws/aws-sdk-php/issues/621).

**Comment by ricardofiorani** [comment]
Honestly this is such a let down, but then, it's not aws's sdk fault so...
Anyway, Thank you for your response @diehlaws

**Comment by esetnik** [comment]
@diehlaws @ricardofiorani Can you provide a code sample showing how to call `tick()` with this service. I faced the same issue and haven't found a complete solution.

**Comment by ricardofiorani** [comment]
@esetnik 

As I mentioned, you have to manually call the method `wait` from the promise. This will cause the CURL (or whatever adapter you use) to tick.

If you want to call it directly from your CURL Handler, then here there is a few examples https://github.com/guzzle/guzzle/issues/1127

**Comment by esetnik** [comment]
@ricardofiorani do you have a complete code sample? I wasn't able to make it work using the curl handler approach you linked. I'm looking for a fire and forget request that doesn't block my php application at all. I'm seeing regular performance issues with the `putMetricData` apis which routinely take >1s to respond in approximately 0.1% of my requests and AWS is insistent that there is no problem and the api is working correctly. I'll have to stop using the service for monitoring if I can't guarantee better performance characteristics, specifically finding a way to make it non-blocking.
