### ISSUE TITLE
InstanceProfileProvider does not handle when the response contains an invalid JSON

### ISSUE THREAD

**Issue by alquerci** [aws/aws-sdk-php#1664]
Hello,

We have a dynamically modified infrastructure managed by auto-scaling rules. EC2 instances are launched and terminated upon load.

Issue
------

Some times the instance metadata server respond with an invalid JSON and we got this exception.

The response body here is partial.

```
Unexpected instance profile response code:  
Stack trace:
#0 /project/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php(53): Aws\Credentials\InstanceProfileProvider->decodeResult('{\n  "Code" : "S...')
```

See https://github.com/aws/aws-sdk-php/blob/3.70.2/src/Credentials/InstanceProfileProvider.php#L102

Note
-------

* When occurred the common retry behaviour is skipped.
* I saw boto provides a fix for such issue https://github.com/boto/botocore/issues/1049

**Comment by diehlaws** [comment]
Hi @alquerci, thanks for reaching out about this. Unfortunately the Instance Profile Credential Provider does not use the same retry middleware that is used when issuing service API calls, and its default Guzzle handler does not automatically retry the Instance Profile retrieval when an unsuccessful response is returned by the Instance Metadata service. 

That being said, it is possible to pass your own handler to the Credential Provider so that retries can be implemented to fit your use case. Below is an example of implementing a custom handler on an Instance Profile Credential Provider for an S3 client based on our [Handlers and Middleware](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_handlers-and-middleware.html) documentation page.

```php
$myHandler = function (CommandInterface $cmd, RequestInterface $request) {
    $result = new Result(['foo' => 'bar']);
    // Implement retry logic here
    return Promise\promise_for($result);
};

$provider = CredentialProvider::instanceProfile([
    'handler' => $myHandler
]);

$creds = $provider()->wait();

$client = new S3Client([
    'region' => 'us-west-2',
    'version' => 'latest',
    'credentials' => $creds
]);
```

**Comment by alquerci** [comment]
Hello @diehlaws, thanks to take care about this.

For sure extends the library is the solution to provide the expected behaviour. I create this issue because such feature/patch may have the place on `aws-php-sdk` and not only library user side. Because this issue is hard to detect and need to use a dedicated retry bahaviour because it is bound to AWS infrastructure.

* For further investigation how is it possible that the Instance Metadata service return an invalid JSON on the response body?
* Does it is planned to patch the Instance Profile Credential Provider?

Note: `json_decode()` does not throw an exception when on Invalid JSON but just return `false`. On this case it most likely a bug on the Instance Metadata service. What do you think?

**Comment by alquerci** [comment]
@diehlaws I want to know whether the Instance Profile Credential Provider is open for to be patched with a pull request?

**Comment by diehlaws** [comment]
@alquerci, apologies for the delay in response from our end. To answer your questions directly:

> For further investigation how is it possible that the Instance Metadata service return an invalid JSON on the response body?

There are a few cases where the instance metadata service is known not to work as expected:
- The instance metadata service can be unavailable if the OS has no route to the metadata service as seen [here](https://aws.amazon.com/premiumsupport/knowledge-center/waiting-for-metadata/). 
- Requests to the metadata service are throttled on a per-instance basis as mentioned in the 'Throttling' section of [this documentation page](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html#instancedata-data-retrieval).
- There are a few AWS Forum posts that discuss issues interfacing with the instance metadata service [here](https://forums.aws.amazon.com/thread.jspa?messageID=831094) and [here](https://forums.aws.amazon.com/thread.jspa?messageID=686746). The first one may be exclusive to m5.large instances, however the second one may apply to your use case depending on how your auto-scaling group starts the application that uses the SDK.

Unfortunately the behavior you're describing does not sound similar to any of the above since you're receiving an OK 200 response from the metadata service (just not a complete/expected response), so it's possible you've encountered an edge case with Auto-Scaling and the instace metadata service that warrants further investigation from the EC2 service team. I recommend opening a [new support case](https://console.aws.amazon.com/support/v1#/case/create) under the EC2 service as the Premium Support engineers working under that profile will have more in-depth knowledge of how the instance metadata service works.

>Is it planned to patch the Instance Profile Credential Provider?

I've brought this up as a feature request in our most recent sprint, and it has been added as a backlog item to investigate in the near future.

> Is the Instance Profile Credential Provider open for to be patched with a pull request?

We would be happy to review a PR for this! You may review our contribution guidelines [here](https://github.com/aws/aws-sdk-php/blob/master/CONTRIBUTING.md).

**Comment by alquerci** [comment]
@diehlaws Thank you for this feedback as it opens a road to a resolution.

Your message grabs mainly all related issues. :+1: 

I am convinced that implementing a naive retry solution will not be enough and may aggravating the problem.

That's why your feedback provides a good clarification of the situation.
