### ISSUE TITLE
No response from AWS SES when I try to send an email

### ISSUE THREAD

**Issue by AngieRd** [aws/aws-sdk-php#1669]
Hi, 
I have a recent issue with my emails, on week ago I started get errors in my email sending, problem is that sometimes when I call this function `sendEmail` it never returns the `Aws/Result` or any `Exception`. So my script is looped waited for it. The issue is sporadic. I supposes that my requested couldn't be added to AWS queue but I would get an Exception at least.

I tried to find a timeout setting that I could set to don't eternally wait, but I couldn't find it in documentation. I have 2 years using this service and I haven't get error until now.

Somebody else has experienced this issue? 
Where can I set a timeout for this calls related to SES Class? 

Note: I'm using AWS SDK PHP version 3.67.20

I'm getting this error
```
AWS HTTP error: Client error: `POST https://email.us-west-2.amazonaws.com` resulted in a `403 Forbidden` response:
<ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/">
  <Error>
    <Type>Sender</Type>
    <Code>SignatureDo (truncated...)
 SignatureDoesNotMatch (client): Signature expired: 20181107T003842Z is now earlier than 20181107T005054Z (20181107T005554Z - 5 min.) - <ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/">
  <Error>
    <Type>Sender</Type>
    <Code>SignatureDoesNotMatch</Code>
    <Message>Signature expired: 20181107T003842Z is now earlier than 20181107T005054Z (20181107T005554Z - 5 min.)</Message>
  </Error>
  <RequestId>xxxxxxx-xxxx-xxxx-xxxx-13bf5130fec1</RequestId>
</ErrorResponse>
```

Thanks,

**Comment by diehlaws** [comment]
Thanks for reaching out to us @AngieRd. The error you're receiving suggests there is an issue with the clock on the host generating the request signature (likely the same host issuing the request, unless you're presigning the request elsewhere and passing it to the host sending the request). This could be caused by things such as the time zone not being set properly on this machine, or its clock being more than a few minutes out of sync at the time the request is signed. You may need to double check the machine's time zone and synchronize its clock with a public NTP server to avoid this behavior.

I was able to reproduce the error message with valid IAM user credentials by manually setting my local machine's clock back 6 minutes, however this error was caught as an `AwsException` as expected using the `catch` block shown below.

```php
try {
    $result = $SesClient->sendEmail([
      // sendEmail parameters
    ]);
    $messageId = $result['MessageId'];
    echo("Email sent! Message ID: $messageId"."\n");
} catch (AwsException $e) {
    // output error message if request fails
    echo("The email was not sent. Error message: ".$e->getAwsErrorMessage()."\n");
    echo "\n";
}
```

**Comment by AngieRd** [comment]
Thank you for your response @diehlaws, weird thing here is that the 99% of the sendings the message ID is returned within 0.5 secs but 1 of 100 emails the request hang a long time, in the end, the email is sent, other times I get that error.

I would suppose that if my server's timezone is wrong I should get same error in all requests to SES, right?

**Comment by AngieRd** [comment]
I have synchronized NTP Time in my server and now it's working. 
I let the link for Ubuntu SO that I followed 
https://www.tecklyfe.com/fix-ubuntu-timedatectl-ntp-sync-no/

Thank you so much for your help @diehlaws 
I think this ticket can closed.
