### ISSUE TITLE
Word Press | Missing required client configuration options : AWS PHP SDK 3.X 

### ISSUE THREAD

**Issue by techman1984** [aws/aws-sdk-php#1670]
Hi There,

I have installed AWS PHP SDK 3.X in a Word Press container. SDK integration works fine.. But some of the core Word Press features are broken and i have following error in logs:

[07-Nov-2018 14:54:53 UTC] PHP Fatal error: Uncaught InvalidArgumentException: Missing required client configuration options:

version: (string)

A "version" configuration value is required. Specifying a version constraint
ensures that your code will not be affected by a breaking change made to the
service. For example, when using Amazon S3, you can lock your API version to
"2006-03-01".

Your build of the SDK has the following version(s) of "s3": * "2006-03-01"
Few observations :

I'm consistently getting this error whenever i try to create a new page in WordPress Editor
I'm getting an error for S3Client, but i'm not using any S3 Client.
Here is some other information:

Word Press Version - 4.9.8
PHP Version - 7+
Please take a look and share your thoughts.

Thanks,
Ashwini

**Comment by diehlaws** [comment]
Hi @techman1984, thanks for reaching out to us about this. The error you're seeing typically comes up when a service client is initialized without a 'version' parameter - in this case it looks to be an S3 Client. If you cannot see the full stack trace pointing out where this error is originating you may want to search your application's directory for PHP files containing an S3 client initialization, then check to make sure those are specifying an API version in the client parameters. This can be done with `grep` as shown below. 

```
grep -rnw '/path/to/application/' -e 'new S3Client' -e 'new Aws\S3\S3Client' --exclude-dir=/path/to/aws-sdk-for-php/
```

-r will search recursively,
-n will include the line number where the expression was found,
-w will match the whole word instead of partial matches,
-e will search for the given expression, and can be used multiple times in the same command to search for multiple expressions,
--exclude-dir is used to exclude the SDK's installation directory so you don't mistakenly remove 'S3Client' from any files in the SDK.

I hope this helps you identify where your S3Client is being improperly initialized! Please don't hesitate to reach back out if you continue running into trouble with this.

**Comment by techman1984** [comment]
Hi Alex,

Thanks for sharing this. I have already tried that option but this does not solve the issue.

Any other pointers?

Regards,
Ashwini

**Comment by diehlaws** [comment]
Unfortunately the troubleshooting steps taken on your end are not clear to me - it sounds like you tried searching for 'new S3Client' and 'new Aws\S3\S3Client' and weren't able to find any instances of these expressions, please correct me if I'm wrong. It might be worth searching for just 'S3Client' as well since the S3 Client initialization in [version 2](https://docs.aws.amazon.com/aws-sdk-php/v2/guide/service-s3.html) of the AWS SDK for PHP is different from version 3.
If your `grep` search does not show any files that initialize an S3 Client in your entire WordPress directory, you shouldn't be getting this error. Reviewing the full stack trace would point out the files that are involved in this error, which would help narrow down where to look for this misconfiguration. 

It is possible that one or more of your WordPress plugins conflicts with the AWS SDK for PHP v3.x as seen [here](https://github.com/aws/aws-sdk-php-symfony/issues/10#issuecomment-163409593), [here](https://wordpress.org/support/topic/missing-required-client-configuration-options/), [here](https://wordpress.org/support/topic/the-aws-sdk-usage-seem-to-conflict-with-other-plugins-using-aws-sdk/), and [here](https://wordpress.org/support/topic/missing-required-client-configuration-options-2/). I suggest disabling your WP plugins systematically to ensure this isn't the cause of your error. 
You could disable all WP plugins and enable them one by one until you start seeing this error again to identify the culprit, or take a binary search approach where you disable half your plugins, check to see if the behavior persists, if it does then disable half of the remaining enabled plugins and repeat until things work as expected. From there, enable one by one the plugins from the last set of plugins that were disabled until you start seeing the error again to see which plugin is conflicting with the SDK.

**Comment by techman1984** [comment]
++ Patrick

Hi Alex,

Thanks for your email. I think you are right and this seems to be a third-party plugin issue. I think I have found the plugin.. but instead of enabling or disabling plugins one by one, I used the following word press function ‘exception::getTrace();’. I think I’m close now.

Anyways, I appreciate your help.

Regards,
Ashwini

**Comment by techman1984** [comment]
Hi Alex... This was caused due to a third party plugin which was using SDK 2.0...since... now we migrated to 3.0.. it started throwing error. 

Anyways, Thanks for your help.
