### ISSUE TITLE
Deprecation of FILTER_FLAG_SCHEME_REQUIRED and FILTER_FLAG_HOST_REQUIRED in PHP 7.3

### ISSUE THREAD

**Issue by growbeauty** [aws/aws-sdk-php#1692]
> Deprecated: filter_var(): explicit use of FILTER_FLAG_SCHEME_REQUIRED and FILTER_FLAG_HOST_REQUIRED is deprecated in vendor/elasticsearch/elasticsearch/src/Elasticsearch/ClientBuilder.php on line 686

FILTER_FLAG_SCHEME_REQUIRED and FILTER_FLAG_HOST_REQUIRED are removed in php 7.3

[https://wiki.php.net/rfc/deprecations_php_7_3#filter_flag_scheme_required_and_filter_flag_host_required](url)

Affected method:
```php
// \Elasticsearch\ClientBuilder
private function prependMissingScheme($host)
    {
        if (!filter_var($host, FILTER_VALIDATE_URL, FILTER_FLAG_SCHEME_REQUIRED)) {
            $host = 'http://' . $host;
        }

        return $host;
    }
```

**Comment by diehlaws** [comment]
Hi @growbeauty, thanks for reaching out to us. The warning you're receiving looks like it is referring to the PHP client for Elasticsearch rather than the AWS SDK for PHP - I was able to locate the function you mention in [another repository](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/ClientBuilder.php#L672) that does not belong to Amazon. Opening an issue under that repository would be more appropriate in this case.
