### ISSUE TITLE
Crypto missing? aws/aws-sdk-php:3.6

### ISSUE THREAD

**Issue by kostiag** [aws/aws-sdk-php#1704]
I am on php 3.6. Need S3EncryptionClient. My understanding was that it is available since ver 3.4. Using composer.

need S3EncryptionClient

use Aws\S3\Crypto\S3EncryptionClient
use Aws\Crypto\S3EncryptionClient

Crypto is missing, no errors reported during install.

**Comment by diehlaws** [comment]
Hi @kostiag, thanks for reaching out to us. The S3 Encryption Client (Aws\S3\Crypto\S3EncryptionClient) was added to the AWS SDK for PHP in the release of version [3.38.0](https://github.com/aws/aws-sdk-php/blob/master/CHANGELOG.md#3380---2017-11-08) on Nov 8 2017. This release is 32 minor versions ahead of version [3.6.0](https://github.com/aws/aws-sdk-php/blob/master/CHANGELOG.md#360---2015-10-06), which was released Oct 6 2015. 

Is there any particular reason you cannot use a version of the AWS SDK for PHP that is newer than 3.6.0? That version is quite old and will be missing a lot of functionality that has been added to the SDK since 2015.

**Comment by kostiag** [comment]
Yeah, I understand and not a very good reason other than no time to switch even though on the to do list. 
Not sure I follow though how is 3.38 ahead of 3.6?

**Comment by diehlaws** [comment]
Thanks for the clarification @kostiag, and I'm glad to hear that updating the SDK worked as expected. I'll be closing out the issue here since it sounds like things are now in order on your end. If you continue to see issues related to the S3 Encryption Client, please do not hesitate to comment on the issue so we may re-open it to continue working on this.

Software version numbers typically do not follow the same rules as standard decimal notation, instead they are broken down into three individual numbers separated by periods - major, minor, and patch version numbers. As a result, instead of multi-digit numbers signifying sub-versions of their single-digit counterparts, single-digit numbers will typically signify an older version than multi-digit numbers. This applies to major versions (20.0.0 is newer than 3.0.0), minor versions (1.29.0 is newer than 1.5.0), and patch numbers (1.2.15 is newer than 1.2.8).
