### ISSUE TITLE
openssl_sign(): supplied key param cannot be coerced into a private key

### ISSUE THREAD

**Issue by pawansharma-headspire** [aws/aws-sdk-php#1715]
Timezone : GMT+05:30

For generating signed url, the following code is working for almost 6 months for me,
```
$cloudFront->getSignedUrl([
            'url' => $url,
            'expires' => $expires,
            'private_key' => 'key.pem',
            'key_pair_id' => 'ID'
        ]);

```
but yesterday night suddenly, it started throwing error 

`openssl_sign(): supplied key param cannot be coerced into a private key`

And the Backtrace led me to `/src/CloudFront/Signer.php Line 100`

which simply does `openssl_sign` using the supplied public key which is fetched by using `file_get_contents()`.

And today afternoon it started working fine again, I can assure you that `key.pem` was never modified.

From Yesterday night 02:00AM to 07:00AM I called this code multiple times and it always gave me the same error. But when in afternoon at 01:00PM I ran the same code, it ran perfectly like nothing happened.

I was finally able to get the same error if I manually modified `key.pem` which led me to believe that somehow `file_get_contents()` couldn't read the key file properly at that time.

**Comment by diehlaws** [comment]
Hi @pawansharma-headspire, thanks for reaching out to us. Unfortunately I'm not able to reproduce this from my end, however given your description of the issue it sounds like this may have been a transient error in loading your private key. It does not seem likely that any changes were made to PHP (or to the AWS SDK for PHP) in your environment, as such this does not sound like an issue that stems from the SDK itself. This sounds like it was most likely caused by something happening with the environment in which you were running this code, my best guess would be that the storage device containing your private key may not have been available to fully load the key. 

Were you able to read your private key to ensure its integrity during the time you were receiving this error? If you being to see this behavior consistently during the given timeframe, that would be the first troubleshooting step that I would suggest performing. It may also be a good idea to write a standalone PHP script that loads your private key via `openssl_sign()` (or just `file_get_contents()`) without using the AWS SDK for PHP to see if this behavior persists without involving our SDK.
