### ISSUE TITLE
StreamWrapper fails silently for big file upload ~4GB+ (SDK v3.81)

### ISSUE THREAD

**Issue by tomekit** [aws/aws-sdk-php#1717]
I've got AWS SDK v3.81 and PHP 7.2.10-0ubuntu0.18.04.1, my app relies heavily on StreamWrapper, especially `copy` function which is used to read/write from S3.

First issue is that StreamWrapper fails to upload a file ~4GB file. 
Second problem is that StreamWrapper fails silently, `copy` returns true, no warning is raised, no exception is thrown. How to rely on it, if it doesn't mimick stream behavior?

It uploads ~3GB files without problems though.

Here is the code that I am using, I run it from the CLI:
```
<?php
ini_set('display_errors', 1);
error_reporting(E_ALL);

$s3 = \AWSProvider::getS3();
$s3->registerStreamWrapper();

stream_context_set_default([
	's3' => [
		'seekable' => true
	]
]);

$source = '/tmp/largefile.zip';
$f = fopen($source, 'wb');
fseek($f, 4 * 1000 * 1000 * 1000, SEEK_SET); // 4GB
fwrite($f, 'after GB');
fclose($f);

$result = copy($source, 's3://bucket/largefile.zip');
var_dump($result);
unlink($source);
```

EDIT:
In this particular part of app I've solved my problem by using MultipartUploader, but the issue with StreamWrapper is still somewhat concerning.

```
	$s3 = \AWSProvider::getS3();
		$uploader = new \Aws\S3\MultipartUploader($s3, $source, [
			'bucket' => S3BUCKET,
			'key' => $destination
		]);

		$uploader->upload();
```

**Comment by diehlaws** [comment]
Hi @tomekit, thanks for reaching out to us. Per the [documentation](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-stream-wrapper.html#other-object-functions) for using S3 Stream Wrapper with the AWS SDK for PHP:

> Although `copy` will generally work with the Amazon S3 stream wrapper, some errors might not be properly reported due to the internals of the copy function in PHP. We recommend that you use an instance of [AwsS3ObjectCopier](https://docs.aws.amazon.com/aws-sdk-php/v3/api//class-Aws.S3.ObjectCopier.html) instead.

I tested the provided code (appending a `HeadObject` call for the resulting object in S3), unfortunately I was unable to reproduce the described behavior - The resulting output is attached below. 
If using the S3 Stream Wrapper is required for your use case, using other functions such as `file_put_contents` or `fwrite` to write content to S3 via the Stream Wrapper should return any errors that come up more consistently than using `copy` for the same purpose. Otherwise, using an instance of [AwsS3ObjectCopier](https://docs.aws.amazon.com/aws-sdk-php/v3/api//class-Aws.S3.ObjectCopier.html) as suggested in our documentation would be a better approach for this.

```
$ php StreamWrapper.php                                                     
Copying /tmp/largefile.zip to s3://php-1717/largefile.zip at 01/25/2019 10:58:06 pm UTC                            
bool(true)
HeadObject result for https://php-1717.s3.us-west-2.amazonaws.com/largefile.zip:
ContentLength:
4000000008
LastModified:
2019-01-25T22:58:50+00:00
```

**Comment by cmlara** [comment]
I know this is an old issue but since I hit an issue that might be this I wanted to provide some details for anyone else who may eventually run across this and see this issue as I did.

If you hit this issue (at least in 3.174.3) make sure to verify that you have enough free space in the TEMPORARY directory to make a full duplicate of the file in question (temporary directory may very based on PHP configuration.)

PHP copy() operation function as a stream_open() and then a lot of fwrite()'s which are buffered by the StreamWrapper into a temp file before they can be uploaded.  Exhausting disk space in this scenario for some reason does not appear to trigger any errors writing to the tempfile (or php copy ignores them?) and when copy() calls fclose() the AWS StreamWrapper reads the temp file and uploads it and believes it has uploaded a full file even though the buffer stopped writing some time earlier.
