### ISSUE TITLE
Api\Validator incorrectly erring on assoc. arrays that contain a `0` index

### ISSUE THREAD

**Issue by bwg** [aws/aws-sdk-php#1722]
The heuristic for determining whether an array is assoc `Api\Validator::checkAssociativeArray` fails when an array contains a `0` index, regardless of the other keys.  

This is not correct.  The simple presence of a `0` index does not indicate a non-assoc array.  Both `json_encode` and `Aws\DynamoDb\Marshaler::marshalValue()` consider an array non-assoc only when the keys are 0 based sequential integers.

given the array (actual data I'm working with):
```
$a = [
    0   => 4,
    1   => 6,
    "b" => 2,
    "d" => 1,
    "e" => 29,
]
```

json_encode will encode it as a map
```
json_encode($a);
{"0":4,"1":6,"b":2,"d":1,"e":29}
```

more importantly, so does `DynamoDB\Marshaler`

```
$m = new Aws\DynamoDb\Marshaler();
$m->marshalValue($a);
array(1) {
  'M' =>
  array(5) {
    [0] =>
    array(1) {
      'N' =>
      string(1) "4"
    }
    [1] =>
    array(1) {
      'N' =>
      string(1) "6"
    }
    'b' =>
    array(1) {
      'N' =>
      string(1) "2"
    }
    'd' =>
    array(1) {
      'N' =>
      string(1) "1"
    }
    'e' =>
    array(1) {
      'N' =>
      string(2) "29"
    }
  }
}
```

This manifests itself when validating a DynamoDB request, since DynamoDb has marshaled the data as a Map, but the validator treats it as an array.  Disabling validation in the SDK allows the request to successfully complete.

This issue was previously reported as a PR here: https://github.com/aws/aws-sdk-php/pull/930 but the proposed solution was rejected; for reasons I'm not entirely clear on.  

I'm submitting this as an issue instead of a PR because of the maintainers comments in #930.  As stated there are many ways to check whether an array is acting as a map or list, but I'm not sure what would be an acceptable solution.  Perhaps the way that `DynamoDb\Marshaler` does it?

At the end of the day validation has to be correct, or at the very least consistent. I'm happy to submit this as a PR with some guidance on an acceptable implementation.

Cheers

**Comment by howardlopez** [comment]
The reason the previous PR was rejected is that doing a completely thorough check would require copying the array, or at least all of its keys, which would have a performance impact for every call that checks maps. The check for `$array[0]` is a quick heuristic solution that unfortunately doesn't work for cases like yours. 

One potential option is to add to the heuristic by also checking the last key of the array and comparing it to the array length (minus one). This would make it far less likely that a random input map looks like an indexed array, as it would have to match both the first and last index.

If you'd like to [submit a PR](https://github.com/aws/aws-sdk-php/blob/master/CONTRIBUTING.md), it would be welcome. 

Otherwise, we'd add it to our backlog, but I wouldn't be able to make any promises regarding the timeframe.

**Comment by howardlopez** [comment]
Thanks for the making the revisions - PR has been merged.
