### ISSUE TITLE
Failed opening required 'phar://aws-3.90.3.phar/aws-autoloader.php'

### ISSUE THREAD

**Issue by neoacevedo** [aws/aws-sdk-php#1751]
Hi, I just downloaded the latest version of AWS Phar and I'm getting this error:

> ** Got error 'PHP message: PHP Warning:  Dispatcher::main(phar://aws-3.90.3.phar/aws-autoloader.php): failed to open stream: failed to open stream: &quot;TYPO3\\PharStreamWrapper\\PharStreamWrapper::stream_open&quot;**

But I don't know exactly why. I'm including as `require '/path/to/aws.phar';` in dispatche main method but it fails.

I have disabled OPCache but the error remains. 
I'm using a Bitnami stack.

**Comment by diehlaws** [comment]
Hi @neoacevedo, thanks for reaching out to us. This behavior looks to be caused by the manner in which TYPO3's `PharStreamWrapper` parses the content of our `aws.phar` package. As mentioned in https://github.com/TYPO3/phar-stream-wrapper/issues/21 replacing `require('/path/to/aws.phar');` with `require('phar:///path/to/aws.phar/aws-autoloader.php');` allows the AWS SDK for PHP to be loaded as expected from my end, as such I would suggest using this workaround for the time being. Please don't hesitate to reach back out to us if this workaround does not work as expected on your end.

**Comment by neoacevedo** [comment]
Hi @diehlaws, I'm sorry for my late answer.
In effect, I have contacted to the TYPO3's project owner https://github.com/TYPO3/phar-stream-wrapper/issues/21
I was thinking TYPO3 was part of AWS SDK.
Kind Regards.
