### ISSUE TITLE
InvalidSignatureException - Amazon Rekognition with PHP Client

### ISSUE THREAD

**Issue by hemantjha28** [aws/aws-sdk-php#1776]
Hi,

I am getting the following error whenever I connect to Amazon Rekognition Service through a PHP script deployed on a hosted server (hostgator)

`
AWS HTTP error: Client error: POST https://rekognition.us-east-2.amazonaws.com resulted in a 400 Bad Request response: {"__type":"InvalidSignatureException","message":"Signature expired: 20190430T075732Z is now earlier than 20190430T105409 (truncated...) InvalidSignatureException (client): Signature expired: 20190430T075732Z is now earlier than 20190430T105409Z (20190430T105909Z - 5 min.) - {"__type":"InvalidSignatureException","message":"Signature expired: 20190430T075732Z is now earlier than 20190430T105409Z (20190430T105909Z - 5 min.)"}'
`

I am using the following PHP script.

```php
require 'aws/aws-autoloader.php';
use Aws\Rekognition\RekognitionClient;
//Credentials for access AWS Service code parameter
$credentials = new Aws\Credentials\Credentials('xxxx', 'yyyyy');
//Get Rekognition Access
$rekognitionClient = RekognitionClient::factory(array(
'region' => "us-east-2",
'version' => 'latest',
'correctClockSkew' => true,
'credentials' => $credentials
));
```

I tried adding "'correctClockSkew' => true," as suggested by other solutions but doesnt seem to work for me.

I am not sure whether it is the right way of solving this problem.

Please Help

**Comment by srchase** [comment]
@hemantjha28 

The PHP SDK does not implement correctClockSkew.

Can you verify that the clock on your hosted server is correct?

**Comment by hemantjha28** [comment]
Thanks for the update. I have asked the hosting server to look into and correct the same. If correctClockSkew is not implemented in PHP SDK ,is there any other way to correct the same till the hosting server is able to resolve the same. As this is a live system, any intermediate solution will greatly help. Thanks again.

**Comment by diehlaws** [comment]
Unfortunately the AWS SDK for PHP does not provide a way to fix incorrect system time. Since PHP's `time()` function uses the time provided by the system clock, updating the system clock would be the only viable fix for this without implementing a custom time function that offsets the system clock by a specific amount of time and replacing every instance of `time()` in the SDK's code with your custom time function. 

The [Timecop PHP module](https://github.com/hnw/php-timecop) mentioned in [this thread](https://stackoverflow.com/questions/3923848/change-todays-date-and-time-in-php) may work for you as an intermediary solution until the system clock is corrected. Please keep in mind that this is a third party extension that has not been tested on our end, so there is no guarantee that this will work in conjunction with the AWS SDK for PHP.
