### ISSUE TITLE
"Cannot read credentials from /.aws/credentials" with hardcoded credentials

### ISSUE THREAD

**Issue by gostom** [aws/aws-sdk-php#1782]
### Version of AWS SDK for PHP?
3.93.4

### Version of PHP?
7.1.28

### What issue did you see?
```
$credentials = new Aws\Credentials\Credentials($AccessKey, $SecretKey);
$client = new Aws\CloudFront\CloudFrontClient([
  'profile' => 'default',
  'version' => '2018-06-18',
  'region' => 'us-east-2',
  'credentials' => $credentials
]);

try {
  return $client->listInvalidations([
    'DistributionId' => $distribution_id,
  ]);
} catch (AwsException $e) {
  return false;
}
```
This code causes "Cannot read credentials from /.aws/credentials" - looks like client ignore credentials.

I also tried this:
```
$client = new Aws\CloudFront\CloudFrontClient([
  'profile' => 'default',
  'version' => '2018-06-18',
  'region' => 'us-east-2',
  'credentials' => [
    'key'    => $AccessKey,
    'secret' => $SecretKey,
  ]
]);

**Comment by diehlaws** [comment]
Hi @gostom, thanks for reaching out to us. Your CloudFront client is attempting to locate credentials in the shared credentials file because you're specifying a profile in the client parameters. Removing this parameter from your service client will allow the SDK to use the credentials provided in `$credentials` as expected.
