### ISSUE TITLE
AssumeRoleCredentials not honored when environment KEY variables or ~/.aws/credentials are present

### ISSUE THREAD

**Issue by agentile** [aws/aws-sdk-php#1806]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?
3.94.0

### Version of PHP (`php -v`)?
7.2.17

### What issue did you see?
When running code such as 
```php
$assumeRoleCredentials = new AssumeRoleCredentialProvider([
    'client' => new StsClient([
        'region' => 'us-east-1',
        'version' => 'latest',
    ]),
    'assume_role_params' => [
        'RoleArn' => 'arn::aws...",
        'RoleSessionName' => 'test',
    ],
]);
$provider = CredentialProvider::memoize($assumeRoleCredentials);
$provider()->wait();
```

Even when the EC2 has the proper IAM role attached and configured properly, you can see errors like "Error in retrieving assume role credentials."

The issue is that if there are AWS environment variables set for keys on the EC2 or keys set in `~/.aws/credentials` they seem to override the intent of the code to use the IAM role assumption. 

This is very non-obvious and could not find anything about this issue anywhere, and took a lot of time to figure out. It would seem that if I am explicitly passing assume role credentials, that that is what would be used. Instead it seems to be hijacked by the presence of these other available credentials.

Is there a way, using the AWS PHP SDK, to tell the library to NOT use environment variables or `~/.aws/credentials` for credentials?  Basically, not use `localCredentialProviders` automatically. Thanks.

**Comment by agentile** [comment]
Currently as a workaround I am doing some back and forth clearing out environment variables e.g.

```php
        putenv('HOME=');
        putenv('AWS_ACCESS_KEY_ID=');
        putenv('AWS_SECRET_ACCESS_KEY=');
```

**Comment by diehlaws** [comment]
Hi @agentile, thanks for reaching out to us. Per the [credentials guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials.html) for the AWS SDK for PHP, the default credential provider chain will look for credentials in the following order:

1. Credentials from environment variables
2. Shared credentials file and its profiles
3. Instance profile credentials

If you just want to use the instance profile you've configured for the instance on which your code is running, there is no need to create a new `AssumeRoleCredentialProvider` - instead you can set `$provider` to an `InstanceProfileProvider` then use `$provider` as the 'credentials' value in your service client's configuration options as shown below.

```php
$provider = new InstanceProfileProvider();
$s3 = new S3Client([
    'version' => 'latest',
    'region' => 'us-east-1',
    'credentials' => $provider
]);
```

If, by contrast, you want to use the instance profile to assume a different role before initializing your service client, you can use the `AssumeRoleCredentialProvider` shown in your snippet but you need to specify the instance profile provider as the credentials for the STS client being used in the assume role operation as shown below. Using this approach still requires you to specify the `AssumeRoleCredentialProvider` as the 'credentials' value in the client configuration for the service you want to interact with using the role you've assumed, otherwise the service client will attempt to use the default credential provider chain without taking the newly created `AssumeRoleCredentialProvider` into account.

```php
$profile = new InstanceProfileProvider();
$assumeRoleCredentials = new AssumeRoleCredentialProvider([
    'client' => new StsClient([
        'region' => 'us-east-1',
        'version' => 'latest',
    ]),
    'assume_role_params' => [
        'RoleArn' => 'arn::aws...",
        'RoleSessionName' => 'test',
    ],
]);
$provider = CredentialProvider::memoize($assumeRoleCredentials);

$s3 = new S3Client([
    'version' => 'latest',
    'region' => 'us-east-1',
    'credentials' => $provider
]);
```

**Comment by agentile** [comment]
I am actually doing the later, here is my more fully fleshed out example
```php
        $assumeRoleCredentials = new AssumeRoleCredentialProvider([
            'client' => new StsClient([
                'region' => Config::get('aws_region'),
                'version' => 'latest',
            ]),
            'assume_role_params' => [
                'RoleArn' => Config::get('aws_role_arn'),
                'RoleSessionName' => gethostname(),
            ],
        ]);
        // To avoid unnecessarily fetching STS credentials on every API operation,
        // the memoize function handles automatically refreshing the credentials when they expire
        $provider = CredentialProvider::memoize($assumeRoleCredentials);
        $sm = new SecretsManagerClient([
            'region' => Config::get('aws_region'),
            'version' => 'latest',
            'credentials' => $provider,
        ]);
```

So I am passing the provider as credentials, but it still tries to use local credentials over the ones provided.

In your later example you have 
```php
$profile = new InstanceProfileProvider();
```
But I don't see that variable be used anywhere.

I am using the later example as it seems preferable to leverage `memoize`

I am basically doing what is described here https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_provider.html

**Comment by diehlaws** [comment]
My apologies @agentile, the example I provided for the second scenario is missing precisely what I was suggesting - `$profile` should have been used as the credentials value for the STS client config in the `AssumeRoleCredentialProvider`:

```php
$profile = new InstanceProfileProvider();
$assumeRoleCredentials = new AssumeRoleCredentialProvider([
    'client' => new StsClient([
        'region' => 'us-east-1',
        'version' => 'latest',
        'credentials' => $profile
    ]),
    'assume_role_params' => [
        'RoleArn' => 'arn::aws...",
        'RoleSessionName' => 'test',
    ],
]);
```
