### ISSUE TITLE
AWS Form Processing

### ISSUE THREAD

**Issue by firpo123** [aws/aws-sdk-php#1842]
When I use a form, it is not passing parameters via $_POST when running on AWS. Works on other existing platform. AWS throws `Fatal error: Uncaught exception 'RuntimeException' with message 'Instances of Aws\S3\S3Client cannot be serialized' in /var/www/transitionsquad/html/vendor/aws/aws-sdk-php/src/AwsClient.php:254 Stack trace: #0 [internal function]: Aws\AwsClient->__sleep() #1 {main} thrown in /var/www/transitionsquad/html/vendor/aws/aws-sdk-php/src/AwsClient.php on line 254`

Through some debugging, it looks like when we don't try to connect to S3, form processing is working fine and $_POST variables are being sent through ok with no runtime exceptions being thrown by AWS. So something to do with accessing S3 using SDK is causing the problem.

Also found that this seems to work:
```php
// create s3 client
$s3 = new Aws\S3\S3Client([
	'region' => $config['s3']['region'],
	'version' => 'latest',
	'credentials' => [
		'key'    => $config['s3']['key'],
		'secret' => $config['s3']['secret']
	],
]);	
```
but this causes the problem:
```php
// create s3 client
$_SESSION['s3'] = new Aws\S3\S3Client([
	'region' => $config['s3']['region'],
	'version' => 'latest',
	'credentials' => [
		'key'    => $config['s3']['key'],
		'secret' => $config['s3']['secret']
	],
]);
```

One of AWS support agents said we should create a global s3 client for better performance as we shouldn't create a new client every page that is run as it takes a long time to create. In PHP, session variable makes the most sense, or doesn't it?

**Comment by diehlaws** [comment]
Hi @firpo123, thanks for reaching out to us. As the error message suggests, service clients in the AWS SDK for PHP cannot be serialized. Unfortunately the S3 client is not safe to be serialized into `$_SESSION`, as a result it is best practice to initialize a new S3 client on each page load despite the additional resources required by this method of client instantiation.

Constructing an S3 client should not prevent `$_POST` variables from sending - does this occur when you initialize the service client as shown in the first code snippet you've provided? If so, can you provide a more complete sample showing how `$_POST` is being populated?

**Comment by firpo123** [comment]
Hello Alex,



Thanks for your response.



What does “cannot be serialized” even mean? This is not explained anywhere
and even your own support engineers didn’t understand what it meant or
could find any reference to it in the documentation.



When I create an s3 client and assign it to a local (eg $s3) or $GLOBAL(eg:
$GLOBALS[‘s3’]) variable, I don’t seem to have any problems with $_POST
variables flowing from source page to target page. However if I set it up
as a $_SESSION variable ($_SESSION[‘s3’]) then I get the error, aws throws
the exception and $_POST variables do not flow from source page to target
page.



If I set up as local for each page, there is a big and noticeable
performance hit on the page. However as a $GLOBALS or $_SESSION variable,
that hit happens once the first time a page is called and then it is fast
afterwards as we reference the original variable.



I presume it is unsafe because it can then be manipulated and someone will
have access to my entire S3 bucket. However, is it the same S3 client that
gets created for each page.



It would be very helpful to get you on the phone to answer my questions
rather than little bits and pieces over several emails. Can you please call
me at (416) 249-4049 x303? If you get my voicemail, then hit 7 and it will
go to my cell.



Viraf Baliwalla



*From:* Alex Diehl [mailto:notifications@github.com]
*Sent:* Tuesday, July 9, 2019 1:52 PM
*To:* aws/aws-sdk-php <aws-sdk-php@noreply.github.com>
*Cc:* firpo123 <viraf@transitionsquad.com>; Mention <
mention@noreply.github.com>
*Subject:* Re: [aws/aws-sdk-php] AWS Form Processing (#1842)



Hi @firpo123 <https://github.com/firpo123>, thanks for reaching out to us.
As the error message suggests, service clients in the AWS SDK for PHP
cannot be serialized. Unfortunately the S3 client is not safe to be
serialized into $_SESSION, as a result it is best practice to initialize a
new S3 client on each page load despite the additional resources required
by this method of client instantiation.

Constructing an S3 client should not prevent $_POST variables from sending
- does this occur when you initialize the service client as shown in the
first code snippet you've provided? If so, can you provide a more complete
sample showing how $_POST is being populated?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/aws/aws-sdk-php/issues/1842?email_source=notifications&email_token=AMRMRRKG6OX6CNCD5DEF3YDP6TF4PA5CNFSM4H6UI5D2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZRAT4A#issuecomment-509741552>,
or mute the thread

**Comment by diehlaws** [comment]
Thanks for the update @firpo123! [Object serialization](https://www.php.net/manual/en/language.oop5.serialization.php) in PHP is the conversion of a given value (in this case the combined values of the S3Client object) into a byte-stream representation of said value in a way that can be later retrieved by unserializing the serialized object; this concept is not unique to AWS nor to the AWS SDK for PHP. Within the context of this issue, the S3 client is saved into the `$_SESSION` superglobal, then once the page's script finishes executing and PHP shuts down, the contents of the `$_SESSION` superglobal are automatically retrieved, serialized, and sent for storage using the session save handler. Unfortunately this doesn't work as expected for the S3 client due to the way in which service clients are constructed in the AWS SDK for PHP. Saving the service client to `$GLOBALS` works because, unlike `$_SESSION`, `$GLOBALS` is not automatically serialized at the time PHP shuts down when it finishes executing the script. 

If initializing a new service client for each page load does not fit your use case, you may find it beneficial to keep an active S3 client running on your web server's backend that uploads objects to S3 as the corresponding files are uploaded to your web server by your website's users. That being said, this is a design decision to which there are multiple valid approaches depending on what best fits your use case.

As far as the safety of serialization and deserialization is concerned, I suggest reading through these posts ([1](https://paragonie.com/blog/2016/04/securely-implementing-de-serialization-in-php), [2](https://www.netsparker.com/blog/web-security/untrusted-data-unserialize-php/), [3](https://stackoverflow.com/questions/29798347/how-secure-is-php-object-serialization-and-is-it-safe-to-pass-across-pages-usi)) for a deeper understanding of this topic as they provide good information on the subject matter.

Unfortunately phone support falls outside of the scope of support for the AWS SDKs. Issues on GitHub repositories for the AWS SDKs are typically intended for reporting bugs and raising feature requests specific to the SDK in question, however we are typically happy to provide guidance in using the SDKs as time permits. If you require assistance writing a PHP application that uses the AWS SDK for PHP you may find it beneficial to search the [AWS Partner Network](https://aws.amazon.com/partners/find-a-partner/) for a partner that specializes in PHP development as they would be in more direct and consistent contact with you for this project compared to posting on a public forum and waiting for a response.

**Comment by firpo123** [comment]
Hi Alex,



Thank you, this is very interesting. How would one implement “… keep an
active S3 client running on your web server's backend…” this in PHP with
Apache? I presume this would make the s3 client a single global variable
somehow that would be active for all users. It would be the same client
object that would be used for uploading, deleting and other file functions,
correct?



Viraf



*From:* Alex Diehl [mailto:notifications@github.com]
*Sent:* Tuesday, July 9, 2019 7:20 PM
*To:* aws/aws-sdk-php <aws-sdk-php@noreply.github.com>
*Cc:* firpo123 <viraf@transitionsquad.com>; Mention <
mention@noreply.github.com>
*Subject:* Re: [aws/aws-sdk-php] AWS Form Processing (#1842)



Thanks for the update @firpo123 <https://github.com/firpo123>! Object
serialization
<https://www.php.net/manual/en/language.oop5.serialization.php> in PHP is
the conversion of a given value (in this case the combined values of the
S3Client object) into a byte-stream representation of said value in a way
that can be later retrieved by unserializing the serialized object; this
concept is not unique to AWS nor to the AWS SDK for PHP. Within the context
of this issue, the S3 client is saved into the $_SESSION superglobal, then
once the page's script finishes executing and PHP shuts down, the contents
of the $_SESSION superglobal are automatically retrieved, serialized, and
sent for storage using the session save handler. Unfortunately this doesn't
work as expected for the S3 client due to the way in which service clients
are constructed in the AWS SDK for PHP. Saving the service client to
$GLOBALS works because, unlike $_SESSION, $GLOBALS is not automatically
serialized at the time PHP shuts down when it finishes executing the script.

If initializing a new service client for each page load does not fit your
use case, you may find it beneficial to keep an active S3 client running on
your web server's backend that uploads objects to S3 as the corresponding
files are uploaded to your web server by your website's users. That being
said, this is a design decision to which there are multiple valid
approaches depending on what best fits your use case.

As far as the safety of serialization and deserialization is concerned, I
suggest reading through these posts (1
<https://paragonie.com/blog/2016/04/securely-implementing-de-serialization-in-php>,
2
<https://www.netsparker.com/blog/web-security/untrusted-data-unserialize-php/>,
3
<https://stackoverflow.com/questions/29798347/how-secure-is-php-object-serialization-and-is-it-safe-to-pass-across-pages-usi>)
for a deeper understanding of this topic as they provide good information
on the subject matter.

Unfortunately phone support falls outside of the scope of support for the
AWS SDKs. Issues on GitHub repositories for the AWS SDKs are typically
intended for reporting bugs and raising feature requests specific to the
SDK in question, however we are typically happy to provide guidance in
using the SDKs as time permits. If you require assistance writing a PHP
application that uses the AWS SDK for PHP you may find it beneficial to
search the AWS Partner Network
<https://aws.amazon.com/partners/find-a-partner/> for a partner that
specializes in PHP development as they would be in more direct and
consistent contact with you for this project compared to posting on a
public forum and waiting for a response.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/aws/aws-sdk-php/issues/1842?email_source=notifications&email_token=AMRMRRODUJ6T2RB6LIOHTCTP6UMLNA5CNFSM4H6UI5D2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZRZ7AQ#issuecomment-509845378>,
or mute the thread

**Comment by diehlaws** [comment]
I'm not sure if this is something that could be accomplished using Apache, I was thinking more along the lines of a standalone PHP-CLI process running on the server that maintains an active S3 Client, takes files uploaded by end users, and uploads them to S3 independently of the web service. This could be approached several ways, including the examples below:

1. The standalone process could listen for messages from Apache that prompt the process to upload new files to a predefined S3 Bucket and prefix (or take the prefix from the message delivered from Apache to the standalone process). This would likely require finding or writing a module that allows Apache to send messages that your standalone process can interpret and use in conjunction with a PUT Object call to S3
2. When Apache receives the file from the end user, it could generate a metadata file alongside the file that was uploaded with information such as where the file should go in S3 that the standalone process parses to add the appropriate parameters to the PUT Object call. This could be made persistent by having the process create an S3 client, then loop on a set time interval to check the destination folder for user-uploaded files and their metadata counterparts to upload to S3 then either delete the metadata file and persist the user-uploaded file (in case an error occurs when uploading the file) or deletes both the metadata and user-uploaded file once the PUT Object call to S3 completes successfully


A simpler approach to uploading files to S3 directly from the browser that would avoid the use of the PHP SDK's S3 Client altogether would be to perform browser-based uploads using HTTP POST. The process for this is detailed in S3's [API Reference](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-UsingHTTPPOST.html) documentation with a live example available [here](https://s3.amazonaws.com/doc/s3-example-code/post/post_sample.html); I was also able to find a tutorial for this that includes the use of PHP [here](https://www.sanwebe.com/2015/09/direct-upload-to-amazon-aws-s3-using-php-html).

**Comment by firpo123** [comment]
Thanks Alex,



I will review these options. I think the third option which would work well
also is to instantiate a $GLOBALS[‘S3’] client variable when a user first
signs in and then use that variable throughout the user’s session. Would
that work?



Regards,



Viraf Baliwalla

Transition Squad Inc.

80 Kincort Street

Toronto, ON M6M 5G1

(416) 249-4049 x303



Please check out our sister websites:

www.AutomallNetwork.com <http://www.automallnetwork.com/>

www.MyCarIsWorthLess.com <http://www.mycarisworthless.com/>







*From:* Alex Diehl [mailto:notifications@github.com]
*Sent:* Thursday, July 11, 2019 5:38 PM
*To:* aws/aws-sdk-php <aws-sdk-php@noreply.github.com>
*Cc:* firpo123 <viraf@transitionsquad.com>; Mention <
mention@noreply.github.com>
*Subject:* Re: [aws/aws-sdk-php] AWS Form Processing (#1842)



I'm not sure if this is something that could be accomplished using Apache,
I was thinking more along the lines of a standalone PHP-CLI process running
on the server that maintains an active S3 Client, takes files uploaded by
end users, and uploads them to S3 independently of the web service. This
could be approached several ways, including the examples below:

   1. The standalone process could listen for messages from Apache that
   prompt the process to upload new files to a predefined S3 Bucket and prefix
   (or take the prefix from the message delivered from Apache to the
   standalone process). This would likely require finding or writing a module
   that allows Apache to send messages that your standalone process can
   interpret and use in conjunction with a PUT Object call to S3
   2. When Apache receives the file from the end user, it could generate a
   metadata file alongside the file that was uploaded with information such as
   where the file should go in S3 that the standalone process parses to add
   the appropriate parameters to the PUT Object call. This could be made
   persistent by having the process create an S3 client, then loop on a set
   time interval to check the destination folder for user-uploaded files and
   their metadata counterparts to upload to S3 then either delete the metadata
   file and persist the user-uploaded file (in case an error occurs when
   uploading the file) or deletes both the metadata and user-uploaded file
   once the PUT Object call to S3 completes successfully

A simpler approach to uploading files to S3 directly from the browser that
would avoid the use of the PHP SDK's S3 Client altogether would be to
perform browser-based uploads using HTTP POST. The process for this is
detailed in S3's API Reference
<https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-UsingHTTPPOST.html>
documentation with a live example available here
<https://s3.amazonaws.com/doc/s3-example-code/post/post_sample.html>; I was
also able to find a tutorial for this that includes the use of PHP here
<https://www.sanwebe.com/2015/09/direct-upload-to-amazon-aws-s3-using-php-html>
.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/aws/aws-sdk-php/issues/1842?email_source=notifications&email_token=AMRMRRJAXGRJGOY6HTKWW7TP66R43A5CNFSM4H6UI5D2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZYBYWI#issuecomment-510663769>,
or mute the thread

**Comment by diehlaws** [comment]
@firpo123 in my relatively rudimentary tests I found that storing the S3 client as a `$GLOBAL['S3']` client variable did not result in the S3 client being stored across page loads within the same session, however depending on how your application is written you may find that it does work as expected on your end.

Can you go into more detail on how you're measuring the impact in performance when looking at the difference between instantiating the S3 client on each page load and storing the S3 client in `$GLOBAL`? I would expect the primary source of a performance impact would be issuing the PUT Object call rather than the instantiation of the S3 client itself. Do you see a significant performance impact if the S3 client is instantiated on each page load but it doesn't perform any API calls?

If storing the S3 client in `$GLOBAL` does not work as expected, and you don't see a significant impact in performance when the S3 client is instantiated but does not perform any API calls, another viable option could be using the S3 client to create a [presigned POST request](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-presigned-post.html) (which does not result in any API calls to S3), then issue the HTTP POST request independently of the SDK.
