### ISSUE TITLE
CommandPool doesn't execute any closure

### ISSUE THREAD

**Issue by shihabislambs** [aws/aws-sdk-php#1852]
### Issue:
I am trying to use SES to send email in Batch using CommandPool. **_My emails are getting delivered but none of the closures are getting executed._** I want to do some work for every successful result or let the user know what is wrong if it fails.

Here is the code I am using:
```
$result = [];
$batchRequest = [];
foreach($messages as $message) {
  $batchRequest[] = $this->sesClient()->getCommand('SendRawEmail', array(
      'RawMessage' => array(
              'Data' => $message->toString(),
            ),
    ));
}
$pool = new CommandPool($this->sesClient(), $batchRequest, [
  'fulfilled' => function (ResultInterface $result, $iterKey, PromiseInterface $aggregatePromise) {
      MailLog::info("Completed {$iterKey}: {$result}\n");
      $result[] = [
              'runtime_message_id' => $result['MessageId'],
              'status' => self::DELIVERY_STATUS_SENT,
            ];
    },
  'rejected' => function (AwsException $reason, $iterKey, PromiseInterface $aggregatePromise) {
      MailLog::warning("Failed {$iterKey}: {$reason}\n");
      $result[] = [
              'status' => self::DELIVERY_STATUS_FAILED,
              'error' => $reason,
            ];
    }
]);

$promise = $pool->promise();
$promise->wait();

MailLog::info('Batch sent!');
```

> Also, 'Batch sent!' never gets logged.

**Comment by diehlaws** [comment]
Hi @shihabislambs, thanks for reaching out to us about this. Looking over your code snippet, it looks like your `$result` variables aren't scoped properly within your closures - in order to append MessageId+status / status+error to the `$result` variable you'll want to include a `use` statement in the function declarations to use a reference to this `$result` variable, and change the variable name for your `ResultInterface` from `$result` to something else so it doesn't override your `$result` array further down. I've included an example of these changes below for your review:

```php
    'fulfilled' => function (ResultInterface $response, $iterKey, PromiseInterface $aggregatePromise) use (&$result) {
        echo "Completed {$iterKey}: {$response["MessageId"]}\n";
        $result[] = [
            'runtime_message_id' => $response['MessageId'],
            'status' => "Sent",
        ];
    },
```

Unfortunately I'm not familiar with the `MailLog` class/method you're using, so I've replaced it with `echo` in my tests. I was able to see my `echo "Batch sent!\n"` statement get executed successfully even before making changes to the closure function declarations, and after implementing the change referenced above I'm able to see my closures get executed successfully with `$result[]` getting populated as expected.

If you continue to see the same behavior after implementing this change, it's possible that the version of the SDK you're using may have some bugs with `CommandPool` that have been fixed in newer versions - version 3.19 of the AWS SDK for PHP is nearly 3 years old and 88 minor versions behind latest, and there have been a lot of changes between it and the latest version (3.107.8). As such, I recommend updating the AWS SDK for PHP to a newer minor version even if the above change in your closure fixes this behavior.

**Comment by shihabislambs** [comment]
@diehlaws Thank you for your response. `MailLog` actually writes log in a file named `mail.log`, nothing else. Honestly, all I expected from my code is to write the response from **CommandPool (fulfilled, rejected)** in the `mail.log` file just to check if everything is working properly. I didn't actually care about the `$result[]`. Although, my SES sent my mail but I didn't get any log.

Anyways, I am gonna upgrade to the new SDK and check if everything works.
Will let you know the result.

**Comment by shihabislambs** [comment]
**!! UPDATE !!**

Upgrading to new SDK worked. Thanks @diehlaws
