### ISSUE TITLE
RetryMiddleware doesn't handle Pinpoint THROTTLED

### ISSUE THREAD

**Issue by gitotoro** [aws/aws-sdk-php#1862]
### Version of AWS SDK for PHP?
3.108.2

### Version of PHP (`php -v`)?
PHP 7.2.21 (cli) (built: Jul 30 2019 14:46:08) ( NTS )

### What issue did you see?
RetryMiddleware did not retry when PinpointClient->SendMessages commands are THROTTLED.

### Steps to reproduce
```
$this->pinpointClient = new PinpointClient([ ... ]);

// 5 messages x 2000 commands (*message type is Email)
$commands[] = $this->pinpointClient->getCommand('SendMessages', $message);

foreach (CommandPool::batch($this->pinpointClient, $commands, ['preserve_iterator_keys' => true] as $key => $result) {
     // 'DeliveryStatus' = THROTTLED
     // 'StatusCode' = 403
}
```

### Additional context
- RetryMiddleware::isRetryable ignore 403 and THROTTLED status.

- PinpointClient->SendMessages returns partial THROTTLED results, because 1command has many messages(addresses). consequently, we need rebuild command's array when resending THROTTLED messages(addresses) in my program. It takes time and effort.

- [How is retry scheme handled in the AWS SDK for PHP?](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/faq.html#how-is-retry-scheme-handled-in-the-sdk-php)

> The AWS SDK for PHP also integrates exponential delay with a backoff and jitter algorithm in the retry scheme. Furthermore, default retry behavior is configured as 3 for all services except Amazon DynamoDB, which is 10.

I'm sorry my English isn't good. I hope that my English gets through to you.

**Comment by diehlaws** [comment]
Hi @gitotoro, thanks for reaching out to us about this. The only HTTP 403 response Pinpoint returns in response to a `SendMessages` API call is a `ForbiddenException` which is related to IAM permissions of the entity sending the API call. If you're seeing 'THROTTLED' in the `DeliveryStatus` property of the `EndpointMessageResult` for a given message, that means that instead of the SDK sending requests faster than the service will handle/accept, you're exceeding either the daily sending quota or the maximum sending rate for your Pinpoint project. The SDKs are not aware of these sending limits for a given Pinpoint project, and cannot differentiate between a `DeliveryStatus` of 'THROTTLED' caused by reaching your project's daily quota or by exceeding your project's sending limit, so it is by design that messages with this status are not automatically retried by the SDK. As a result, you'll need to handle rate limiting and retries for message delivery within your application's code according to your Pinpoint project's maximum send rate and daily sending limit in the same way as is described for SES in [this article](https://aws.amazon.com/blogs/messaging-and-targeting/how-to-handle-a-throttling-maximum-sending-rate-exceeded-error/).

**Comment by gitotoro** [comment]
Thanks for the reply. I'm confused.

> The only HTTP 403 response Pinpoint returns in response to a SendMessages API call is a ForbiddenException which is related to IAM permissions of the entity sending the API call.

in my code,
$result['MessageResponse']['Result'][ address ]['StatusCode'] is 403.
$result['MessageResponse']['Result'][ address ]['DeliveryStatus'] is 'THROTTLED'.

if you talk about $result['MessageResponse']['@metadata']['statusCode'] then statusCode is 200.

> As a result, you'll need to handle rate limiting and retries for message delivery within your application's code according to your Pinpoint project's maximum send rate and daily sending limit in the same way as is described for SES in this article.

I will try to use RateLimiter.
Please let me know if you know the sample that uses CommandPool::batch for sending.

**Comment by SamRemis** [comment]
Hi @gitotoro,
Sorry for the delay in response.  Are you still confused by the response above?  If I'm reading correctly, the 200 code in $result['@metadata']['statusCode'] appears to be saying that the message was successfully processed by Pinpoint but the 'Throttled' came about as a failed delivery.  Since they reported a success back too the SDK, it is not retried.  

If you think this should be retried, I can discuss it with the team and if I get the go ahead I can implement a custom retry strategy on pinpoint.  That said, I'm not sure retrying a throttled request will accomplish much since some of the throttling is done as batch throttling.  I think it may be a more frustrating user experience to have the retries throttle your requests further.  

Let me know if you still are experiencing issues
-Sam

**Comment by gitotoro** [comment]
I'm sorry I left the ticket.
I have already written a program that rebuilds and resends commands for partial THROTTLED messages.
But I don't think it's a good idea because it's much more lines of code and more complex than normal command execution.

Since it is sent by batch processing, the execution time does not matter much. Most importantly, all messages are sent in some way.
If possible, it would be nice to have an option in the SDK to limit the rate of the SendMessage command or try a retry with a delay. However, it can be difficult if it doesn't fit the Pinpoint or SDK design.

Is this possible?

**Comment by SamRemis** [comment]
@gitotoro I think it would be possible; there may also be a way to implement a custom retry strategy that always waits a second before re-sending the request.  Since the throttling is done per second, this could work too depending on the timing of the requests being sent.  I will discuss it with the team and get back to you
