### ISSUE TITLE
Could not upload to S3 with ECS Fargate

### ISSUE THREAD

**Issue by zeroiszero** [aws/aws-sdk-php#1867]
Hi, I am running WordPress with ECS Fargate and `TaskRoleArn` defined in [Task Definition](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#task_role_arn) 

### Version of AWS SDK for PHP?
```
aws/aws-sdk-php": "~3.18"
```

### Version of PHP (`php -v`)?
```
PHP 7.3.6 (cli) (built: Jun 12 2019 20:40:46) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies
```

### What issue did you see?

`Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 7: (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/html/wp-content/plugins/s3-uploads/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185 Stack trace: #0 /var/www/html/wp-content/plugins/s3-uploads/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 /var/www/html/wp-content/plugins/s3-uploads/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 /var/www/html/wp-content/plugins/s3-uploads/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(181): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 /var/www/html/wp-content/plugins/s3-u in /var/www/html/wp-content/plugins/s3-uploads/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 185
`

### Steps to reproduce
Run S3 `putObject` as in this [example](https://docs.aws.amazon.com/code-samples/latest/catalog/php-s3-s3-uploading-object.php.html).

Credentials not provided as I assume the SDK will retrieve from the IAM role.

Also tried the task role attached with the policy `AmazonS3FullAccess`. Still the same error.

**Comment by diehlaws** [comment]
Hi @zeroiszero, thanks for reaching out to us. cURL Error 7 is caused by a failure to connect to the target host, which suggests there is something blocking or dropping the connection from your Fargate container to S3. Are you able to reach the [S3 endpoint](https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region) for the region in which your bucket resides using your container without using the AWS SDK for PHP? E.g. using [`curl`](https://curl.haxx.se/docs/httpscripting.html#GET) or [`nc`](https://www.digitalocean.com/community/tutorials/how-to-use-netcat-to-establish-and-test-tcp-and-udp-connections-on-a-vps) from the shell, or using [`fsockopen()`](https://www.php.net/manual/en/function.fsockopen.php) or a [`GuzzleHttp`](http://docs.guzzlephp.org/en/stable/quickstart.html) client within PHP.

As a side note, I see you're using version 3.18 of the AWS SDK for PHP. While this shouldn't affect your ability to connect to S3, this version was released in April of 2016 and is 90 minor versions behind the latest release. I strongly suggest updating the SDK to a newer version as there have been quite a few bug fixes and improvements implemented between these two versions that should result in an overall better experience using the SDK.

**Comment by zeroiszero** [comment]
Hi, @diehlaws

**Comment by zeroiszero** [comment]
Solved.

It was caused by php-fpm configuration that deleted the environment variables when docker started php-fpm processes. 

`AWS_CONTAINER_CREDENTIALS_RELATIVE_URI ` environment variable is required to retrieve credentials from Task Role as mentioned [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html).

To fix this, set `clear_env` to ` no` in php-fpm configurations:
```
; Clear environment in FPM workers
; Prevents arbitrary environment variables from reaching FPM worker processes
; by clearing the environment in workers before env vars specified in this
; pool configuration are added.
; Setting to "no" will make all environment variables available to PHP code
; via getenv(), $_ENV and $_SERVER.
; Default Value: yes
clear_env = no
```

**Comment by at-bachhuynh** [comment]
hi @zeroiszero , I try like you did, but still error
https://github.com/aws/aws-sdk-php-laravel/issues/176

**Comment by Steven-Wright** [comment]
> To fix this, set `clear_env` to ` no` in php-fpm configurations:

I am so glad I found this post, I was really beginning to lose hope.

I'm not sure if it matters much, but rather than preventing FPM from clearing environment variables you could pass `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` specifically. 

I added the line to /etc/php-fpm.d/www.conf:
```
env[AWS_CONTAINER_CREDENTIALS_RELATIVE_URI] = $AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
```

Below the section:
```
; Pass environment variables like LD_LIBRARY_PATH. All $VARIABLEs are taken from
; the current environment.
; Default Value: clean env
;env[HOSTNAME] = $HOSTNAME
;env[PATH] = /usr/local/bin:/usr/bin:/bin
;env[TMP] = /tmp
;env[TMPDIR] = /tmp
;env[TEMP] = /tmp
```
