### ISSUE TITLE
AccessDenied (client): Cannot call GetSessionToken with session credentials

### ISSUE THREAD

**Issue by samueleastdev** [aws/aws-sdk-php#1876]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?
3.112.10

### Version of PHP (`php -v`)?
PHP 7.1.28 

### What issue did you see?
A bit of a weird one not sure if it is something I am doing wrong or missing. I am connecting to AWS by getting temporary detail using StsClient here is my full code.

~~~
require APPPATH . 'libraries/vendor/autoload.php';
use Aws\Credentials\Credentials;
use Aws\S3\S3Client;
use Aws\Sts\StsClient;
use Aws\Exception\AwsException;

$mfa    = $_GET['mfa'];
$arn    = 'arn:aws:iam::0000000000:mfa/app';
$expire = 3600;

try{

	$stsClient = new StsClient([
        'version'     => 'latest',
        'region'      => 'us-east-1'
    ]);

	$credentials = $stsClient->getSessionToken([
	    'DurationSeconds' => $expire,
	    'SerialNumber'    => $arn,
	    'TokenCode'       => $mfa
	]);

	echo 'done';

} catch (AwsException $e) {

   echo $e->getMessage();

}
~~~

This is working fine on my local server but as soon as I upload my script to and AWS Lightsail LAMP PHP 7 stack it does work I get the following error.

~~~
AccessDenied (client): Cannot call GetSessionToken with session credentials
~~~

I have tried everything I can think of resynced mfa device etc and everytime it works locally but not on the server! I am out of ideas can any suggest something that I could possibly try?

Thanks

**Comment by diehlaws** [comment]
Hi @samueleastdev, thanks for reaching out to us. As the error message suggests, session credentials cannot be used to initialize a new STS session via a `getSessionToken` call. Credentials that include a `Token` value (e.g. STS temporary security credentials, assumed IAM roles, instance profile credentials) are considered session credentials and thus cannot be used to obtain a new session token via a `getSessionToken` call.

What credentials are being used on your Lightsail instance to issue the `getSessionToken` call? You can check by issuing a `getCallerIdentity` call and printing the response before issuing your `getSessionToken` call as shown below. If you have an IAM role associated with your Lightsail instance that is being retrieved by the SDK when the STS client is initialized, this is likely what is causing the error you're seeing. Is there any particular reason you cannot use the credentials that the SDK is using to initialize the STS client for whatever calls are being issued after `getSessionToken`? 

```php
    $stsClient = new StsClient([
        'version'     => 'latest',
        'region'      => 'us-east-1'
    ]);

    $creds = $stsClient->getCallerIdentity();

    echo "Initial creds:\n{$creds}\n";

    $credentials = $stsClient->getSessionToken([
        'DurationSeconds' => $expire,
        'SerialNumber'    => $arn,
        'TokenCode'       => $mfa
    ]);
```

If your use case requires using a temporary STS session for API calls to other services you'll need to use the AWS Access Key ID and Secret Access Key corresponding to an IAM user to issue your `getSessionToken` call. This can be done one of three ways:

1. Populate the AWS shared credentials file (~/.aws/config) in your Lightsail instance with credentials for an IAM user
2. Set the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables in your Lightsail instance to credentials corresponding to an IAM user
3. Hard-code the IAM user's credentials into your PHP file (NOT RECOMMENDED!)

Options 1 and 2 won't require any changes to the provided code snippet since the [default credential provider chain](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials.html) for the AWS SDK for PHP will attempt to retrieve these credential sets before retrieving credentials from the instance metadata. However, this means any other code on the instance that uses one of the AWS SDKs will retrieve these credentials instead of picking up the instance profile by default.

Option 3 will require you to change the STS client initialization to include the AWS Access Key ID and Secret Access Key values as shown [here](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_hardcoded.html), but will not affect any other code running on the instance since these credentials won't be added to the default credential chain for the instance. Please keep in mind that we strongly advise against providing credentials to a service client in this manner since it is surprisingly easy to forget to remove credentials from code before committing it to a repository. This can result in your AWS credentials being exposed to more people than you intend, which often results in a compromised AWS account. As such, this method should be used as a last resort or when testing code locally that will never be accessible to others.
