### ISSUE TITLE
Sending SMS (Text) through SnsClient->publish truncates 'PhoneNumber' .

### ISSUE THREAD

**Issue by Mzril** [aws/aws-sdk-php#1885]
### Version of AWS SDK for PHP?

3.112.1

### Version of PHP (`php -v`)?

7.3.7

### What issue did you see?

When sending a correctly formatted E164 phone number that is a US number with some accidental extra digits, (Ex: +11111111111 + 222), the text is being sent correctly to the right phone number, as if the 222 has been truncated off.

### Steps to reproduce

Initialize an SnsClient, then send a message to a valid US phone number with some extra digits attached (Ex: +11111111111 + 222). Somehow the verification is being sent to the correct phone number. The extra digits seem to be being cut off.

```
class SendPhoneVerification
{
    public function __construct(SnsClient $client)
    {
        $this->client = $client;
    }

    public function execute(string $message, string $phoneNumber): void
    {
        if (preg_match("/^\+?[1-9]\d{1,14}$/", $phoneNumber) === 0) {
            // throw error here if not E164
        }

        $response = $this->client->publish([
            'PhoneNumber' => $phoneNumber, //valid E164 number
            'MessageStructure' => 'string',
            'Message' => $message
        ]);
        
        return $response;
    }
}
```

### Additional context

I'm in the midst of creating a Laravel app, and we're enabling phone sign ups with a verification code. But it looks like incorrect phone numbers that were sent up due to accidental button presses are sending correct verification codes which allows for people to sign up with not-so incorrect phone numbers.

It also appears that sending the text through the SNS console on AWS Management console truncates the phone number with this exact behavior. Not sure where I can ask about the issue if that is the case.

**Comment by diehlaws** [comment]
Hi @Mzril, thanks for reaching out to us. Looking at the debug output for a `publish()` call to a phone number with extra digits I can see that the SDK is sending the full number with the extra digits. This truncation appears to be a behavior of the service itself, which is consistent with the SNS console exhibiting the same behavior.

Since this is a behavior of the service and not the AWS SDK for PHP, the best avenues for clarification/support on thi behavior are reaching out to our Premium Support team by opening a [new technical support case](https://console.aws.amazon.com/support/cases#/create) under the SNS service, or creating a post in the [AWS Forums for SNS](https://forums.aws.amazon.com/forum.jspa?forumID=72). In the meantime, I suggest performing your own input validation on this field before passing its value to the SDK's `publish()` call parameters.
