### ISSUE TITLE
Unable to curl an S3 file in ECS fargate

### ISSUE THREAD

**Issue by liaogz82** [aws/aws-sdk-php#1886]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?
3.112.16

### Version of PHP (`php -v`)?
```
PHP 7.3.9 (cli) (built: Sep 12 2019 10:15:36) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.9, Copyright (c) 1999-2018, by Zend Technologies
```

### What issue did you see?
```
The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">GuzzleHttp\Exception\ConnectException</em>: cURL error 7:  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in <em class="placeholder">GuzzleHttp\Handler\CurlFactory::createRejection()</em> (line <em class="placeholder">185</em> of <em class="placeholder">/var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php</em>). <pre class="backtrace">GuzzleHttp\Handler\CurlFactory::finishError(Object, Object, Object) (Line: 102)
```

### Steps to reproduce
Run a Drupal website with S3FS module installed, point it to the s3fs bucket. Create a fargate setup with given task role with Full S3 access.

### Additional context
I have one ECS running EC2 instance and another one run fargate cluster. Both uses the same image in ECR, with the same environment variables. One runs fine but the other throws up an error.

The link is stated here http://thinkchina-fargate-2017312409.ap-southeast-1.elb.amazonaws.com/

**Comment by diehlaws** [comment]
Hi @liaogz82, thanks for reaching out to us. Please keep in mind that S3FS is a third party product that is not supported by Amazon; we do not recommend using S3 as a file system as this can result in odd behavior under various use cases.

That being said, the provided error does not appear to be caused by the AWS SDK for PHP. [cURL error 7](https://curl.haxx.se/libcurl/c/libcurl-errors.html) (Failed to  connect() to host or proxy) suggests your fargate cluster is unable to reach the S3 bucket you're using. Are you able to reach the [S3 endpoint](https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region) for the region in which your bucket resides from your fargate cluster using a method that does not use the AWS SDK for PHP? (e.g. `nc`, `curl`, an HTTP HEAD call in PHP, etc)

**Comment by liaogz82** [comment]
Hi @diehlaws as mentioned above I run 2 cluster and the problem only shows up at fargate. The ECS EC2 cluster has no problem with S3FS and they use the same image in ECR. They also use the same subnet and security groups.

I suspect it is because my container is running multiple threads and the metadata is only available in PID 1 as stated here https://forums.aws.amazon.com/thread.jspa?threadID=273767

Nevertheless I can do some curl testing call. Are there any specific details in curl you want me to get?

**Comment by liaogz82** [comment]
Hi @diehlaws I discovered that there is indeed a curl error. I tried curling https://account-id.s3-control.ap-southeast-1.amazonaws.com from fargate and it did throw me this error

`InvalidURICouldn't parse the specified URI.78AC3006F5EA8F46HtB63GZ/H9728KIF8O47hbjq037esXABFv3b5CipUlJ4Pv0LaKO0J9UvGxmwpAgdm4wIcPWkJY8=`

I guess this is in the support domain?

**Comment by liaogz82** [comment]
Hi. I checked the Drupal S3FS code. And ya they make no provision for fargate deployment

https://git.drupalcode.org/project/s3fs/blob/8.x-3.x/src/S3fsService.php#L157

I am considering sending a pull request to them to use fargate. Is there a way to use AWS PHP SDK to get task profile?

**Comment by liaogz82** [comment]
Closing the issue. There is `CredentialProvider::ecsCredentials();` for ECS drupal setup
