### ISSUE TITLE
Publish checksums in Github releases

### ISSUE THREAD

**Issue by andrewodri** [aws/aws-sdk-php#1899]
When building Docker containers inside a CI environment, the version of the AWS SDK being used is often pinned to a specific version. Downloading the `aws.phar` archive from GitHub releases the easiest way to to obtain a specific version of the SDK. In order to improve security and reduce the potential impact of a supply chain attack, it would ideal if the checksums could be published for validation of the archive during the image build process.

If these could be published as separate files for common hashing algorithms (e.g. MD5, SHA1, SHA256), that would allow for a measure of consistency with other PHP based projects (eg. https://wordpress.org/download/releases/ and https://github.com/wp-cli/wp-cli/releases).

I realize that these could also be generated by the developer and embedded in the image. However, if these were made available from a source within the publisher's control then at least hashes could be validated with a greater measure of confidence.

**Comment by diehlaws** [comment]
Hi @andrewodri, thanks for reaching out to us about this. This seems like a reasonable feature request, however we unfortunately have higher priority items to implement at this time so we may not be able to implement what you're requesting right away. Once we have more information on this we'll update the issue accordingly.

**Comment by udf2457** [comment]
@andrewodri Just my two cents worth, checksums are great, but they don't do much for security without the validation infrastructure provided by digital signatures.  Digital signatures then brings into the question of securing the private key.

So from that perspective I agree with @diehlaws, I would rather they focus on other higher priority items and then come back to this one with a more complete solution rather than just a quick-hack script that calculates some shasums.

**Comment by yenfryherrerafeliz** [comment]
Hi @andrewodri, we will be closing this feature request since there is not intention from us to implement this at this time. We prioritize features and bug fixes based on community engagement and reactions, and we have not found enough interest from the community for this one.

Thanks!
