### ISSUE TITLE
The sns service does not have version

### ISSUE THREAD

**Issue by eegrab** [aws/aws-sdk-php#1901]
I have receive this below error. i am using simple aws.zip file

<br />
<b>Fatal error</b>:  Uncaught Aws\Exception\UnresolvedApiException: The sns service does not have version: 2012-10-17. in /var/www/clients/client0/web1/web/ihub/aws/Aws/Api/ApiProvider.php:85
Stack trace:
#0 /var/www/clients/client0/web1/web/ihub/aws/Aws/ClientResolver.php(486): Aws\Api\ApiProvider::resolve(Object(Aws\Api\ApiProvider), 'api', 'sns', '2012-10-17')
#1 /var/www/clients/client0/web1/web/ihub/aws/Aws/ClientResolver.php(314): Aws\ClientResolver::_apply_api_provider(Object(Aws\Api\ApiProvider), Array, Object(Aws\HandlerList))
#2 /var/www/clients/client0/web1/web/ihub/aws/Aws/AwsClient.php(187): Aws\ClientResolver-&gt;resolve(Array, Object(Aws\HandlerList))
#3 /var/www/clients/client0/web1/web/ihub/create_topic.php(45): Aws\AwsClient-&gt;__construct(Array)
#4 {main}
  thrown in <b>/var/www/clients/client0/web1/web/ihub/aws/Aws/Api/ApiProvider.php</b> on line <b>85</b><br />

**Comment by diehlaws** [comment]
Hi @eegrab, thanks for reaching out to us. As the error suggests, the version string `2012-10-17` is not a valid API version for for SNS. Per our [SnsClient documentation](https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Sns.SnsClient.html) and the service's [API reference](https://docs.aws.amazon.com/sns/latest/api/Welcome.html) the only API version currently available for this service is `2010-03-31`. 

In order to resolve this error you'll want to set `'version' => 'latest',` or `'version' => '2010-03-31',` in the SNS client's initialization parameters.
