### ISSUE TITLE
[GetObject] - Linux fopen() File name too long error

### ISSUE THREAD

**Issue by mauretto78** [aws/aws-sdk-php#1911]
Hello,

I guess that I found an inconsistency.

I am using AWS SDK v3.93 with PHP5.6.

As [documentation reports:](https://docs.aws.amazon.com/en_us/AmazonS3/latest/dev/UsingMetadata.html):

> When you create an object, you specify the key name, which uniquely identifies the object in the bucket. For example, in the Amazon S3 console, when you highlight a bucket, a list of objects in your bucket appears. These names are the object keys. The name for a key is a sequence of Unicode characters whose UTF-8 encoding is at most 1024 bytes long.

So, I can upload an object with a name length of 500 characters, for example.

But what happens when I make a GetObject request for that file?

Look at this example, I got this error:

```
Error executing \"GetObject\" on \"https://s3.eu-central-1.amazonaws.com/xxxxxxxxxxxx/files/20191125/4024893/xliff/Package_2_-_%D0%98%D0%BD%D0%B6%D0%B5%D0%BD%D0%B5%D1%80%D0%BD%D0%B0%D1%8F_%D0%BE%D1%86%D0%B5%D0%BD%D0%BA%D0%B0_%D0%93%D1%83%D0%BB%D0%B8%D1%81%D1%82%D0%B0%D0%BD_%D0%9A%D0%9D%D0%A1_9-10-11.zip___SEP___Package_2_-_%D0%98%D0%BD%D0%B6%D0%B5%D0%BD%D0%B5%D1%80%D0%BD%D0%B0%D1%8F_%D0%BE%D1%86%D0%B5%D0%BD%D0%BA%D0%B0_%D0%93%D1%83%D0%BB%D0%B8%D1%81%D1%82%D0%B0%D0%BD_%D0%9A%D0%9D%D0%A1_9-10-11___SEP___%D0%93%D0%A3%D0%9B%D0%98%D0%A1%D0%A2%D0%90%D0%9D_%D0%9A%D0%9D%D0%A1_10___SEP___100.03_%D0%94%D0%B5%D1%84%D0%B5%D0%BA%D1%82%D0%BD%D1%8B%D0%B9_%D0%B0%D0%BA%D1%82_.xls.sdlxliff\";
AWS HTTP error: Unable to open /tmp/5ddfab5e8a6aa9.45666312_.out.Package_2_-_Инженерная_оценка_Гулистан_КНС_9-10-11.zip___SEP___Package_2_-_Инженерная_оценка_Гулистан_КНС_9-10-11___SEP___ГУЛИСТАН_КНС_10___SEP___100.03_Дефектный_акт_.xls.sdlxliff using mode w+:
fopen(/tmp/5ddfab5e8a6aa9.45666312_.out.Package_2_-_Инженерная_оценка_Гулистан_КНС_9-10-11.zip___SEP___Package_2_-_Инженерная_оценка_Гулистан_КНС_9-10-11___SEP___ГУЛИСТАН_КНС_10___SEP___100.03_Дефектный_акт_.xls.sdlxliff): failed to open stream: File name too long
```

The error is perfectly clear to me: AWS tries to create a temporary copy of the file, but the filename is greater than **255 bytes**, and then Linux cannot create the file.

[As you know indeed, the maximum length of a file path in Ubuntu is 255](https://en.wikipedia.org/wiki/Ext4).

And `/tmp/5ddfab5e8a6aa9.45666312_.out.Package_2_-_Инженерная_оценка_Гулистан_КНС_9-10-11.zip___SEP___Package_2_-_Инженерная_оценка_Гулистан_КНС_9-10-11___SEP___ГУЛИСТАН_КНС_10___SEP___100.03_Дефектный_акт_.xls.sdlxliff`  is 291 bytes long.

So, IMHO, you should fix this: maybe you can assign a hash as the temporary file name. 

I hope this can help you,

M.

**Comment by diehlaws** [comment]
Thanks for reaching out to us @mauretto78. While you are correct regarding Ubuntu's maximum file path length, this is not the only OS on which the AWS SDK for PHP can run and this limit does not apply to all existing operating systems. For example, Windows Server 2016 and newer have a registry key that can be enabled to support file paths longer than 260 characters.

In addition to this, having the SDK automatically truncate the filename of a given object on a `GetObject` call could lead to unexpected behavior - for example, if a variable is set to the key name and is re-used for the local file after a `GetObject` call, the SDK would not automatically change this variable to account for the truncated filename, which would lead to a `No such file or directory` error since the filename no longer matches the variable name.

As a result, the application that uses the AWS SDK for PHP should account for the limitations in the environment in which it is running rather than having the SDK account for all possible environment-specific limitations. You can use the `SaveAs` parameter in your `getObject` call to truncate the filename before the file is written to the local filesystem as shown below.

```php
$resp = $client->getObject([
    'Bucket' => $bucket,
    'Key' => $prefix.$longfilename,
    'SaveAs' => substr($longfilename, 0, 230)
]);
```

**Comment by mauretto78** [comment]
Thanks for your quick reply @diehlaws .

It makes sense to me; I guess that maybe you should add a note to be aware of this potential problem on the SDK official documentation.

I recently developed an abstraction layer on top of the SDK client, which works pretty well, and I already produced a fix to this issue:  

[https://github.com/matecat/simple-s3/blob/master/src/Helpers/Filename.php](https://github.com/matecat/simple-s3/blob/master/src/Helpers/Filename.php)

This class automatically reduces the filename size to a "safe" value of maximum 221 bytes (taking into account the temporary path length).

Thanks again for your support,

M.
