### ISSUE TITLE
Error parsing response for CreateBucket

### ISSUE THREAD

**Issue by rikybordo** [aws/aws-sdk-php#1929]
### Version of AWS SDK for PHP?
3.129

### Version of PHP (`php -v`)?
PHP 7.1.19

### What issue did you see?
When i try to create a bucket with [createBucket](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#createbucket) function, the bucket was created but the response throw this error:
```
Fatal error: Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error parsing response for CreateBucket: AWS parsing error: Error parsing XML: String could not be parsed as XML'

Exception: String could not be parsed as XML in /Applications/MAMP/htdocs/Repos/ceph-api/custom/vendor/aws/aws-sdk-php/src/Api/Parser/PayloadParserTrait.php:44
Stack trace:
#0 /Applications/MAMP/htdocs/Repos/ceph-api/custom/vendor/aws/aws-sdk-php/src/Api/Parser/PayloadParserTrait.php(44): SimpleXMLElement->__construct('{"entry_point_o...')
#1 /Applications/MAMP/htdocs/Repos/ceph-api/custom/vendor/aws/aws-sdk-php/src/Api/Parser/RestXmlParser.php(39): Aws\Api\Parser\RestXmlParser->parseXml(Object(GuzzleHttp\Psr7\Stream), Object(GuzzleHttp\Psr7\Response))
#2 /Applications/MAMP/htdocs/Repos/ceph-api/custom/vendor/aws/aws-sdk-php/src/Api/Parser/RestXmlParser.php(31): Aws\Api\Parser\RestXmlParser->parseMemberFromStream(Object(GuzzleHttp\Psr7\Stream), Object(Aws\Api\StructureShape), Object(GuzzleHttp\Psr7\Response))
```

### Steps to reproduce
Simply call the function:
```
// Instantiate the S3 class and point it at the desired host
$client = new S3Client([
    'region' => '',
    'version' => 'latest',
    'endpoint' => $ENDPOINT,
    'credentials' => [
        'key' => AWS_KEY,
        'secret' => AWS_SECRET_KEY
    ],
    'use_path_style_endpoint' => true
]);

$client->createBucket(['Bucket' => 'Test']);
```

### Additional context
I've installed rados gateway on Ceph (version 14.2.4 - nautilus)

**Comment by diehlaws** [comment]
Hi @rikybordo, thanks for reaching out to us. The AWS SDKs are only guaranteed to work with AWS services. While in theory they should work with third party services that use the same REST APIs, any incompatibilities with third party services would unfortunately fall outside of the scope of the AWS SDKs.

That being said, it sounds like the response provided to the SDK from RADOS Gateway is not properly formatted as XML which is what the SDK is expecting in the response body from the service. You can confirm whether this is the case by setting `'debug' => true` in your `S3Client` config and looking at the resulting output of a `CreateBucket` call to this service. If the response does appear to be XML but is not formatted in the same manner as S3's XML response for a `CreateBucket` call I'd suggest reaching out to Ceph about the manner in which their service responds to this type of call. Or if the response from the service isn't XML at all it may be appropriate to raise a feature request with Ceph to implement their service's response to this call as XML.

If you don't care what the service's response is (given the bucket is being created as expected) and just want to avoid this error from causing your application to exit, you can enclose your `CreateBucket` call within a try/catch block to catch this particular exception type so that your application continues despite receiving this error.

**Comment by rikybordo** [comment]
Hi @diehlaws, thanks for your time, i've added a try cath to the function and for now i ignore this error.
