### ISSUE TITLE
Can't publish message to SQS from Lambda

### ISSUE THREAD

**Issue by pavinthan** [aws/aws-sdk-php#1942]
I try to deploy Laravel application using AWS Lambda

### Version of AWS SDK for PHP?
3.130.2

### Version of PHP (`php -v`)?
7.3

### What issue did you see?
Error executing \"SendMessage\" on \"https:\/\/sqs.ap-southeast-1.amazonaws.com\/622706049672\/LaravelCLI-production\"; AWS HTTP error: Client error: `POST https:\/\/sqs.ap-southeast-1.amazonaws.com\/622706049672\/LaravelCLI-production` resulted in a `403 Forbidden` response:\nSender<\/Type>I (truncated...)\n InvalidClientTokenId (client): The security token included in the request is invalid. - Sender<\/Type>InvalidClientTokenId<\/Code>The security token included in the request is invalid.<\/Message><\/Error>c2c5e1fe-25f2-500c-94e4-b779ac203758<\/RequestId><\/ErrorResponse>

### Steps to reproduce
I have created an role with following permissions
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "ec2:CreateNetworkInterface",
                "ec2:DeleteNetworkInterface",
                "ec2:DescribeNetworkInterfaces",
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents",
                "ssm:GetParameters",
                "ssm:GetParameter",
                "lambda:invokeFunction",
                "s3:*",
                "ses:*",
                "sqs:*",
                "dynamodb:*",
                "route53domains:*"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}
```
and create a Lambda function with custom runtime and try to dispatch a job to SQS to queue but that time I got this message.

 VPC is not assigned

**Comment by diehlaws** [comment]
Hi @pavinthan, thanks for reaching out to us. This behavior sounds like a configuration issue within the Lambda function rather than a bug in the AWS SDK for PHP. Can you provide a code sample showing how the SQS client is being initialized in your function? Are you able to reproduce this behavior in an environment outside of Lambda (e.g. on an EC2 instance)? If your code works as expected outside of Lambda I'd suggest reaching out to our Premium Support team by opening a [new technical support case](https://console.aws.amazon.com/support/cases#/create) under the Lambda service for further support on the service end. That being said, following are some considerations for troubleshooting this error.

Does this behavior occur with other calls to AWS services? E.g. can you successfully issue a `ListQueues` call to SQS, or a `ListBuckets` call to S3 within the same Lambda function?

Can you verify that your Lambda function is assuming your IAM role as expected? You can check this with a `GetCallerIdentity` call with an STS client that is initialized with the same credentials as your SQS client.

Was your IAM role created during the creation of the Lambda function? If not, you'll want to make sure that the role's trust relationship policy allows Lambda to assume the role as shown below.

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

**Comment by pavinthan** [comment]
Hi @diehlaws sorry for my delay and thanks for your response,

Yes that code work outside of AWS Lambda and this is my trust relationship.
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "apigateway.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    },
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

and I found the issue that AWS Lambda execution envirement variables don't have access to execute SNS but if I chage the config and provide blank envirement variables that works fine.

**Comment by diehlaws** [comment]
Thanks for the additional information @pavinthan, I'm glad you were able to get your Lambda functions executing properly 😄
I'm closing out the issue, however if you have any additional questions about this please do feel free to comment and/or re-open the issue so we can continue working on this.
