### ISSUE TITLE
Warning, Notice in vendor/guzzlehttp/guzzle/src/Client.php and 1 Fatal Error

### ISSUE THREAD

**Issue by RaviJayagopal** [aws/aws-sdk-php#1963]
### Version of AWS SDK for PHP?
Latest, I guess. Using composer.

### Version of PHP (`php -v`)?
7.1.14

### What issue did you see? 
ISSUE #1
1 notice and 1 warning. not sure if this has anything to do with my 2nd issue.
Notice: Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' in /home3/cofwpaul/public_html/wp-content/plugins/S3MediaVaultPro/vendor/guzzlehttp/guzzle/src/Client.php on line 221

Warning: idn_to_ascii() expects parameter 3 to be integer, string given in /home3/cofwpaul/public_html/wp-content/plugins/S3MediaVaultPro/vendor/guzzlehttp/guzzle/src/Client.php on line 221

ISSUE #2
My code connects to S3 as follows:

$s3Client = new Aws\S3\S3MultiRegionClient([
                'version'     => 'latest',
                'region'      => 'us-east-1',
                'credentials' => [
                    'key'    => $accessKey,
                    'secret' => $secretKey,
                ],
            ]);

$region = $s3Client->determineBucketRegion($bucketname); // <= LINE E

It is working on a lot of websites just fine, but on one website, right at LINE E above, it triggers a PHP Exception, and the error when I print it says "Host must be a string". That message is coming from S3, not in my code.

How can I troubleshoot and fix this?

Thanks!

- Ravi

**Comment by diehlaws** [comment]
Hi @RaviJayagopal, thanks for reaching out to us. Can you please provide the exact version of the AWS SDK for PHP you're using? This will help us ensure you aren't using an older version and running into something that has been fixed in a newer release. You can check the SDK's version either by running `composer show` in the directory that contains your `composer.json` or by printing `Aws\Sdk::VERSION` in your code. Seeing the version of Guzzle being used would also be helpful for issue 1 since the notice and warning look to be originating from that package.

Unfortunately for issue 1 the given notice and warning provided do not make it clear what action is being taken with the AWS SDK for PHP that is causing this behavior. Does this occur consistently on a given action, or does it only happen under specific circumstances? Enabling [debug logging](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#debug) on the service client and providing the resultant output for a call that results in this behavior would help us better understand what's causing this.

For issue 2, seeing the full stack trace for the error returned would help us understand which function this error is originating from. Additionally, dumping the `$bucketname` variable for the website that exhibits this behavior would help determine why it's not considered a string.

Are you able to reproduce either of these issues using the AWS SDK for PHP without the S3MediaVaultPro WordPress plugin? If so, seeing code samples that consistently exhibit this behavior would help us troubleshoot this with more accuracy.

**Comment by RaviJayagopal** [comment]
This is resolved by updating to latest PHP SDK. Thanks!
