### ISSUE TITLE
s3 error when fclose is not called

### ISSUE THREAD

**Issue by rbro** [aws/aws-sdk-php#1967]
### Version of AWS SDK for PHP?
3.133.15

### Version of PHP (`php -v`)?
7.3.14

### What issue did you see?
I noticed that if I enable stream wrappers and write to a file, but don't run fclose(), I get an error.

### Steps to reproduce
```
<?php
$s3->registerStreamWrapper();

$fp = fopen('s3://test/test1', 'w');

fwrite($fp, 'test');
?>
```

The error I get is:

```
Fatal error: Uncaught Error: Class 'Aws\Command' not found in /tmp/aws/Aws/AwsClient.php:258
```

If I do fopen with 'x' instead of 'w', I get:

```
Fatal error: Uncaught Error: Class 'Aws\Api\MapShape' not found in /tmp/aws/Aws/Api/Shape.php:47
```

Both run successfully if I run:

```
fclose($fp);
```

Thank you for checking this.  Please let me know if I can give any more info.

**Comment by diehlaws** [comment]
Hi @rbro, thanks for reaching out to us. The behavior you describe is expected - per our S3 StreamWrapper's [documentation page](https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.S3.StreamWrapper.html), write only streams will maintain a 'php://temp' stream to buffer data written to the stream until the stream is flushed (usually by closing the stream with fclose). This is because S3 requires the 'Content-Length' header which cannot be accurately determined until the stream is flushed - if you want to write to the same S3 object multiple times within the same script without closing and re-opening its handle you can flush the stream via `fflush()` each time you want to write to the object, however it is good practice to close the handle before the script finishes executing.

**Comment by rbro** [comment]
Hi @diehlaws - thanks, makes sense.  I normally call fclose() always.  I'm new to using aws-sdk-php and hadn't put in the fclose call in my test script, but just wasn't expecting an error like that where it seems more like a class was missing (I first checked to make sure that the php file for that class existed).

**Comment by techdaddies-kevin** [comment]
Thank you @rbro for posting this. I was tearing my hair out over here trying to figure out why I was getting such an odd error message, and indeed, it's because I had forgotten to close the file handler.

**Comment by diehlaws** [comment]
Thanks for the additional information @rbro, and I do apologize for the long delay in response on our end. While it will be difficult to find a way to have the SDK determine whether a file's stream within the S3 Stream Wrapper is flushed/closed before the script finishes running, we've added a backlog item to investigate whether we can find a way to improve the error handling for this behavior.
