### ISSUE TITLE
EcsCredentialProvider doesn't work for php-fpm due to missing relative uri env variable

### ISSUE THREAD

**Issue by Pi-George** [aws/aws-sdk-php#1971]
https://github.com/aws/aws-sdk-php/blob/master/src/Credentials/EcsCredentialProvider.php

Environment variable doesn't exist in php-fpm runtime $AWS_CONTAINER_CREDENTIALS_RELATIVE_URI

This issue is a clone of this closed issue, however the issue shouldn't of been closed so I'm making this one https://github.com/aws/aws-sdk-php/issues/1920

This code in your entrypoint file before starting php-fpm should act as a temporary fix.

```
if [ -f /proc/1/environ ]; then
    # Get the ECS environment variables
    export $(strings /proc/1/environ)
    # Set the AWS_CONTAINER_CREDENTIALS_RELATIVE_URI environment variable if it isn't already set
    if ! grep -q 'AWS_CONTAINER_CREDENTIALS_RELATIVE_URI' /etc/php/7.2/fpm/pool.d/www.conf; then
        echo "clear_env = no" >> /etc/php/7.2/fpm/pool.d/www.conf
        echo "env[AWS_CONTAINER_CREDENTIALS_RELATIVE_URI] = $AWS_CONTAINER_CREDENTIALS_RELATIVE_URI" \
            >> /etc/php/7.2/fpm/pool.d/www.conf
    fi
else
    echo "Warning, couldn't find ECS environ file"
fi
```

**Comment by magnetik** [comment]
Thanks a lot for the pointer.
I've added:

`echo "env[AWS_CONTAINER_CREDENTIALS_RELATIVE_URI] = $(strings /proc/1/environ | grep AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | cut -d = -f2 )" >> /usr/local/etc/php-fpm.d/www.conf`

to my docker entrypoint 👍

**Comment by Shardj** [comment]
I've since improved mine, if you're using ubuntu or another OS that has /etc/environment then you can do

```
    # Get the ECS environment variables
    export $(strings /proc/1/environ)
    # Make sure php has access to environment variables
    env > /etc/environment
```

As long as your php-fpm pool has `clear_env = no` and as long as you start php-fpm with `/etc/init.d/php7.2-fpm start` and not `service php7.2-fpm start`. No idea why service doesn't work and init.d does, but it is how it is.

**Comment by Pi-George** [comment]
Still an issue as far as I'm aware github bot

**Comment by Shardj** [comment]
stop avoiding the issue bot

**Comment by yenfryherrerafeliz** [comment]
Hi @Shardj, @Pi-George, could you please elaborate more regarding why this is a bug with the PHP SDK?. For me this seems to be an issue with php-fpm and not with the SDK. The SDK expects that either AWS_CONTAINER_CREDENTIALS_FULL_URI or AWS_CONTAINER_CREDENTIALS_RELATIVE_URI is set, otherwise it will will fail. Those variables are injected by ECS when running the container, and if they are not available then it means something prevent those variables from being set. I got a similar issue in the past and I was able to provide the following workaround [here](https://github.com/aws/aws-sdk-php/issues/2751#issuecomment-1684794062) that seems to aid that issue at that time. 

Would you please be able to try the workaround I have provided and let me know if that works?

Thanks!

**Comment by vc-ishan-tripathi** [comment]
@yenfryherrerafeliz - This issue still a ghost.... I am currently facing this with my ECS Fargate setup on PHP 8.2 Laravel 10
I have already tried your script work around but no luck. I tried SSH into the container and it shows up in both .env as well as container env.

Can you provide a solution to this ASAP
