### ISSUE TITLE
CreateInvalidation Error

### ISSUE THREAD

**Issue by FreelanceWebNinja** [aws/aws-sdk-php#1973]
Suddenly getting odd error. Literally no code or keys have changed. Using version: latest.

Error executing "CreateInvalidation" on "https://cloudfront.amazonaws.com/2019-03-26/distribution/XXX/invalidation"; AWS HTTP error: Client error: `POST https://cloudfront.amazonaws.com/2019-03-26/distribution/XXX/invalidation` resulted in a `400 Bad Request` response: Sender< (truncated...) MalformedXML (client): 1 validation error detected: Value null at 'invalidationBatch' failed to satisfy constraint: Member must not be null - SenderMalformedXML1 validation error detected: Value null at 'invalidationBatch' failed to satisfy constraint: Member must not be null

**Comment by diehlaws** [comment]
Hi @FreelanceWebNinja, thanks for reaching out to us. Aside from documentation updates, changes to the CloudFront client for the AWS SDK for PHP in 2019 and 2020 have been minimal. Have you recently updated your version of the SDK? Which version did you update from?

Please fill out the issue template so we can better assist with this. Seeing a code snippet showing how the input parameters for your `CreateInvalidation` call are being populated (specifically the contents of `InvalidationBatch`) would help us better troubleshoot this behavior.



```
Please fill out the sections below to help us address your issue.

### Exact version of AWS SDK for PHP?


### Version of PHP (`php -v`)?


### What issue did you see?


### Steps to reproduce
If you have a runnable example, please include it as a snippet or link to a repository/gist for larger code examples.

### Additional context
Any additional information relevant to the issue. Examples include any framework you may be using (e.g. Laravel, Wordpress) in conjunction with the AWS SDK for PHP, or PHP/environment config settings if the issue is related to memory or performance.
```

**Comment by treyseals** [comment]
I'm confused. You closed the issue before I could reply?

**Comment by diehlaws** [comment]
@treyseals We typically close issues after 11 days of inactivity in order to prevent inactive issues from building up in the repository. Unfortunately the information provided is not sufficient for us to troubleshoot the behavior you're seeing. Please provide the information requested above so that we may assist you with the error you're receiving from the AWS SDK for PHP.

**Comment by diehlaws** [comment]
@FreelanceWebNinja please provide the requested information to prevent the issue from closing once again due to inactivity.

**Comment by diehlaws** [comment]
Hi @FreelanceWebNinja @treyseals, due to inactivity on the issue I'll be closing this out once again. Once you have a chance to collect the information requested above please open a new issue with this information in the initial post so we can assist you with the behavior you're seeing with the SDK's CloudFront client.
