### ISSUE TITLE
access denied on assumeRole with MFA enabled user

### ISSUE THREAD

**Issue by monaye** [aws/aws-sdk-php#1976]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?
3.133

### Version of PHP (`php -v`)?
PHP 7.2.20

### What issue did you see?
I have a following simple code trying to get the session, but it returns the access denied error. I have double-checked that the user has permission to perform the assume role. What is causing the access denied is very unclear. 

```php
// AWS Returns access denied on following
use Aws\Lambda\LambdaClient;
use Aws\Sts\StsClient;


putenv('AWS_SDK_LOAD_NONDEFAULT_CONFIG=1');

$client = StsClient::factory(array('version' => 'latest', 'profile' => 'build-account', 'region' => 'us-east-1'));

try {
  $session = $client->getSessionToken([
            'DurationSeconds' => 3600,
            'SerialNumber' => 'arn:aws:iam::83649276487334:mfa/win', 
            'TokenCode' => '194086']);

  dd($session);

} catch (AwsException $e) {

   dd($e->getMessage());

}
```
Above code returns following error 
```
Error: User: arn:aws:iam::83649276487334:user/awsauth/win is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::83649276487334:role/awsauth/build
IAM user or role experiencing the issue: 
```
To confirm I have correct permission, I run following code
```
// this returns the correct credential information 
aws sts get-caller-identity --profile build-account
```
I've chatted with the support team multiple times and they also went through the console to confirm all the permission settings, but permission settings seem ok. In fact, I was able to run the sts command proves that, but not sure why it keeps giving me the access denied when using the SDK.

**Comment by diehlaws** [comment]
Hi @monaye, thanks for reaching out to us. Unfortunately it is not possible to obtain a session token using session-based credentials - this applies to all AWS SDKs as well as the AWS CLI. Attempting to issue a `GetSessionToken` call with the AWS CLI (as well as the AWS SDK for Go and boto3) returns the error `AccessDenied: Cannot call GetSessionToken with session credentials` from STS. By contrast, the AWS SDK for PHP seems to be erroring out when attempting to assume the role for the specified profile due to a lack of a token provided for the MFA-enabled IAM user set as the `source_profile` for the role's profile. This behavior is something we'll be investigating separately in further detail so that we can support assuming a role from the shared credentials file with an underlying MFA-enabled user.

That being said, the output of both `GetSessionToken` and `AssumeRole` contains the same `Credentials` fields (access key ID, secret access key, session token, and expiration). As such, given the lack of ability to obtain a session token using session-based credentials, the correct approach for your use case would be to initialize your STS client using the profile for the MFA-enabled IAM user to issue an `assumeRole` call to the role corresponding to your `build-account` profile in order to retrieve the temporary security credentials you're looking for:

```php
$resp = $client->assumeRole([
    'DurationSeconds' => 3600,
    'RoleArn' => 'arn:aws:iam::<account-id>:role/<role-name>',
    'RoleSessionName' => '<session-name>',
    'SerialNumber' => 'arn:aws:iam::<account-id>:mfa/<token-name>',
    'TokenCode' => '<OTP>'
]);
```
