### ISSUE TITLE
Use late static binding for credential resolution

### ISSUE THREAD

**Issue by jradtilbrook** [aws/aws-sdk-php#1985]
### Is this related to a problem?
I use this package through the [Laravel extension](https://github.com/aws/aws-sdk-php-laravel). However, when caching configuration, Laravel empties the environment variables so `getenv()` and `$_ENV` returns null or contains nothing.

### Feature description
As such, I would like to extend the CredentialProvider to use [late static binding](https://www.php.net/manual/en/language.oop5.late-static-bindings.php) when calling class methods so that it would use a child classes definition of the `env()` method. In this method I would implement laravel specific logic to get environment credentials that have been cached (rather than using `getenv()`.

### Describe alternatives you've considered
There isn't really an alternative I can think of except to not cache configuration. However, I strongly want to keep that for performance reasons.

### Additional context
N/A

This should be a very simple change and shouldn't have any repercussions. I can provide a PR if this change would be accepted

**Comment by diehlaws** [comment]
Hi @jradtilbrook, thanks for reaching out to us about this. Unfortunately there was a [bug](https://bugs.php.net/bug.php?id=66622) relating to late static bindings that was fixed in PHP version [5.5.14](https://3v4l.org/lk4i0#v5514), however the current major version of the AWS SDK for PHP must maintain compatibility with PHP version 5.5.0 and up.

If this can be implemented in a manner that is not affected by this bug we'd be happy to review a PR for this change, however if it exhibits the buggy behavior in versions 5.5.0-5.5.13 we unfortunately wouldn't be able to implement this feature until we release a new major version of the SDK.

**Comment by jradtilbrook** [comment]
Thanks, @diehlaws that's good to know. I'll look into other ways to achieve this and get back to you
