### ISSUE TITLE
S3 billing went to the sky all of a sudden

### ISSUE THREAD

**Issue by khanof89** [aws/aws-sdk-php#1989]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP?**
Example: v3.133.20
* get SDK version by printing the output of `Aws\Sdk::VERSION` in your code 
* if the SDK was installed via composer you can see the version installed with `composer show -i` 

**Version of PHP (`php -v`)?**
PHP/7.3.13-1+ubuntu18.04.1+deb.sury.org+1

**Describe the question**
Since last 20 days my everyday bill of s3 storage spiked from $1-$2 to $90-$100 upon debugging found out that my cron server is sending unlimited requests to bucket and trying to access files which do not even exists, I have first removed all the code which in anyway uses s3 storage, the billing did not reduce, then I have stopped the cron and killed all the scripts, I have removed the bucket name and access key and access secret from environment variable the requests are still heading to s3 bucket. My question is, is there any known/lates bug which starts sending request to s3 bucket ? Following is the message I see in S3 server access log files: 

f6fba15fb4fd39a431fdae255e70153f7128bac77b7f864038dd7a358791ce28 MY-BUCKET-NAME [29/Mar/2020:12:30:29 +0000] MY-CRON-SERVER-IP - 1E0C1C2CE66F7BDC REST.GET.BUCKET - "GET /MY-BUCKET-NAME?prefix=photo_folder%2F96%2F14260196_9.jpg%2F&max-keys=1&encoding-type=url HTTP/1.1" 403 InvalidAccessKeyId 354 - 3 - "-" "aws-sdk-php/3.133.20 GuzzleHttp/6.5.1 curl/7.58.0 PHP/7.3.13-1+ubuntu18.04.1+deb.sury.org+1" - SomeSortOfLongIdentifierGoesHereSeemsLikeRequestSignature ECDHE-RSA-AES128-GCM-SHA256 AuthHeader s3.amazonaws.com TLSv1.2

**Comment by diehlaws** [comment]
Hi @khanof89, thanks for reaching out to us. Looking at our [changelog](https://github.com/aws/aws-sdk-php/blob/master/CHANGELOG.md) the most recent change relating to S3 (on March 16th) was to implement support for tagging Batch Operations jobs for S3Control, which should not have affected standard S3 operations such as `listObjects` or `listObjectsV2`. The AWS SDK for PHP should not be issuing any requests to S3 that were not called via a function from the `S3Client`.

Is there any chance you have a third party utility or plugin that uses the SDK under the hood to, for example, display content hosted on S3 or back up local content to an S3 Bucket? The query string in the provided log entry suggests that the SDK is looking for a specific image object in the `photo_folder` prefix within your bucket. However, S3 is returning an error due to the Access Key ID used in the request not being valid, so while it looks like removing your access key

**Comment by khanof89** [comment]
@diehlaws thank you for the response, I was not able to get to a definitive answer for what was causing the issue, the access log were not of much help because they were behind, the log created right now was of 90 minutes ago(may be because of so many requests that my app was sending) so I end up removing aws sdk from my code base and now the everyday bill is under control
