### ISSUE TITLE
Help for Multiple 'AND' , 'OR' ConditionalOperator in a DynamoDB  getIterator('Scan')

### ISSUE THREAD

**Issue by sijoph** [aws/aws-sdk-php#1993]
Please Help :

AWS SDK Version 2.8 
PHP version 5.4

How to write a program with  multiple keyword search with DynamoDB - PHP :

 $cityIterator = $this->dynamoDbClient->getIterator('Scan', array(
				'TableName' => $tableName,
				"AttributesToGet" => array( "id","name","region"),
				"ConsistentRead" => true,
				'ScanFilter' => array(
					'account_type' => array(
						'AttributeValueList' => array(array('S' => "SELLER")),
						'ComparisonOperator' => 'EQ'
					),
					'country' => array(
						'AttributeValueList' => array(array('S' => 'US')),
						'ComparisonOperator' => 'EQ'
					),
					'name' => array(
						'AttributeValueList' => array(array('S' => 'houst')),
						'ComparisonOperator' => 'CONTAINS'
					),
				),
				'ConditionalOperator' => 'AND'
			),
			array(
				'limit' => 25 
			)
		);

The above program is working for me. But iam trying to write the program for keywords search on table column "name" OR "region" with multiple keywords 

LIKE MYSQL QUERY => SELECT * FROM tablename WHERE (account_type='SELLER' AND COUNTRY='US') AND (NAME LIKE "%hous%" OR REGION LIKE "%hous%" OR NAME LIKE "%illino%" OR REGION LIKE "%illino%")  

For example i have input text to type a city name like "houston" OR "Illinois" OR "manhattan". If one user type the input as "hous illino manhat". I need a search query in DynamoDB with PHP program. Could you please help me with this issue. Iam in trouble.

I tried with searching.
Please HELP
Thanks in Advance

**Comment by diehlaws** [comment]
Hi @sijoph, thanks for reaching out to us. While I understand the level of urgency of your request, and I sympathize with the situation in which you find yourself, unfortunately a request of this nature falls beyond the scope of support for the AWS SDKs. 

While I'm happy to provide guidance with questions that specifically address how to use the SDK in a given manner, translating a MySQL query to the appropriate parameters for a DynamoDB Scan operation does not fall within our area of expertise. Questions surrounding the usage of DynamoDB would be better served by either opening a [new Technical Support case](https://console.aws.amazon.com/support/home?#/case/create) under the DynamoDB service, posting in the [DynamoDB section of the AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=131), or requesting help from other users that are more familiar with the using this service on [StackOverflow](https://stackoverflow.com/). If you require more in depth guidance with the service than these alternatives can offer I suggest looking into the [AWS Partner Network](https://aws.amazon.com/partners/) for a Partner that can guide you in effectively using DynamoDB within your PHP application.

That being said, I see that you are using a version of PHP that has been [EOL since September 3rd, 2015](https://www.php.net/eol.php). I strongly suggest updating your version of PHP as soon as you can as using the current version may expose you to security vulnerabilities and bugs that have been fixed in more recent versions of PHP. While version 2.8 of the AWS SDK for PHP is still technically supported, it has not seen a minor version update since 2015. I strongly suggest updating to version 3 of the AWS SDK for PHP as well since many changes have taken place with services (including DynamoDB) that cannot be taken advantage of with such an old version of the SDK.

Please do not hesitate to reach back out to us if you are running into issues specific to the AWS SDK for PHP or problems with the behavior of a given service when using the AWS SDK for PHP.
