### ISSUE TITLE
New new ChimeClient

### ISSUE THREAD

**Issue by aalvarezcoco** [aws/aws-sdk-php#1999]
Confirm by changing [ ] to [x] below:
- [ ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP?**
Example: v3.133.6
* get SDK version by printing the output of `Aws\Sdk::VERSION` in your code 
* if the SDK was installed via composer you can see the version installed with `composer show -i` 

**Version of PHP (`php -v`)?**

**Describe the question**

how to create a new ChimeClient in php to manage aws chime.

when i try it comes out

The chime service does not have version: 2006-03-01

help please

**Comment by diehlaws** [comment]
Hi @aalvarezcoco, thanks for reaching out to us. Where do you see API version `2006-03-01` published for the Amazon Chime API? From what I can see the only service that uses that particular API version is S3. Looking at the [ChimeClient](https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Chime.ChimeClient.html) page of the documentation for the AWS SDK for PHP I only see version `2018-05-01` as currently supported. When initializing a service client within the AWS SDK for PHP you'll want to check the documentation for the service's client within [our docs](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html) to ensure you're using a supported API version for the service in question. 

When writing test code to check whether a given client or call works for a given service you can provide the string `latest` to the “version” configuration value to use the most recent available API version that your installed version of the AWS SDK for PHP can find. Please keep in mind that we do not recommend Using `latest` in a production application because pulling in a new minor version of the SDK that includes an API update could potentially break your production application.

**Comment by aalvarezcoco** [comment]
I have a concern for the administration of user rooms and other things that service chime gives me, can I use the sdk php version 2018-05-01 or must I necessarily use amazon-chime-sdk-js javascript

**Comment by diehlaws** [comment]
@aalvarezcoco Please keep in mind that the API version used for a given service client is not equivalent to the version of the AWS SDK for PHP used within your application. I see you commented on #1100 regarding a `BadRequest` error you received trying to issue a `CreateUser` call, however that issue covers a different behavior (attempting to reach the service via http as opposed to https) so that issue is not related to the behavior you're seeing. Are you able to receive a successful response on a `CreateUser` call using [amazon-chime-sdk-js](https://github.com/aws/amazon-chime-sdk-js)? If so, I would be interested to see what the resultant HTTP request headers and body look like in comparison to the [debug output](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#debug) for the same call using the AWS SDK for PHP.

That being said, I'm able to elicit the same error specifically with the `CreateUser` call using the AWS SDKs for PHP, Go, and Python, as well as the AWS CLI, which seems to indicate an issue with the usage of the service rather than something specific to the AWS SDK for PHP. I am getting successful responses using other calls such as `ListAccounts`, `ListUsers`, `InviteUsers`, and `CreateMeeting` with the SDKs mentioned above so I suspect there may be some undocumented caveats to issuing a `CreateUser` call successfully. Looking through the [Amazon Chime Administration Guide](https://docs.aws.amazon.com/chime/latest/ag/getting-started.html) I'm not seeing any mention of creating a user outright without sending them an invitation (which would be equivalent to an `InviteUsers` call via the AWS SDKs). I also don't see a way to create a new user outright (as opposed to sending an email invite) via the Chime web console, unfortunately I'm not sufficiently familiar with the service to determine whether this should be possible or what the requirements are if it is.

I recommend reaching out to our Premium Support team by creating a [new Technical Support case](https://console.aws.amazon.com/support/home#/case/create) under the Chime service to determine the appropriate usage of this particular API call outside of the context of a specific SDK as they will have a better understanding of how to use the service itself.
