### ISSUE TITLE
Cognito-user-identity-pools "listUsers" Pagination sorting does not support descending sorting order, to reach users which are started from "Z" letter requires paginate through most of the data.

### ISSUE THREAD

**Issue by rimvislt** [aws/aws-sdk-php#2015]
**Is your feature request related to a problem? Please describe.**
https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ListUsers.html

Pagination does not support descending sorting order, to reach users which are started from "Z" letter requires paginate through all data.

Because of the way how pagination is made in AWS SDK, to see anything what is in the end of alphabet requires go through intensive pagination to reach that specific letter or place (waste a lot of computing power and resources).

Since API does not support those features, data duplication by storing it inside database is required, for ability to do pagination/filtering/sorting actions:
* sort  (ASC|DESC)
* multi-filters (only single filter is supported by "listUsers" function)
* pagination to be able to jump to the end of the list or in the page which is in the middle of the list. (if user wants to see the last page or second page from the end).

**Comment by diehlaws** [comment]
Thanks for reaching out to us @rimvislt. Please keep in mind that feature requests submitted here should be for changes specific to the AWS SDK for PHP. Since what you're requesting is a change in how the listUsers API works for the Cognito service, this request would be more appropriate to submit to our Premium Support team via a [new technical support case](https://console.aws.amazon.com/support/home?#/case/create) under the Cognito service and the Feature Request category.
