### ISSUE TITLE
CommandPool unexpected concurrent execution | AWS SES

### ISSUE THREAD

**Issue by shihabislambs** [aws/aws-sdk-php#2049]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP?**
v3.134.6
**Version of PHP (`php -v`)?**
v7.3.11

**Describe the question**

I use the code below to create a single command and run I multiple times to create an array of commands.
```
$command = $client->getCommand('SendRawEmail', array(
   'RawMessage' => array(
      'Data' => $message->toString(),
   ),
));
```

This is how I am executing commands using CommandPool. (This is just a simplified code)

```
$pool = new CommandPool($client, $commands, [
    'concurrency' => 14,
    'fulfilled' => function (ResultInterface $result, $iterKey, PromiseInterface $aggregatePromise) {
        // Do stuff
    },
    'rejected' => function (AwsException $reason, $iterKey, PromiseInterface $aggregatePromise) {
        // Do stuff
    }
]);
```

The `$commands` array contains 2000 commands and the value of `concurrency` is my SES sending limit per second. When I execute this code after a few seconds I get rejection. I don't remember the exact error message but the summary of the massage is: "I have exceeded the sending rate limit". Which basically means I am sending more that 14 request to SES.

What am I missing here? Did I miss understand the purpose of `concurrency`? Is it happening because those 14 requests are completing quickly and triggering another 14 request within one second?

Thank you.

**Comment by diehlaws** [comment]
Thanks for reaching out to us @shihabislambs. The CommandPool will move on to issuing the next command immediately after a previously issued command completes to maintain a constant pool size corresponding to the set `concurrency` value. As a result, your CommandPool is likely sending your `SendRawEmail` commands at a rate faster than 14 requests per second since each command likely takes less than a second to receive a response from SES - you can see how long each request takes to complete by setting `'stats' => true` in your SesClient's config.
You'll want to add a 1 second wait time to your 'fulfilled' function to ensure you don't go over your max send rate in SES when executing the commands in your CommandPool.

**Comment by shihabislambs** [comment]
@diehlaws That is what I suspected. Thank you for your explanation.
