### ISSUE TITLE
Error retrieving credentials from the instance profile metadata server. (Client error: `GET http://169.254.169.254/latest/meta-data/iam/security-credentials/` resulted in a `404 Not Found` 

### ISSUE THREAD

**Issue by Tarequzzaman** [aws/aws-sdk-php#2068]
Hi 
I got this error  while connecting AWS Managed Elasticsearch. But My code does not provide any error on my local environment. I have shared my both environment specification below:

<h3>Local Environment:</h3>

```
Mac OS Catelina

```
AWS CLI version:

```aws-cli/2.0.31 Python/3.7.4 Darwin/19.3.0 botocore/2.0.0dev35
```
aws-php-sdk:
```
"aws/aws-sdk-php": "3.90.6",
```

<h3>Dev Environment:</h3>

```
AWS EC2
Ubuntu 18.04.2 LTS (GNU/Linux 5.3.0-1019-aws x86_64)
```

AWS CLI version:

```
aws-cli/1.18.69 Python/3.6.9 Linux/5.3.0-1019-aws botocore/1.16.19

```
aws-php-sdk:
```
"aws/aws-sdk-php": "3.90.6",
```

I have check the aws credentials both of **local** and **dev** server using `cat ~/.aws/credentials
` and they are the same.

```
[default]
aws_access_key_id =  xxxxxx
aws_secret_access_key = xxxxxxxxxxxx
```

I have added both of my local and dev server public ip on elasticsearch access policy.

Below I have added my PHP code: 

Service class for getting client: 

```Php
  class ElasticSearchService
{
    public function getElasticClient(){
        $provider = CredentialProvider::defaultProvider();
        $handler = new ElasticsearchPhpHandler('ap-southeast-1', $provider);
        $client = ClientBuilder::create()
            ->setHandler($handler)
            ->setHosts(['https://xxxx-xxxxx-xxxxxxxxxxxxxxx.ap-southeast-1.es.amazonaws.com:443'])
            ->build();
        return $client;
    }
}

```

Controller: 

```Php
class SearchController extends Controller
{
 
   public function __construct(ElasticSearchService $elasticSearchService){
       $this->elasticSearchService = $elasticSearchService;
   }

public function  search(Request $request){
   try {
       $client = $this->elasticSearchService->getElasticClient();
       $content = $request->get("body");
         $parms = [
           "index" => "questions",
           "body" => [
               "size" => 5,
               "query" => [
                   "multi_match" => [
                       "fuzziness" => "AUTO",
                       "fields" => ["body"],
                       "query" => $content,
                       "minimum_should_match" => "50%"
                   ]
               ]
           ]
       ];
       $result = $client->search($parms);
       $data = array();
       foreach($result['hits']['hits'] as $d){
           array_push($data, $d["_source"]);
       }
       return MakeResponse::successResponse($data);
   }catch ( \Exception $exception){
       return MakeResponse::errorResponse("Something Went Wrong", $exception->getMessage());
   }
}

```

I got success data on my **local** environment. But on **dev** environment I got error response where the error message is : 

```
Error retrieving credentials from the instance profile metadata server. (Client error: `GET http://169.254.169.254/latest/meta-data/iam/security-credentials/` resulted in a `404 Not Found` response:\n<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n\t\"http://www. (truncated...)\n)

```

Help me find my problem.

**Comment by diehlaws** [comment]
Hi @Tarequzzaman, thanks for reaching out to us. While version 3.90.6 of the AWS SDK for PHP is relatively old and I recommend upgrading to the latest version of the SDK to ensure recent changes in service APIs are supported, there haven't been any significant changes in how the SDK handles credentials from the shared credential file since that version so this shouldn't affect your ability to load the credentials you're trying to use.

Based on the error you're seeing it sounds like the AWS SDK for PHP is not finding a credentials file in the default path within your dev environment so it's continuing down the default provider chain to retrieve instance profile credentials. Is the code in your dev environment being run as the same user that has the `.aws/credentials` file in its home directory? If not, you'll want to ensure this file is present in the correct home directory so the SDK is able to locate and open it. 
Alternately, you can configure an [ini provider](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_provider.html#ini-provider) in place of the default credential provider and specify the absolute path of your credentials file. This of course will require the user running your PHP process to have at least read access to the credentials file.

**Comment by Tarequzzaman** [comment]
Yes The code is running both the same user that has the .aws/credentials file in its home directory. 


BTW the issue is solved using <a href=https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_provider.html>custom provider</a>

Thanks

**Comment by HaidarZ** [comment]
Similar issue here
```
Aws\Exception\CredentialsException: Error retrieving credentials from the instance profile metadata service. (Client error: `GET http://169.254.169.254/latest/meta-data/iam/security-credentials/` resulted in a `404 Not Found` response: <?xml version="1.0" encoding="iso-8859-1"?> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://ww (truncated...) )
```

I've downgraded back to `aws/aws-sdk-php:3.278.1` and everything is normal now.
