### ISSUE TITLE
PHP/Laravel libraries to implement identity and isolation for multi-tenant SaaS solution with Cognito

### ISSUE THREAD

**Issue by nimeth** [aws/aws-sdk-php#2072]
Dear AWS developer team,

We are working on our project building a multi-tenant SaaS of a Suite of HR applications. Throughout my long-time research and understanding for building a multi-tenant SaaS solution on AWS, I'm strongly interested with a reference architecture and application for building identity and isolation for multi-tenant SaaS on AWS as described here [SaaS identity and isolation with Amazon Cognito](https://aws.amazon.com/quickstart/saas/identity-with-cognito/) , [here](https://aws-quickstart.s3.amazonaws.com/saas-identity-cognito/doc/saas-identity-and-isolation-with-cognito-on-the-aws-cloud.pdf ) and also [SaaS on AWS Bootcamp](https://github.com/aws-samples/aws-saas-factory-bootcamp), which I believe a high standard solution for building and managing multi-tenant SaaS on AWS. Anyway, I note that all backend services of the reference application are based on Node.js and the most interesting logic implementations for tenant identity and isolation found in shared modules/libraries directory (config-helper, dynamodb-helper, and token-manager) are all in JavaScript.

Because all developers in my team are coming from PHP/Laravel background and we already started developing a few backend services based on Laravel, I spent a few weeks trying to understand and look for similar examples based on AWS SDK for PHP, but no luck.

Please kindly help to guide me to sample implementations based PHP/Laravel.

Thanks in advance,
Nimeth

**Comment by diehlaws** [comment]
Hi @nimeth, thanks for reaching out to us. Unfortunately to my knowledge we do not have any sample implementations based on PHP of a multi-tenant SaaS application similar to those described in the links you've provided. That said, the API calls made to AWS services should be the same between the AWS SDKs for PHP and Javascript, so the source code for the SaaS implementation quickstart you mention would be a good start to understanding which calls are being made to Cognito in order to achieve the desired results.

Please do feel free to reach out to us if you have any questions regarding the usage of the AWS SDK for PHP including the implementation of specific service calls, if you encounter any unexpected behavior when using the SDK to interact with AWS services, or if you have ideas to implement new functionality within the SDK.
