### ISSUE TITLE
Pre-signed URL using Aws\Signature\SignatureV4 and temp Cognito credentials fails with 403

### ISSUE THREAD

**Issue by CoDanny** [aws/aws-sdk-php#2247]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
When using the class ```Aws\Signature\SignatureV4``` to pre-sign an IoT Core websocket connection or GET shadow request, the request fails with 403 (The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.).

This only happens when using Cognito Identity temporary credentials. Permanent IAM credentials work.

This is due to the following lines https://github.com/aws/aws-sdk-php/blob/d7ad80a9a9c145bc571d106f0fd5629f7c9552e0/src/Signature/SignatureV4.php#L265-L267 which are trying to add the security token header to the pre-signed request. The server seems to want this header added at the end of the pre-sign process. It shouldn't be part of the signature.

**Version of AWS SDK for PHP?**
Example: v3.178.11
* get SDK version by printing the output of `Aws\Sdk::VERSION` in your code 
* if the SDK was installed via composer you can see the version installed with `composer show -i` 

**Version of PHP (`php -v`)?**
php 5.6

**To Reproduce (observed behavior)**
Obtain STS Credentials from a Cognito Identity and use them to generate a websocket connection URL for IoT Core. I have also tried by making a https GET shadow request. Then use that url in javascript with mqtt.js to connect to IoT Core.

**Expected behavior**
The connection succeeds

**Comment by ajredniwja** [comment]
Hi @CoDanny, sorry for delayed response, is this still a persisting issue? I can see [here](https://docs.aws.amazon.com/iot/latest/developerguide/connect-iot-lorawan-network-analyzer-generate-request.html) that the `security-token` header is marked optional so Im not sure if thats what is causing this. I'll discuss it with the team for some more insight.

**Comment by stobrien89** [comment]
Hi @CoDanny,

Apologies for the delayed response here.  In order to determine whether or not this is a bug, I'd need to see how you're generating the presigned url.  

Presigned urls are only _officially_ supported by a few services, so in this case it might be better than you've reimplemented the class— it's possible you're trying to do something that the SDK doesn't officially support.

**Comment by CoDanny** [comment]
Here's my code snippet:
```php
$credentials = new Credentials($idCredentials->accessKey, $idCredentials->secretKey, $idCredentials->sessionToken, $idCredentials->expiration);
$request = new Request("GET", "wss://". $iotConfig->iotEndpoint ."/mqtt");
$signer = new SignatureV4ForIotCore('iotdevicegateway', $this->config->aws->region);
$signed = $signer->presign($request, $credentials, "+5 seconds");
```

I then return the signed url

```php
'connection_url' => (string) $signed->getUri()
```

```SignatureV4ForIotCore``` is a class that extends from ```SignatureV4``` with my fixes.

**Comment by RanVaknin** [comment]
Hi @CoDanny ,

Thanks for your patience. Like @stobrien89 mentioned, not every service supports presigned URLs, therefore the behavior might not be consistent. 
A signature mismatch error happens when the request sent using the presigned URL and the signature on the presignedURL itself do not match. 

One way we can examine such discrepancies is to log the raw request made by whatever http handler you are using to make that request with the presigned URL. 
It would be helpful if you can share that with us, and also the generated presignedURL that you are using to make that request. (Please redact any sensitive info like your AWS access key)

If those 2 are not matching, we might be able to direct you to how you can tweak the request to force it to match.
If those _are_ matching and you are still seeing a mismatch error, then it might point to the fact that the presigning behavior for the IOT service is not fully supported. (will have to get investigated by the AWS service team itself) 

Thanks,
Ran~
