### ISSUE TITLE
S3 MultipartUploader in PHP does not encrypt the file

### ISSUE THREAD

**Issue by zishanj** [aws/aws-sdk-php#2254]
I am trying to use `MultipartUploader` to encrypt the file but unfortunately the file remains unencrypted on S3 storage. I have following implementation:

```
$client = new S3Client([
            'version' => 'latest',
            'region'  => $s3_region,
            'endpoint' => $url_to_endpoint,
            'credentials' => [
                'key'    => S3_KEY,
                'secret' => S3_SECRET,
            ],
        ]);
$args = [
            'Bucket' => 'webstorage',
            'Key' => $filename,
            'SSECustomerKey' => $my_32_chars_key,
            'SSECustomerAlgorithm' => 'AES256'
        ];
// Prepare the upload parameters.
$uploader = new MultipartUploader( $client, $source, $args );

// Perform the upload.
try {
            $result = $uploader->upload();
            print_r($result);
} catch ( MultipartUploadException $e ) {
            echo $e->getMessage();
}
```
If I use S3 `putObject` then it encrypt and upload the file with following additional args in above:
```
$args['SourceFile'] = $source;
$args['Content-Length'] = filesize( $source );
```
Is it a bug in `MultipartUploader` or I am doing something wrong?

**Comment by SamRemis** [comment]
Hi @zishanj,
You appear to be trying to use server side encryption to encrypt a file using the uploader.  Looking at the documentation, the correct way to do this isn't as clear as it should be.  Since the multipart uploader is a wrapper around multiple commands, we have a specific parameter to use to pass parameters to those upload part commands: 'params'.  

Please try changing your args to look like this, and let me know if that works for you:
```
$args = [
            'Bucket' => 'webstorage',
            'Key' => $filename,
            'params' => [
                  'SSECustomerKey' => $my_32_chars_key,
                  'SSECustomerAlgorithm' => 'AES256'
            ]
        ];
```

**Comment by zishanj** [comment]
Thanks @SamRemis! This has worked very well. But I wonder why it didn't returned `x-amz-server-side-encryption-customer-algorithm` and `x-amz-server-side-encryption-customer-key-md5` in header like it appears in `putObject`. Files got encrypted though.

**Comment by SamRemis** [comment]
That's great to hear!  I'd have to look into it more to give you a definitive answer as to why, but when you call a multipart upload, the SDK winds up calling a series of operations: createMultipartUpload, uploadPart, and completeMultipartUpload.  If you want more granular control and to get those headers, you can print them out using a callback as some of the after_* parameters.   
Hope this helped :) closing the issue since it appears to have been solved
