### ISSUE TITLE
All clients should implement interfaces to make for easier testing

### ISSUE THREAD

**Issue by toddlang** [aws/aws-sdk-php#2267]
All of the client objects should implement interfaces to make mocking and unit testing easier.  This is _partially_ done in the API.  For example, the S3Client implements S3ClientInterface.  However, DynamoDbClient does not implement a suitable interface.

**Describe the solution you'd like**
Define interfaces for all clients and have them implement them, consistent with S3Client.

**Comment by SamRemis** [comment]
Hi there @toddlang,
The reason that this doesn't exist already has to do with how the SDK works.  If you look at _almost_ any client, they don't have any methods implemented in them; instead the calls all happen based on data provided to us by the service itself.  The reason that S3 has an interface is because we have some custom S3 clients that add logic and were hand written like S3EncryptionClientV2.  

Having an interface that they implement would be redundant.  I'm not sure exactly how you are trying to mock and unit test them, but all clients do extend AwsClient; could you use that?

**Comment by toddlang** [comment]
Our attempt is to implement and enforce strict typing throughout the entire project.  We could make exceptions for the clients if the difficulty in making the strong typing outweighs the benefits of strict unit testing, I suppose?

Obviously I'm not in a position to tell you how to design your APIs - I just appreciate the work you do for us.  I would suspect fast, accurate feature implementation likely outweighs most other considerations.

**Comment by SamRemis** [comment]
I agree this is a good idea; it would add a good bit of data to the package, which is already a problem for us.  I plan on fixing that in the next major version of the SDK, and will do my best to implement this then :) thank you for the suggestion!

I've added it to the document that we are using to design the next version
