### ISSUE TITLE
open_basedir is not within the allowed path(s)

### ISSUE THREAD

**Issue by ljay88** [aws/aws-sdk-php#2303]
Warning: is_readable(): open_basedir restriction in effect. File(/home/www/.aws/config) is not within the allowed path(s): (/www/wwwroot/test/:/tmp/) in /www/wwwroot/test/vendor/aws/aws-sdk-php/src/Retry/ConfigurationProvider.php on line 158

Warning: is_readable(): open_basedir restriction in effect. File(/home/www/.aws/config) is not within the allowed path(s): (/www/wwwroot/test/:/tmp/) in /www/wwwroot/test/vendor/aws/aws-sdk-php/src/S3/UseArnRegion/ConfigurationProvider.php on line 134

Adding the following configuration does not work 

'csm' =>false,

**Comment by SamRemis** [comment]
Hi @ljay88,

I could use a little more context here.  I see the lines that you're referencing, but what code of yours is calling the lines.  Can you provide me with some code that I can use to reproduce the issue so that I can confirm it's fixed once I've patched it?

**Comment by ljay88** [comment]
date_default_timezone_set('PRC');
require __DIR__ . '/vendor/autoload.php';

$s3 = new Aws\S3\S3Client([
    'version' => 'latest',
    'region' => 'us-east-1',
    'csm' =>false,
    'endpoint' => 'http://192.168.3.10:9000',
    'use_path_style_endpoint' => true,
    'credentials' => [
        'key' => 'usertest',
        'secret' => 'usertest888'
    ]
]);

$command = $s3->getCommand('GetObject', [
    'Bucket' => 'test',
    'Key'    => 'test.jpg'
]);

**Comment by SamRemis** [comment]
try setting 'use_aws_shared_config_files' => false in the client, it should skip checking those config files you don't have access to.  

$s3 = new Aws\S3\S3Client([
'version' => 'latest',
'region' => 'us-east-1',
'csm' =>false,
'endpoint' => 'http://192.168.3.10:9000',
'use_path_style_endpoint' => true,
'use_aws_shared_config_files' => true,
'credentials' => [
'key' => [redacted],
'secret' => [redacted]
]
]);

**Comment by ljay88** [comment]
Thank you very much, I will try

**Comment by SamRemis** [comment]
@ljay88 Thank you :) please let us know if this doesn't work, or if it does close the issue (or let me know so that I can)

**Comment by ljay88** [comment]
Thank you very much, it works normally

**Comment by JorisDebonnet** [comment]
@SamRemis, I had this problem too, and found this page when searching. I would like to request reopening this issue.

Reasoning: it's not considered "nice" to require users to circumvent an issue by adding extra configuration. A "nicer" solution would be if this package just had a more graceful handling of this situation.

I believe the fix is straightforward: just wrap these particular `is_readable` calls in try/catch (and make it return 'false' in the catch). After all, everything still works perfectly fine if `is_readable` does not return true, so there isn't really a reason to 'bother' the developer about it :D

**Comment by SamRemis** [comment]
@JorisDebonnet That's true, and a feature request.  I have to think about if this is potentially breaking change for anyone, but off the top of my head, I don't see a reason that a user would be relying on this particular failure.  

I will re-open this and add the feature request label to it, and chat with the team to make sure that I'm not missing anything where a customer could be relying on the current behavior

**Comment by SamRemis** [comment]
@JorisDebonnet We did, and it should be fine to implement; I'm just formalizing it now to get final approval/confirmation.  There's still a chance that it will get denied, but I'd be surprised.  Thank you for following up :) 
Just to confirm, this is just a warning for you, right?  This is not stopping code execution like an error would?

**Comment by JorisDebonnet** [comment]
> Just to confirm, this is just a warning for you, right? This is not stopping code execution like an error would?

That is correct, everything is still functional. I'm just trying to clean up our error logs (which include these warnings) 🙂

**Comment by sbergmann95** [comment]
+1 for graceful handling of this, also trying to clean up error logs with all the warnings that are being spammed with every call to aws (we have lot's of calls to aws for encryption / decryption so the error logs get quite noisy)

**Comment by SamRemis** [comment]
So this should be fixed by https://github.com/aws/aws-sdk-php/pull/2359, I still need to do a bit more testing to confirm for sure.  
This shouldn't be a try/catch loop since it's not an exception though; it should be an @ suppression.  I did look through the code, and couldn't find any reason that `use_aws_shared_config_files=false` wouldn't be working, @JorisDebonnet, could you please show me your client constructor and tell me what version of the SDK you're on.  Also, what OS are you running the code on?

**Comment by JorisDebonnet** [comment]
@SamRemis #2359 looks great! 

`use_aws_shared_config_files=false` not working may have been due to using an old version of the sdk. On one of my projects, I had limited the SDK to 3.174.* to avoid some issue, but I don't remember which ... So I have ensured to be using the most recent version now, and assume that this will make `use_aws_shared_config_files=false` work.

**Comment by mmoorree4444** [comment]
@SamRemis  I am having the same issue with php 7.4 and sdk version 3.209. I am using the AWS Linux 2 AMI 

use Aws\S3\S3Client;

$s3 = new S3Client([
'version' => 'latest',
'region'  => 'us-east-1',
'use_aws_shared_config_files' => false,
]);

**Comment by SamRemis** [comment]
Sorry for the delay, https://github.com/aws/aws-sdk-php/pull/2359 was just merged

**Comment by SamRemis** [comment]
If you installed via composer, this should go out with the tagged release on Monday around 2pm EST :)
