### ISSUE TITLE
Please Update guzzlehttp/psr7 ^2.0.0 

### ISSUE THREAD

**Issue by pgartin** [aws/aws-sdk-php#2329]
Hey this old version of guzzlehttp/psr7 is holding me back please update to the latest if possible.

Thanks

**Comment by SamRemis** [comment]
This is close to ready, but there were a number of changes that were implemented in the latest version that will cause features in the SDK to break.  This is being addressed in [this PR](https://github.com/aws/aws-sdk-php/pull/2276).  The PR should be done, but needs more testing prior to merging

Closing because this is a duplicate issue

**Comment by SamRemis** [comment]
https://github.com/aws/aws-sdk-php/issues/2264
