### ISSUE TITLE
[Amazon connect] Cannot update language ja-JP in Contact Recording Behavior Flow language

### ISSUE THREAD

**Issue by VietTomosia2509** [aws/aws-sdk-php#2330]
When i update action UpdateContactRecordingBehavior in contact flow with AnalyticsLanguage ja-JP using AWS SDK for PHP 3.x
https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-connect-2017-08-08.html#updatecontactflowcontent
https://docs.aws.amazon.com/connect/latest/adminguide/contact-actions-updatecontactrecordingbehavior.html

I want to update AnalyticsLanguage = ja-JP
I received an error that the language is invalid while i was able to update ja-JP on Amazon Connect console, for en-US it works fine

i'm in tokyo region, in this region has support japanese language for amazon contact lens

This is my contact flow content:

```
{
  "Identifier":"2853760c-5563-41e9-bbe0-ed76b97f0f76",
  "Type":"UpdateContactRecordingBehavior",
  "Transitions":{
    "NextAction":"70dfb051-7f6a-4609-b973-61df6256f59b",
    "Errors":[],
    "Conditions":[]
  },
  "Parameters":{
    "RecordingBehavior":{
      "RecordedParticipants":[
        "Agent",
        "Customer"
      ]
    },
    "AnalyticsBehavior":{
      "Enabled":"True",
      "AnalyticsMode":"RealTime",
      "AnalyticsLanguage":"ja-JP",
      "AnalyticsRedactionBehavior":"Disabled",
      "AnalyticsRedactionResults":"None"
    }
  }
}
```

Error: 
```
{"Problems":[{"Message":"Invalid Action property value. Path: Actions[7].Parameters.AnalyticsBehavior.AnalyticsLanguage" (truncated...)
 InvalidContactFlowException (client):  - {"Problems":[{"Message":"Invalid Action property value. Path: Actions[7].Parameters.AnalyticsBehavior.AnalyticsLanguage"}],"Message":null}
```

**Comment by SamRemis** [comment]
@VietTomosia2509 My apologies, I'm not totally sure what you're trying to do here.  Is that string that you're sending what you're using as the input to the 'Content' parameter?  

Do you mind showing me a bit of the PHP code surrounding the JSON that you posted so that I can determine if this issue is service side or SDK side.  Looking at the response that you're getting, that's not a PHP error, it's in JSON.  Was that wrapped in a ConnectException?

**Comment by VietTomosia2509** [comment]
@SamRemis sorry for my presentation
<img width="801" alt="Screen Shot 2021-10-08 at 13 16 08" src="https://user-images.githubusercontent.com/76545419/136507481-30134700-719f-432d-bb1d-f587807b39bf.png">

i want to update language to japanese using Aws sdk for PHP. However when I set the language in ja-JP I get an invalid error

```
// Update contact flow content to aws
$this->awsConnect->updateContactFlowContent([
    'ContactFlowId' => $contactFlow->aws_contact_flow_id,
    'InstanceId' => $this->instanceId,
    'Content' => $params['content']
]);
```

I created the 'Content' following the Flow Language guide
https://docs.aws.amazon.com/connect/latest/adminguide/flow-language.html

I know the problem is on the SDK side because if I set the language as en-US it works `AnalyticsLanguage: 'en-US'`

**Comment by SamRemis** [comment]
That suggests the issue is more likely service side because if we are properly sending en-US, we are probably properly sending ja-JP as well and they're rejecting it for some reason on their side.  I looked at the service model, and there are no validations on the 'Content' parameter that would cause the SDK to remove the parameter.  I would guess that other SDKs would have the same issue. 

I was also unable to find a list of supported languages- I trust that this is supported though because of the screenshot above.  I will contact the team and see if they have any idea why this might be happening and get back to you ASAP

**Comment by stobrien89** [comment]
Hi @VietTomosia2509,

Can you confirm whether or not this is still an issue after a version bump? Thanks!
