### ISSUE TITLE
Call to undefined function Aws\is_fips_pseudo_region

### ISSUE THREAD

**Issue by dmitryvasilevskiy** [aws/aws-sdk-php#2350]
v3.202.2 
php 8.0.9 
get error
Call to undefined function Aws\is_fips_pseudo_region

but local php 8.0.1 local work success 

I needed aws/aws-sdk-php (3.202.2 => 3.199.1)

**Comment by SamRemis** [comment]
@dmitryvasilevskiy Can you give me more info to reproduce the issue?  This function is called in three different locations, so it would be useful to have a stack trace to figure out where this issue is happening and to know how you called it.  
This function was added and used in the same PR, so is it possible you have multiple versions of the SDK installed and you have to update both?

**Comment by dmitryvasilevskiy** [comment]
I dont want repeat on production, we need hard set 3.199.1 and we dont get the error. 
Local machine same params well work, but production got the error.....

**Comment by SamRemis** [comment]
Chances are you have two separate installs of it in production, or for some reason the files didn't update at the same time

**Comment by jackkitley** [comment]
Same error with me 
PHP 7.4.3 (cli) (built: Oct 25 2021 18:20:54) ( NTS )

"aws/aws-sdk-php": "^3.185",

Error: Call to undefined function Aws\is_fips_pseudo_region() in /vendor/aws/aws-sdk-php/src/Endpoint/UseFipsEndpoint/ConfigurationProvider.php:169
Stack trace:

**Comment by SRangaReddy** [comment]
Same error with me
PHP 7.3.27-9+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb 23 2021 15:09:46) ( NTS )

"aws/aws-sdk-php": "^3.204"

 Uncaught Error: Call to undefined function Aws\is_fips_pseudo_region() in /vendor/aws/aws-sdk-php/src/Endpoint/UseFipsEndpoint/ConfigurationProvider.php:169

**Comment by SamRemis** [comment]
@jackkitley Thank you :) I can push out a stopgap fix today as I investigate where this issue came from

**Comment by SamRemis** [comment]
More of a stack trace would help me figure out the initial bug as well, if you don't mind posting the next few lines

**Comment by jackkitley** [comment]
@SamRemis 
`Error: Call to undefined function Aws\is_fips_pseudo_region() in /var/www/html/projectname/vendor/aws/aws-sdk-php/src/Endpoint/UseFipsEndpoint/ConfigurationProvider.php:169
Stack trace:
#0 /var/www/html/projectname/vendor/guzzlehttp/promises/src/Promise.php(204): Aws\Endpoint\UseFipsEndpoint\ConfigurationProvider::Aws\Endpoint\UseFipsEndpoint\{closure}()
#1 /var/www/html/projectname/vendor/guzzlehttp/promises/src/Promise.php(169): GuzzleHttp\Promise\Promise::callHandler()
#2 /var/www/html/projectname/vendor/guzzlehttp/promises/src/RejectedPromise.php(42): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()`

**Comment by jackkitley** [comment]
Not working:

        "aws/aws-sdk-php": "^3.185",
        "guzzlehttp/guzzle": "^7.3",

Working:

    "aws/aws-sdk-php": "^3.173",
    "guzzlehttp/guzzle": "6.3.3"

**Comment by segurirangareddy** [comment]
@SamRemis  I had the same issue this morning, Later realised that the project has this sdk installed in two different locations, Uninstalling it from one location fixed the issue.

**Comment by SamRemis** [comment]
@segurirangareddy Thank you so much for the update, that's my suspicion about what's going wrong for everyone on here; there's no reason that function call shouldn't work in that context.  Still, I'd rather be safe than sorry while I investigate more. 
It's really nice to hear from customers like you who help me know when the issue occurs, so it makes it far easier to fix

**Comment by jackkitley** [comment]
@SamRemis how does one install multiple times? mine is direct from composer and then used with php application. 
Thanks.

**Comment by SamRemis** [comment]
@jackkitley that's odd, considering this function wasn't even introduced until 3.200.1.  Since that call has to be coming from somewhere, I'm guessing you do have a second version installed somewhere.

As for where or how, I am not sure.  I only suspected that since I had a similar issue come up for another customer before.  I haven't been able to replicate the issue locally either.  If you find out, I'd love to know so I can test against it in the future.  

One more question- did you test against 3.185 again after switching to 3.173?  I'm wondering if both of your installs got updated when you switched, so it would still work if you switched back?  Or even if you switched to the current version?  I can't think of any reason that 3.173 would be fine, but 3.185 wouldn't.

**Comment by jrm0695** [comment]
Same issue here. Downgrading to 3.173

**Comment by SamRemis** [comment]
@jrm0695 which version were you on before?

**Comment by andreypopov** [comment]
+1
 Downgrading to 3.173

**Comment by jackkitley** [comment]
Just an update. Did composer update and using the following now:

`        "aws/aws-sdk-php": "^3.185",
        "guzzlehttp/guzzle": "^7.3",`

This works

**Comment by jackkitley** [comment]
Mine is suddenly working with the new versions as i used previously. Not sure what it was.
        "aws/aws-sdk-php": "^3.185",
        "guzzlehttp/guzzle": "^7.3",

**Comment by SamRemis** [comment]
https://github.com/aws/aws-sdk-php/pull/2351 should have fixed this; I can't be sure since I couldn't reproduce the issue, but I've eliminated the method call
