### ISSUE TITLE
Random AWS HTTP error: cURL error 7

### ISSUE THREAD

**Issue by mrbinr** [aws/aws-sdk-php#2357]
PHP version 7.2
"aws/aws-sdk-php": "^3.132.4"

I've have a strange behavour in my project, randomly this error appears and I've not find how and why ...

`
Error executing "PutObjects" on ...; AWS HTTP error: cURL error 7:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
`

I've seen in some other forum that people add same issue but without any answers.
The really strange fact it is that something it works and sometimes not ...
Most of time it is not working I think it is 20% working ...

This behavior is going to make me crazy 🤣

Any idea ?

Thanks for your help
Pascall

**Comment by mrbinr** [comment]
Hi 
I have added debug to the connection and I have this error

`connect to xxx.xxx.xxx.xxx port 443 failed: Connection refused`

The IP is AWS IP

**Comment by mrbinr** [comment]
I have updated my code with S3Exception catching in order to make several attempts and after 4 attempts it finally does the upload.
I have also add a sleep between getCommand and execute and it works too.

Really frustrating ...

**Comment by mrbinr** [comment]
Hum...
I have noticed a strange thing ..
In fact it seems that between the instantiation of the client and the possibility of doing any action I have to wait several seconds otherwise the error occur.
It is not only putObject but everything like create a waiter or delete a file ....
Really strange...

**Comment by mrbinr** [comment]
so last try,
i have add 
```
    'retries' => [
        'mode' => 'standard,
        'max_attempts' => 7
    ],
```

and it works every time ...
but still weird for me ...

**Comment by mrbinr** [comment]
So i have add 
```
$client = new S3Client([
...
            'retries' => [
                'mode' => 'legacy',
                'max_attempts' => 10,
            ]
...
]);
```

and it looks working more often, but it still sounds weird for me ...

**Comment by SamRemis** [comment]
Hi ther @mrbinr, thanks for opening the issue.  The reason that you didn't find an answer when looking at the issue is that it's a very generic error thrown by the library underlying the SDK; each cause will be different.  It's odd that it's failing in the way it is; I've got a few questions around it:

1. What method are you using to provide credentials to the SDK?  Is it coming from a shared aws file like '.aws/credentials', or is it coming from the constructor?  Somewhere else?  And are you sure that you're always getting the same exact credentials and nothing is changing between the calls?
2. Legacy is the default, you don't have to set it to legacy, you could have just used `'retries' => 10` to accomplish the same thing,  but that's not a big deal.  I prefer standard mode myself, so mostly out of curiosity I was wondering if you'd tried standard mode
3. Is this command always on the same bucket, and does the account you're using always have access to the buckets that it is trying to call?  I assume yes since you're succeeding on retries, but never hurts to check.  
4. Where is this code running?  Is it on an EC2 instance?  Some other server?  I'm wondering if there could be a firewall or something blocking you.  Running [these checks](https://aws.amazon.com/premiumsupport/knowledge-center/s3-could-not-connect-endpoint-url/) on the server may help:  


There's so many issues that can cause a connection to be refused; it's hard to say exactly what the root cause is, so I'm sorry I can't be more specific just yet

**Comment by mrbinr** [comment]
@SamRemis thanks for you answer.
About point 1:
About the method that I use to provide credientials, I have tried with .aws or using array containing credentials and Aws\Credential. But I know this it is a really problem with this, otherwise the problem will not appears randomly.

About point 2:
In fact, no i've not tried standard mode, but i will.

About point 3:
Yes for the moment i've only use a same bucket for the development.

About point 4: 
For the running code, for the moment it is in development so it is on my computer and I will try it soon on a server.


Thanks again to have take on your time to give me some answers.

Best Regards
Pascall

**Comment by SamRemis** [comment]
One other thing I noticed- you're using version 3.132, which is almost two years old.  If you update it, does the issue still occur?  There may have been some changes to the signing code that would have fixed the issue by now.
