### ISSUE TITLE
Uncaught Error: Class 'AwsEndpointUseFipsEndpointConfigurationProvider' not found

### ISSUE THREAD

**Issue by RaviJayagopal** [aws/aws-sdk-php#2363]
Error shown in server logs:

Uncaught Error: Class 'AwsEndpointUseFipsEndpointConfigurationProvider' not found in <path>/vendor/aws/aws-sdk-php/src/ClientResolver.php:1921

**Version of AWS SDK for PHP?**
v3.208.5

**Version of PHP (`php -v`)?**
PHP 7.4.26

Thanks!

**Comment by SamRemis** [comment]
Hi @RaviJayagopal, I've seen similar issues before to this one, and it is usually caused by someone somehow having duplicate installs on their system in one way or another.  Since I haven't been able to reproduce it this far, I couldn't tell you for sure how to check if you are impacted by the same issue.

A few things about this error strike me as odd though- first of all, ClientResolver.php is only 1008 lines at the moment, so I'm not sure why you'd be getting an error on line 1921.  The other thing is that there should be slashes there- Aws/Endpoint/UseFipsEndpoint/ConfigurationProvider.  This all leads me to think something may be up with your install, could you tell me how you've installed the SDK so I can try to replicate?

**Comment by RaviJayagopal** [comment]
@SamRemis , thank you for your response. Looks like some issue occurred with Composer when updating the files. This seems to be resolved for now after I manually downloaded the sdk and unzipped and overwrote the files. 

BTW, the wrong line number was due to FTP adding double-spacing to text.
