### ISSUE TITLE
Payload content length is required and can not be calculated

### ISSUE THREAD

**Issue by dividerbeam** [aws/aws-sdk-php#2398]
hello, i have a question with this error:

`Fatal error: Uncaught Aws\Exception\IncalculablePayloadException: Payload content length is required and can not be calculated. in /var/www/php/vendor/S3/aws/aws-sdk-php/src/StreamRequestPayloadMiddleware.php:71`

while i try to put in minio generated image, minio ask content-length and i add it to image headers, but minio still gives an error

here is the picture I'm trying to add to minio:
|
https://vhst.ru/apps/Qr/chillerlan/php-qrcode/examples/image_copy.png

**Comment by SamRemis** [comment]
Hi there @dividerbeam,
Is it possible that your image is corrupt?  When I click the link, it tells me that the image can't be displayed because it contains errors.  That would explain why the body is unable to be calculated.  
Also, how are you adding the content_length header?  If you're adding it after StreamRequestPayloadMiddleware (in the sign step), then this will error out.  You want to make sure the header you're setting is `content-length`

**Comment by Vijaypatel9876** [comment]
getting same errror

**Comment by SadamWebDeveloper** [comment]
May 9: I am also facing with the same error

**Comment by yenfryherrerafeliz** [comment]
Hi @SadamWebDeveloper, would you please be able to open a new issue and provide more details regarding the issue you are getting, including a sample and reproducible code that helps us investigate this better?

Thanks!
