### ISSUE TITLE
GetObject with SaveAs option creating file when object does not exist in S3 bucket

### ISSUE THREAD

**Issue by adrianbecker013** [aws/aws-sdk-php#2408]
We are using the following PHP code to download files from AWS S3 bucket to our local system.
```
try {
    $this->storage->getObject(array(
        'Bucket'    => $this->CloudBucket,
        'Key'       => $objectKey,
        'SaveAs'    => 'temp/file.csv.gpg'
    ));
} catch (\Aws\S3\Exception\S3Exception $e) {
    return $e;
}
```
Any idea why this file is creating "temp/file.csv.gpg" with below content when downloading the file but that object does not exist in S3 bucket.
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>temp/file.csv.gpg</Key><RequestId>12345678</RequestId></Error>
```
Can we download those object files which object exist in S3 bucket? and how we can prevent it?

We are using following resources:-
- PHP 7.2
- aws/aws-sdk-php: 2.* (Also checked it with aws/aws-sdk-php: 3.* but still it is creating file).

Thanks in advance!

**Comment by SamRemis** [comment]
Hi there @adrianbecker013,

This is the expected behavior; the key `$objectKey` in `$this->CloudBucket` doesn't exist; if you're asking about how to do it without creating the file on a miss, there's a few ways. I'm making an assumption here that you're only using relatively small files that don't need `MultiPart` operations based on your current code;

First off, you can just manually delete that file in your catch statement.  This is probably the easiest way and doesn't involve making more calls to S3.  

```
try {
    $bucket = 'remiss-us-east-1';
    $key = 'nonexistantkey';
    $result = $s3client->getObject(array(
        'Bucket'    => $bucket,
        'Key'       => $key,
        'SaveAs'    => './abcde.txt'
    ));
    echo $result;
} catch (\Aws\S3\Exception\S3Exception $e) {
    unlink('./abcde.txt');
    return $e;
}

```

You can also do it by calling `doesObjectExist` first and only making the `getObject` call if the object exists.  
```
   if ($s3client->doesObjectExist($bucket, $key)) {
        $result = $s3client->getObject(array(
            'Bucket'    => $bucket,
            'Key'       => $key,
            'SaveAs'    => './abcde.txt'
        ));
    }
```

**Comment by SamRemis** [comment]
If you're just asking why this is the behavior, the `SaveAs` parameter maps to Guzzle's `sink` parameter; the output of the call is saved to that file before the results are returned to the SDK.
