### ISSUE TITLE
retrying in InstanceProfileProvider not working as expected?

### ISSUE THREAD

**Issue by umesecke** [aws/aws-sdk-php#2484]
### Describe the bug

I'm trying to understand how retrying works in the InstanceProfileProvider. As far as I understand the code, there are three requests necessary to acquire the credentials:
* retrieve a token
* retrieve the profile
* retrieve credentials

In each step there is a check whether the failed request is retryable which boils down to a number of conditions and a final check whether the number of attempts already done is higher than the retry limit.

What I'm missing is how this attempt counter actually works as it is only increased but never resets. Which looks to me as attempts from earlier requests are counted towards later requests.

### Expected Behavior

I'd expect the attempt-counter to be reset before each new "request stage" (meaning after retrieving a token we should reset to 0 before trying to retrieve the profile), so a retried attempt in one request stage does not affect the number of retries available for the subsequent request stages.

### Current Behavior

Right now the attempt counter is never reset after initializing in the constructor. So after a full "run" (retrieving a token, then the profile and the credentials) the counter will be at least 3 and will prevent any retries in later calls (3 retries is the default).

This prevents the provider from retrieving credentials if the instance profile metadata server has availability problems that could easily be retried like the following error (which I think comes from the "retrieve profile" request):

```
Error retrieving credentials from the instance profile metadata service. (Server error: `GET http://169.254.169.254/latest/meta-data/iam/security-credentials/` resulted in a `503 Service Unavailable` response:
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		 "http://ww (truncated...)
)
```

### Reproduction Steps

I have no steps to reproduce right now as I just tried to understand how we are still getting the usual credential exceptions from the instance profile metadata service which I would expect the SDK should retry automatically.

### Possible Solution

The attempt-counter should be reset to 0 before each request stage, possibly before or after each while loop in the `__invoke()` method.

### SDK version used

3.222.19, but also in master

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.1.6 (cli) (built: May 17 2022 16:48:09) (NTS), Ubuntu 20.04

**Comment by yenfryherrerafeliz** [comment]
Hi @umesecke, thanks for opening this issue. After looking into this, I foudn that the reason why we do not reset the attempt-counter is because  a new object is created every time the SDKs tries to load the credentials using the instance profile provider. You could confirm that [here](https://github.com/aws/aws-sdk-php/blob/142a872fd7172bf5d067f4e30e4f89593296fc8f/src/Credentials/CredentialProvider.php#L316). 

Please let me know if that clarify your doubts, or if you have any questions just let me know.

Thanks!

**Comment by stobrien89** [comment]
Hi @umesecke,

Thanks again for reporting this.  This is something I noticed when working on https://github.com/aws/aws-sdk-php/pull/2396.  

I don't think we'd want to reset the attempts prior to each request 'stage'—basically we want imds requests to fail fast in cases where future attempts will be unlikely to suceeded and reduce the likelyhood of throttling errors— but I think we'll definitely want to look at initializing the attempts value each time the provider is invoked rather than in the constructor.  In both the case you highlighted and in the case of the (memoized) default chain, the same provider instance will be re-used when an attempt to refresh credentials is made.

**Comment by stobrien89** [comment]
Fixed by https://github.com/aws/aws-sdk-php/pull/2498
