### ISSUE TITLE
3.239.0 break

### ISSUE THREAD

**Issue by MrJuliuss** [aws/aws-sdk-php#2541]
### Describe the bug

Hi,

With the last release 3.239.0, the package seems to be broken. 

### Expected Behavior

No error

### Current Behavior

```
[2022-10-19 09:56:49] local.ERROR: Error retrieving credentials from the instance profile metadata service. (cURL error 28: Connection timed out after 1001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://169.254.169.254/latest/meta-data/iam/security-credentials/) {"exception":"[object] (Aws\\Exception\\CredentialsException(code: 0): Error retrieving credentials from the instance profile metadata service. (cURL error 28: Connection timed out after 1001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://169.254.169.254/latest/meta-data/iam/security-credentials/) at /var/www/web/apps/shop_website/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php:264)
[stacktrace]
```

### Reproduction Steps

We just upgrade our projet with the last version of sdk (we use a minio system for aws)

### Possible Solution

A rollback to `[3.238.6](https://github.com/aws/aws-sdk-php/releases/tag/3.238.6)` fix the problem. 

### SDK version used

3.239.0

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.1

**Comment by yenfryherrerafeliz** [comment]
Hi @MrJuliuss, thanks for opening this issue. I will investigate what could be changed for this behavior to happen, however, I know that if you are using container on top of a ec2 instance, then you need to increase the hop limit from 1 to at least 2+, otherwise when requesting credentials from the containerized app to the IMDSv2 you will get a timeout. The explanation for this is that ec2 instances use IMDSv2 by default, since it improved some security aspects that you can find information about [here](https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/); Basically, first you can review here how IMDSv2 works [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html), and you will find that you need to create a session token using a put request to the specific imds endpoint for this, but if you have just one hop limit set, that means you have just one channel to do this request and is already used by the ec2 instance itself, which means that you if you are using container or virtualization, etc, on top of the ec2 instance, then you need to set an appropriated value for hop limit that aligns with you have in place.

So, if I guessed that you are using container, you can increase the hop limit by doing the following:
Note: I assumed you have aws cli installed.
```console
aws ec2 modify-instance-metadata-options
        --instance-id YOUR-INSTANCE-ID \
    --http-put-response-hop-limit 2
 ```
 The number I set was 2, but feel free to set this to a value that fit your needs.
 
 Thanks!

**Comment by yenfryherrerafeliz** [comment]
@MrJuliuss could you also please let me know which type of credentials provider are you using?

Thanks!

**Comment by MrJuliuss** [comment]
We are using the sdk with a minio server instance (selfhosted). 

This error occus on list bucket call : 

```
        $sdk = new Sdk($s3Config);

        $s3Client = $sdk->createS3();
        $buckets = $s3Client->listBuckets();
```

**Comment by SamRemis** [comment]
Hi there @MrJuliuss,
I'm interested to see if this broke for anyone else.  We didn't make any code changes in 3.290.0 that would impact the credential provider, which is where you're seeing this break.  It's fairly early on in the logic flow of the SDK, so I wouldn't expect it to break easily.  Could you try upgrading again and telling me if the issue persists?  

Assuming it does-  how are you supplying the credentials?  The error you're seeing is what happens when all of the credentials providers fail.  It's hard to debug this at all without knowing which part of the credential provider chain is broken, so were you doing it through environment variables?   Are relying on an assumed role?  Any additional info you could provide about how you're authenticating would be helpful.

Thank you,
-Sam

**Comment by stobrien89** [comment]
Hi @MrJuliuss,

Closing this for now.  Let us know if you're still having issues!
