### ISSUE TITLE
listObjectsV2 returns different structure between v3.242.1 … v3.243.0

### ISSUE THREAD

**Issue by leevigraham** [aws/aws-sdk-php#2559]
### Describe the bug

Run the following php code

```php
$command = $client->getCommand(
    'ListObjectsV2',
    [
        'Bucket'  => $bucket,
        'Prefix'  => $prefix,
        'MaxKeys' => 1,
    ]
);

$result = $client->executeCommand($command);
```

### Expected Behavior

`v3.242.1` does not include `contents`

![Screen Shot 2022-11-15 at 3 40 49 pm](https://user-images.githubusercontent.com/25124/201831130-f7f7a25e-bb5c-4a9f-a5d7-56dd54ee66fa.png)

`3.243.0` does include `contents` with size: 0

![Screen Shot 2022-11-15 at 3 40 11 pm](https://user-images.githubusercontent.com/25124/201831151-c26ad376-cc65-4ddd-a0c9-83d2978cf8b8.png)

### Current Behavior

See Expected Behavior

### Reproduction Steps

See "Describe the bug"

### Additional Information/Context

This causes issues downstream in thephpleague/flysystem: https://github.com/thephpleague/flysystem/blob/3.x/src/AwsS3V3/AwsS3V3Adapter.php#L132

### SDK version used

3.243.0

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

php 8.1

**Comment by i-just** [comment]
I believe this is happening because of ill-formatted endpoint URL. You can see it in the `$results` if you follow @leevigraham's steps. 

On v3.242.1 `src/AwsS3Adapter.php->doesDirectoryExist()`, the `$result` > `@metadata` > `effectiveUri` is correctly encoded, on v3.243.0 and v3.243.1 it's not. It causes the v3.243.1 `doesDirectoryExist()` to check if there's any directory in the bucket you're searching through, ignoring the `prefix` param.

v3.242.1: `https://s3.amazonaws.com/<bucket_name>?list-type=2&prefix=300C.png%2F&max-keys=1`
v3.243.0, v3.243.1: `https://s3.amazonaws.com/<bucket_name>?list-type=2%3Dprefix=300C.png%2F&max-keys=1`

**Comment by lro-tiierisch** [comment]
Hey, I just created a new PHP project on my local machine and installed the AWS PHP SDK because I had to look up some files in our companies S3 storage. After getting some unexpected results I also noticed that the Prefix parameter seems to be ignored in v3.243.

**Comment by stobrien89** [comment]
Hi all,

I've created a PR which addresses both this issue and https://github.com/aws/aws-sdk-php/issues/2558. We should have a release cut shortly. Many apologies for the disruption here.

**Comment by i-just** [comment]
Thanks. I'll close my PR in that case.

**Comment by mrtus** [comment]
@stobrien89 Will those also fix issues with `listObjectVersions` where the `Versions` key is no longer returned?

**Comment by stobrien89** [comment]
Version 3.243.2 is live— can those affected upgrade and confirm this is no longer an issue? Thanks!

**Comment by lro-tiierisch** [comment]
The Prefix parameter seems to be working again with this fix. Thanks

**Comment by stobrien89** [comment]
Closing this now, but more than happy to take another look if anyone is still having issues.

**Comment by drekinov** [comment]
We had that issue too. 
I am writing to share how bad it could been.
We have  temporary files which are deleted after some time.
Because of that issue this lead to batch delete API query to root of bucket.
effectively we had one of dev buckets wiped.

Fortunately hat did not land on stage or production because it wipe files as fast as blink of the eye.
It took me coule days to debug that because i thought it is bad code on our side :)
