### ISSUE TITLE
Pulling instance profile instead of app role on EKS

### ISSUE THREAD

**Issue by eric-kinsa** [aws/aws-sdk-php#2565]
### Describe the bug

I'm unable to get the SDK to use the app role assigned to the pod. Instead it tries to use the instance profile for whichever instance the pod is deployed to. I'm using the same process of assigning a role to a k8s service account as I do with my other dozen services. I feel like I'm missing a flag or something obvious, but I've looked through stackoverflow, github issues etc.

### Expected Behavior

Create a secretsmanager client and access a secret using the role assigned to the pod.

### Current Behavior

It's only looking for the instance profile, which could change depending on which node the pod is deployed to.

`AccessDeniedException (client): User: arn:aws:sts::xxxxxxxxxx:assumed-role/eks-nodes-sandbox/i-076b0f0634dsabdbf is not authorized to perform: secretsmanager:GetSecretValue on resource: sandbox/app1 because no identity-based policy allows the secretsmanager:GetSecretValue action -`

### Reproduction Steps

```php
<?php
    require 'vendor/autoload.php';
    use Aws\SecretsManager\SecretsManagerClient;
    use Aws\Exception\AwsException;

    $client = new SecretsManagerClient( [
        'version' => 'latest',
        'region' => 'us-east-1',
        'debug' => true
    ] );

    $secretName = 'sandbox/app1';
    try {
        $result = $client->getSecretValue( [
            'SecretId' => $secretName,
        ] );
    } catch ( AwsException $e ) {
        $error = $e->getAwsErrorCode();
        if ( $error == 'DecryptionFailureException' ) { // Can't decrypt the protected secret text using the provided AWS KMS key.
            throw $e;
        }
        if ( $error == 'InternalServiceErrorException' ) { // An error occurred on the server side.
            throw $e;
        }
        if ( $error == 'InvalidParameterException' ) { // Invalid parameter value.
            throw $e;
        }
        if ( $error == 'InvalidRequestException' ) { // Parameter value is not valid for the current state of the resource.
            throw $e;
        }
        if ( $error == 'ResourceNotFoundException' ) { // Requested resource not found
            throw $e;
        }
    }
```

### SDK version used

latest

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

EKS, php8.1

**Comment by yenfryherrerafeliz** [comment]
Hi @eric-kinsa, thanks for opening this issue. I will investigate the reported behavior and I will get back to you as soon as possible. In the meantime would you be able to specify the ecs credential provider manually, when instancing the client?, example below:
```php
$ecsProvider = CredentialProvider::ecsCredentials();
  $secretManagerClient = new SecretsManagerClient([
      'version' => 'latest',
      'region' => 'REGION',
      'credentials' => $ecsProvider
  ]);
```

Thanks!

**Comment by xian13** [comment]
Hi @eric-kinsa , in your case, is the error always happened and you can't get the correct credentials or it happened intermittent?

In our case, it happened intermittent and we still not sure why it happened

We use IAM Role and service account to connect to dynamodb, sometimes it gives us error 
`AccessDeniedException User: arn:aws:sts::xxxxxxx:assumed-role/xxxx-node-group-xxxxxx/i-xxxxxx is not authorized to perform: dynamodb:DescribeTable on resource: arn:aws:dynamodb:ap-southeast-1:xxxxx:table/xxxx-xxxxx-xxxx because no identity-based policy allows the dynamodb:DescribeTable action`

The error happened around 2-3 minutes and after that it can correctly get the access

At first we think maybe because we're not using the latest version, we use version 3.198.8 but after updating to 3.226.0 the error still happened

From `CredentialProvider.php` we see that there's some credential chain, when `web_identity` fail it will fallback to `instance` so in our case, some problem happened and it fallback from web identity into instance profile

And because we use less privilege and only the web identity provider that has the correct permission to access the dynamo db, it fail when try access the dynamo db using instance profile

@yenfryherrerafeliz could you check on this case?

**Comment by yenfryherrerafeliz** [comment]
Hi @xian13, thanks for reaching out and providing this information. I will have a discussion with my team soon about this issue, and then I will provide updates regarding, so that I will get back to you all as soon as possible.

Thanks!

**Comment by yenfryherrerafeliz** [comment]
Hi @xian13, while we investigate this I would like to see why the credential resolution for web_identity fails, and therefore it follows the next provider in the default chain. Would it be possible for you to enable debug logs and provide them?, also, you could specify which credential provider you want to use when instancing the client, which will not try with other credential provider in the chain. 

To enable debug logs you just need to pass the parameter  "debug" set to true when creating the client. Example:
```php
$client = new S3Client([
    'version' => 'latest',
    'region' => 'REGION',
    'debug' => true
])
```
**Note: Please redact any sensitive information.**

And to make the client to use the web_identity provider you could do the following:

```php
$ecsProvider = CredentialProvider::ecsCredentials();
$client = new S3Client([
    'version' => 'latest',
    'region' => 'REGION',
    'credentials' => $ecsProvider
]);
```

Thanks!

**Comment by PedroReichert** [comment]
Hello! Having the same problem in here:

#1292
