### ISSUE TITLE
HashingStream incompatible with Psr\Http\Message\StreamInterface

### ISSUE THREAD

**Issue by ecilion** [aws/aws-sdk-php#2644]
### Describe the bug

HashingStream::read() and HashingStream::seek() functions declaration is incompatible with Psr\Http\Message\StreamInterface.

### Expected Behavior

I expect that the read function doesn't throw an error when used

### Current Behavior

Fatal Compile Error: Declaration of Aws\HashingStream::read($length) must be compatible with Psr\Http\Message\StreamInterface::read(int $length): string

Uncaught Exception Symfony\Component\ErrorHandler\Error\FatalError: "Compile Error: Declaration of Aws\HashingStream::read($length) must be compatible with Psr\Http\Message\StreamInterface::read(int $length): string" at /app/vendor/aws/aws-sdk-php/src/HashingStream.php line 36

### Reproduction Steps

It's a compilation error so no steps to reproduce. I use the latest version of `psr/http-message`

### Possible Solution

change the functions declarations to

-  `public function read(int $length): string` for the `read` function
- `public function seek(int $offset, int $whence = SEEK_SET)` for the `seek` function

### SDK version used

3.258.1 and 3.258.2

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.1

**Comment by yenfryherrerafeliz** [comment]
Hi @ecilion, thanks for opening this issue. The suggested changes are not backward compatible, which will break customers using the SDK with an old php versions. I am not sure also why your installation of "psr/http-message" has the StreamInterface functions implemented with declared data types for the parameters. For example, if we check the code base, the abstract functions [read](https://github.com/php-fig/http-message/blob/efd67d1dc14a7ef4fc4e518e7dee91c271d524e4/src/StreamInterface.php#L134), and [seek](https://github.com/php-fig/http-message/blob/efd67d1dc14a7ef4fc4e518e7dee91c271d524e4/src/StreamInterface.php#L87), we can see that the parameters do not have datatype.

So, in order to better assist you could you please include any details we can use to reproduce your behavior?, for example, how did you install "psr/http-message"?, and if you installed manually, why don't you use the version that comes with the SDK?

Thanks you!

**Comment by ecilion** [comment]
Sorry for inconvenience, I just realized that we're using a custom version of "psr/http-message", thanks to your comment. I should have check that first.
