### ISSUE TITLE
Allow developer to choose psr http implementation

### ISSUE THREAD

**Issue by kaznovac** [aws/aws-sdk-php#2652]
### Describe the feature

currently sdk forces the guzzle as psr7 implementation, it would be benefitial to allow other implementations (like symfony/http-client, ...)

### Use Case

I'd like to use the client already in the app without importing and configuring another

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.261.2

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

N/A

**Comment by SamRemis** [comment]
Hi @kaznovac, 
To some extent, this is already possible using the [http_handler](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#http-handler) client configuration option.  You can use this to specify your http implementation, but you are bound to having it return a guzzle promise as the response.  

With a bit of custom code, this should work for you if you're only looking to have control over the client.  If you're looking to decouple from guzzle all together, then this would need a major version bump to change it.  Is setting `http_handler` sufficient for your use case?

**Comment by kaznovac** [comment]
Thank you for the quick answer @SamRamis :)

I'll investigate the suggestion.

In the future, I believe, it would be beneficial to the library to decouple it from the concrete http client.

**Comment by stefangr** [comment]
It would be great if this package in a future version depends on [php-http/discovery](https://packagist.org/packages/php-http/discovery) instead of guzzlehttp/guzzle and guzzlehttp/psr7. (More on this package on https://docs.php-http.org/en/latest/discovery.html)

This would require updating the minimum PHP version to 7.1, but with a [user base of less than 1% of composer users](https://packagist.org/php-statistics) on older PHP versions, that should not be a problem.

**Comment by stobrien89** [comment]
Hi all, 

Just wanted to let you know that we'll be closing this for now.  There are no plans for work on this in V3 of the SDK, but when/if we get the green light to work on a V4, we will be very much in favor of going with an agnostic approach with regard to HTTP clients.
