### ISSUE TITLE
Composer dependency symfony/deprecation-contracts requires php >=8.1

### ISSUE THREAD

**Issue by bluewire-solutions** [aws/aws-sdk-php#2655]
### Describe the issue

- Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0".
- Documentation says 5.5 is minimum version https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/getting-started_requirements.html

### Links

https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/getting-started_requirements.html

**Comment by SamRemis** [comment]
Hi @bluewire-solutions,
Is there a longer error message?  Our [minimum version](https://github.com/aws/aws-sdk-php/blob/1fb31e97fa4da90935a87e321c07662a5827ee2d/composer.json#L19) is set to 5.5.  The same is true for the [symfony package](https://github.com/aws/aws-sdk-php-symfony/blob/bb42107736a9b3f4aea32b25a5cf3e15bf6fd427/composer.json#L15).  

Is it possible this error is being generated by another package you require?

**Comment by bluewire-solutions** [comment]
can definitely be assigned to that installation of the plugin instance.

composer.lock
`{
            "name": "symfony/deprecation-contracts",
            "version": "v3.2.1",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/deprecation-contracts.git",
                "reference": "e2d1534420bd723d0ef5aec58a22c5fe60ce6f5e"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/symfony/deprecation-contracts/zipball/e2d1534420bd723d0ef5aec58a22c5fe60ce6f5e",
                "reference": "e2d1534420bd723d0ef5aec58a22c5fe60ce6f5e",
                "shasum": ""
            },
            "require": {
                "php": ">=8.1"
            },`


currently evaluating the option, that php8.2 of dev system which made composer install is causing that versioning issue on 8.0 production system

**Comment by bluewire-solutions** [comment]
https://github.com/symfony/deprecation-contracts/blob/main/composer.json came with aws sdk and requires 8.1 according to it's spec

**Comment by stobrien89** [comment]
Hi @aberkow and @bluewire-solutions,

Sorry to hear about the issues.  Can you confirm this message is coming from the composer `platform_check` script?

> currently evaluating the option, that php8.2 of dev system which made composer install is causing that versioning issue on 8.0 production system

Are you shipping dependencies installed by your dev system? I wouldn't recommend doing this.  This might be okay in certain cases, but package constraints will vary from version to version.

@aberkow,

Are you doing something similar? If so, I'd recommend having the production system install dependencies rather than shipping them from dev.

**Comment by bluewire-solutions** [comment]
Confirm platform_check script.

In that particular case we're building it in a CD environment and ship it as wordpress plugin, thus all composer activities are running in the pipeline and not in the production system.

The approach from @aberkow would work out then

**Comment by stobrien89** [comment]
@bluewire-solutions,

Thanks for confirming.  There's nothing we can do to prevent this from happening, as this is a dependency of Guzzle. I'd recommend finding some way to install the dependencies with the version that will be used in production, otherwise, you can contact the package owners (of deprecation-contracts).  There's nothing we can do here since it's not a dependency of ours— it's a guzzle dependency.  Sorry we can't be of more help!

**Comment by aberkow** [comment]
Sorry I didn't see the notification earlier. In my case the development environment was using PHP8 and the prod environment was using PHP7.x so it was less of an issue for deployment.
