### ISSUE TITLE
`S3Storage->upload()` doesn't seem to be synchronous

### ISSUE THREAD

**Issue by wujekbogdan** [aws/aws-sdk-php#2701]
### Describe the bug

I can't delete the uploaded local file right after calling the `upload()` method because uploading will fail.

### Expected Behavior

I would expect to be able to delete a file right after the `upload()` method is called.

### Current Behavior

If I delete a file right after calling `upload()` then uploading fails.

### Reproduction Steps

``` php
$client = new AwsS3Client([
    'version' => 'latest',
    'region' => MY_REGION,
    'credentials' => [
        'key' => MY_KEY,
        'secret' => MY_SECRERT,
    ],
]);

$file = '/path/to/file.jpg';
$client->upload('my-bucket', 'my-file.jpg', fopen($file, 'r+'));

unlink($file);

// Uploading fails
```

``` PHP
$client = new AwsS3Client([
    'version' => 'latest',
    'region' => MY_REGION,
    'credentials' => [
        'key' => MY_KEY,
        'secret' => MY_SECRERT,
    ],
]);

$file = '/path/to/file.jpg';
$client->upload('my-bucket', 'my-file.jpg', fopen($file, 'r+'));

$blankImage = 'path/to/dummy.jpg';

copy($blankImage, $file);

// dummy.jpg is uploaded instead of file.jpg!
```

### SDK version used

3.271.3

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

8.1.18, php:8.1.18-apache Docker image running on macOS 13.3.1

**Comment by yenfryherrerafeliz** [comment]
Hi @wujekbogdan, sorry to hear about your issues. I am not sure why you are experiencing this, because the upload function is a synchronous operation. We can confirm this by following its implementation, and you will see that [here](https://github.com/aws/aws-sdk-php/blob/bc19179c5f070b3d7ca7fe8a87eaeda1464b94e5/src/S3/S3ClientTrait.php#L35)  we will be always expecting a promise, and from there we are calling the wait function that will wait for the operation to complete. I also tried to reproduce this on my end, by using the code below, and I was not able to. In every try I got success results.
Here is my code:
```php
$client = new Aws\S3\S3Client([
    'version' => 'latest',
    'region' => 'us-east-2'
]);
$file = "./file1";
$client->upload(getenv('TEST_BUCKET'), getenv('TEST_KEY'), fopen($file, 'r+'));
// UNCOMMENT THIS TO DELETE
// unlink($file);
// UNCOMMENT THIS TO COPY
copy('./file2', $file);
```

>$client = new AwsS3Client([
    'version' => 'latest',
    'region' => MY_REGION,
    'credentials' => [
        'key' => MY_KEY,
        'secret' => MY_SECRERT,
    ],
]);

What I noticed here is that the class that you are instancing is AwsS3Client, but is this correct?, because it should be Aws\S3\S3Client. Could you please confirm if you are using the correct PHP SDK dependency and version?

Thanks!

**Comment by wujekbogdan** [comment]
> What I noticed here is that the class that you are instancing is AwsS3Client

It's just an alias:

``` php
use \Aws\S3\S3Client as AwsS3Client;
``` 

here's the entry from `composer.json`

``` json
"aws/aws-sdk-php": "^3.52"
```

which resolves to `3.271.4`

**Comment by yenfryherrerafeliz** [comment]
@wujekbogdan have you tried running ```composer update``` to make sure this dependency is up to date?. Could you please also try in a separated empty project and try installing the dependency from scratch?. I have been trying to reproduce this issue and I am not able to. 

Thanks!

**Comment by wujekbogdan** [comment]
> @wujekbogdan have you tried running composer update to make sure this dependency is up to date?. Could you please

I'm 100% sure the lib is up to date. It's version `3.271.4`, I double check it - I went to `vendor` to confirm if what I see in the IDE reflects the reality.

> Could you please also try in a separated empty project and try installing the dependency from scratch?

Let me try it out. I'll get back to you.

**Comment by yenfryherrerafeliz** [comment]
Hi @wujekbogdan, were you able to try my suggestion of creating an empty project?, if so, how did that go?

Thanks!
