### ISSUE TITLE
AWS SDK PHP show deprecated warning from Guzzle

### ISSUE THREAD

**Issue by EnzoLORMONT** [aws/aws-sdk-php#2738]
### Describe the bug

AWS SDK PHP show deprecated warning from Guzzle as followed
Deprecated: Creation of dynamic property GuzzleHttp\Handler\CurlMultiHandler::$_mh is deprecated in GuzzleHttp/Handler/CurlMultiHandler.php on line 58

### Expected Behavior

No deprecated warning

### Current Behavior

Deprecated: Creation of dynamic property GuzzleHttp\Handler\CurlMultiHandler::$_mh is deprecated in GuzzleHttp/Handler/CurlMultiHandler.php on line 58

### Reproduction Steps

Run AWS SDK PHP by downloading aws.php on this link : https://docs.aws.amazon.com/aws-sdk-php/v3/download/aws.phar

### Possible Solution

No response

### Additional Information/Context

Use it in WordPress plugin to send all files to S3.

### SDK version used

May be latest

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.2.8 
OS : Manjaro Linux
Kernel : 6.1.38-1-MANJARO

**Comment by gitnik** [comment]
see https://github.com/aws/aws-sdk-php/issues/2702

**Comment by yenfryherrerafeliz** [comment]
Hi @EnzoLORMONT, sorry for the delay on answering to this. Please see this [comment](https://github.com/aws/aws-sdk-php/issues/2738#issuecomment-1658269486), which basically links you to an issue where explains that this issue could be related to using an outdated Guzzle version. Could you please try running composer update in order to update your dependencies?

Please let me know if that helps!

Thanks!
