### ISSUE TITLE
Deprecated since 9 years but never removed

### ISSUE THREAD

**Issue by AurelienPillevesse** [aws/aws-sdk-php#2756]
### Describe the issue

In the AWSClient class, since 9 years (when I use the Blame feature) a function is deprecated.

```https://github.com/aws/aws-sdk-php/blame/master/src/AwsClient.php#L662```

In the last 2.xx tag version, it was already ```@deprecated``` but not removed between 2.xx and 3.xx version. 

```https://github.com/aws/aws-sdk-php/blob/6ad549d04ec33d38f79ff0aa103c7a74f3e93cfa/src/AwsClient.php#L662```

Is it really deprecated or not ?
If it was, it should have been removed between 2.xx and 3.xx no ?

**Comment by yenfryherrerafeliz** [comment]
Hi @AurelienPillevesse, thanks for opening this issue. The reason why this is just marked as deprecated and not removed is because we do not want to break customers that still uses this function and that want to keep using the most updated SDK. 

Please feel free to open a new issue if there is anything else that we can assist you with.

Thanks!
