### ISSUE TITLE
DAX query support

### ISSUE THREAD

**Issue by stadskle** [aws/aws-sdk-php#2758]
### Describe the feature

#2118 is closed for staleness, but this should be re-opened as a feature request. 

We need to get support to query DAX from PHP in order to utilize DAX caching on our DynamoDB services.

### Use Case

With the rise of Frameworks like [bref](https://bref.sh/docs/function/handlers.html)  DynamoDB and PHP is becoming more and more relevant, and when using DynamoDB at scale through public lambda, the need for high performance access to DynamoDB becomes quickly relevant. It is very costly engineering wise (and unnecessary) to start adding custom redis layers when DAX exists. 

Currently there is no support of querying a DAX cluster using the PHP SDK, and this seems like a basic gap from one of the large service offerings from AWS, I hope the team can consider this seriously. 

### Proposed Solution

Add a DAX query client in the SDK.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.278.2

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

8.2

**Comment by wolflingorg** [comment]
+1

Adding DAX query support to the AWS PHP SDK is essential for improving DynamoDB's performance, especially when used with public Lambda functions. This enhancement would simplify architecture and reduce the need for custom Redis layers, making it a valuable addition to the SDK.

**Comment by DanielMukh** [comment]
+1

Adding DAX query support to the AWS PHP SDK is essential for improving DynamoDB's performance, especially when used with Lambda functions. This enhancement would simplify architecture and reduce the need for custom Redis layers, making it a valuable addition to the SDK.

**Comment by GabrielVBusatoCodificar** [comment]
+1

Adding DAX query support to the AWS PHP SDK is essential for improving DynamoDB's performance, especially when used with Lambda functions. This enhancement would simplify architecture and reduce the need for custom Redis layers, making it a valuable addition to the SDK.

**Comment by raphaelcangucu** [comment]
Hi @yenfryherrerafeliz , do you guys have any plans to add the DAX Client? 

If not, can you provide any kind of example or implementation of some queries on dax using only PHP?

Kind regards

**Comment by cd-aws** [comment]
@raphaelcangucu We can help you with this. Please reach out on your AWS request.

**Comment by RanVaknin** [comment]
Hi everyone,

Thanks for all the engagement on this issue. The reason this was never prioritized is because there are several data plane API clients for different AWS languages and they are all owned by the Dynamodb DAX team itself. This data plane client was never officially a part of the SDK therefore the SDK team cannot add it (it requires DDB specific logic that the DDB service team is better equipped with) 

Please refer to [this comment](https://github.com/aws/aws-sdk-js-v3/issues/4263#issuecomment-2035584918) which outlines the distinction between the teams. FWIW we have upstreamed this request to the DDB team to implement a PHP DAX data plane client, however it's currently not planned. 

Because this request is outside the scope of the SDK, we are going to close this. I encourage you all to submit Feedback by following the "Feedback" link on the bottom of the DynamoDB page on the AWS Console.

Thanks again for your engagement.
All the best,
Ran~
