### ISSUE TITLE
I can't figure out how to log in via the SDK.

### ISSUE THREAD

**Issue by Lollichkeit** [aws/aws-sdk-php#2789]
### Describe the bug

I can't figure out how to log in via the SDK.
Also, I can't find any documentation.

### Expected Behavior

I searched everything on Github.

### Current Behavior

I can't find any documentation

### Reproduction Steps

Can someone please help me with this?

### SDK version used

aktuell

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP

**Comment by SamRemis** [comment]
Hi @Lollichkeit,

If you just mean provide credentials to log in to AWS, there are a number of ways, a few of them listed [here](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_provider.html).  The SDK will automatically search places like your .aws/credentials file, your aws config file, your environment variables, etc.  This is standard behavior across all SDKs which you can read more about [here](https://docs.aws.amazon.com/sdkref/latest/guide/standardized-credentials.html#credentialProviderChain). 

If you're trying to log in using SSO via the SDK, that behavior is not currently supported in this or most SDKs.  You can log in via the CLI and the SDK will automatically use the credentials retrieved from it.  

If you're looking for how to specify credentials on the client constructor, that's currently undocumented behavior.  Hard-coding your credentials is never recommended because of the security risks.  That being said, it is supported and the syntax for it looks like this:

```
$client = new S3Client([
      'region' => 'us-east-1',
      'credentials' => [
            'key' => 'key_here',
            'secret' => 'secret_here' 
      ]
]);
```
