### ISSUE TITLE
File paths are not safe for Windows

### ISSUE THREAD

**Issue by alaskancode** [aws/aws-sdk-php#2908]
### Describe the bug

PHP Fatal error:  Uncaught Aws\Exception\CredentialsException: Cannot read credentials from C:\Users\myuser/.aws/credentials in C:\Users\myuser\Downloads\amazon_php\example_code\dynamodb\dynamodb_basics\vendor\aws\aws-sdk-php\src\Credentials\CredentialProvider.php:826

Note that the beginning of the file path is with proper backslashes in Windows, and that it then switches to Unix style forward slashes for the rest of the path: i.e. C:\Users\myuser/.aws/credentials

### Expected Behavior

C:\Users\myuser\.aws\credentials

Note, Windows does not do well with . folder names. The default for Windows should be to a designated folder without . in the folder name. I tried setting credentials file to a new location using setx command suggested in the documentation (https://docs.aws.amazon.com/sdkref/latest/guide/file-location.html), but the php program does not respect it.

### Current Behavior

This path will fail in Windows: C:\Users\myuser/.aws/credentials, which is what happens

### Reproduction Steps

1) Download current php-sdk
2) composer update
3) composer install
3) php Runner.php (dynamo db example)
4) program fails with above exception, due to not being able to locate credentials file

### Possible Solution

Use realpath function, which will create proper path naming in a Windows environement: https://www.php.net/manual/en/function.realpath.php

### SDK version used

"name": "aws/aws-sdk-php",             "version": "3.304.0",

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

php 8

**Comment by yenfryherrerafeliz** [comment]
Hi @alaskancode, sorry to hear about your issue. I understand that some improvements could be done here for resolving paths depending on running environment, and this is something I will bring up to the team for discussion. However, there are some alternatives that you can use now for solving this issue and some of them are in the link that you posted already. If you properly set a value for AWS_SHARED_CREDENTIALS_FILE with a location of your preference then, you should have not issues if that location is a valid path and the file is a valid credentials one. I know the docs recommends using setx, but if that did not work then, you may need to check on your environment what is preventing that variable from being set. We can check [here](https://github.com/aws/aws-sdk-php/blob/6dac9b3257873a807ac73f6dc4418bdc49a5d9db/src/Credentials/CredentialProvider.php#L833) that we look at that variable value first and if is set then we give preference to that value over the default one. Windows also has another ways to set environment variables and I encourage you to try them. Below you can see a short example where I set AWS_SHARED_CREDENTIALS_FILE to a custom location and the SDK tried to use that one. Please see below:
```php
<?php
require '../vendor/autoload.php';

use Aws\Credentials\CredentialProvider;
use Aws\S3\S3Client;

putenv("AWS_SHARED_CREDENTIALS_FILE='./mysharedcredsfile'");

$client = new S3Client([
    'region' => 'us-east-2',
    'credentials' => CredentialProvider::ini()
]);
$client->listBuckets();
```
Here is the output:
```console
PHP Fatal error:  Uncaught Aws\Exception\CredentialsException: Cannot read credentials from './mysharedcredsfile' in $PROJECT_DIR/src/Credentials/CredentialProvider.php:826
Stack trace:
...
```
Another solution for your issue is to provide the credentials file location explicitly to the credential provider as follow:

```php
<?php
require '../vendor/autoload.php';

use Aws\Credentials\CredentialProvider;
use Aws\S3\S3Client;

$credentialsFilePath = 'YOUR_CUSTOM_CREDENTIALS_FILE_PATH';
$provider = CredentialProvider::ini(null, $credentialsFilePath);
$memoizedProvider = CredentialProvider::memoize($provider);
$s3Client = new S3Client([
    'region' => 'us-east-1',
    'credentials' => $memoizedProvider
]);
$s3Client->listBuckets();

```

Please let me know if that helps!

Thanks!
