### ISSUE TITLE
Missing manifest function

### ISSUE THREAD

**Issue by jase-languasco** [aws/aws-sdk-php#3024]
### Describe the bug

I'm getting the following fatal:

```
Fatal error: Uncaught Error: Call to undefined function Aws\manifest() in /srv/www/vendor/aws/aws-sdk-php/src/AwsClient.php:241 
```

I've uninstalled the package with composer and reinstalled it. I've looked at the installed code in the vendor directory and src/functions.php is there with the manifest function.

Not sure whats going on here. Any help would be appreciated.

### Regression Issue

- [x] Select this option if this issue appears to be a regression.

### Expected Behavior

No fatal

### Current Behavior

A fatal is being thrown

```
Fatal error: Uncaught Error: Call to undefined function Aws\manifest() in /srv/www/vendor/aws/aws-sdk-php/src/AwsClient.php:241 
```

### Reproduction Steps

Setting up SesClient

```
$this->vendor = new SesClient([
    'version' => 'latest',
    'region'  =>  "us-east-1",
    'credentials' => [
        'key'    => $params['aws_access_key_id'],
        'secret' => $params['aws_secret_access_key'],
    ],
]);
```

Using: `"aws/aws-sdk-php": "^3.325",`

### SDK version used

"aws/aws-sdk-php": "^3.325",

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.3.9 (cli) (built: Jul  5 2024 12:03:46) (NTS) Copyright (c) The PHP Group Zend Engine v4.3.9, Copyright (c) Zend Technologies     with Zend OPcache v8.3.9, Copyright (c), by Zend Technologies

**Comment by yenfryherrerafeliz** [comment]
Hi @jase-languasco, sorry to hear about your issues. I have done a test in my local with the same version you point here and I do not see the same behavior. 
To determine what the problem is, could you please try the following:
- Try a new test project from scratch and check if you get the same error? if you do not see the error it means something is wrong with your original project configuration.
- Try deleting the vendor folder and run `composer update`.

Please let me know if that helps!

Thank you!
