### ISSUE TITLE
upload direct link to s3

### ISSUE THREAD

**Issue by syrakozz** [aws/aws-sdk-php#452]
how i can upload a direct link (not absoulte path on disk ) source to s3

**Comment by jeremeamia** [comment]
The `'Body'` parameter of `putObject()` can accept a stream created by `fopen()`. So if you do `fopen('http://...', 'r')`, then it could work. However, S3 requires that the content-length be provided. When you upload a local file, the SDK will calculate that for you. In the case of a stream, you would need to explicitly specify that using the `'ContentLength'` parameter.

**Comment by syrakozz** [comment]
thank you, 
is there any future release that it will calculate ContentLength for the stream
it will be very usefull

**Comment by mtdowling** [comment]
It depends on the stream that you use. If it has a known content-length because there was a content-length header in the HTTP response, then we will automatically know the length of the stream (assuming you're using a PHP stream wrapper for the input stream).

For chunked streams or streams, we do not attempt to calculate the length because it could be anywhere from 0 to an infinite number of bytes. If the stream is not rewindable (which network streams usually aren't), then we'd have to cache all of that data in memory.
