### ISSUE TITLE
The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256

### ISSUE THREAD

**Issue by DrySs** [aws/aws-sdk-php#483]
Hi there,

I'm trying to implement SDK on new bucket with v4 authorization (like Frankfurt - 'eu-central-1').

However, even if I force "signature=>v3" on S3 factory, and (I checked it) if "new S3SignatureV4('s3')" is called in S3Client.php, I still receive this message after a call to getSignedUrl() in CloudFront download distribution.

Unable to play streaming distribution (RTMP) too, with an infitinite loop on play button.

If I switch to v2 signature (like Ireland bucket- 'eu-west-1'), everything works fine.
Any idea on v4 signature issues?

Thanks

**Comment by mtdowling** [comment]
This is a known issue with CloudFront that unfortunately cannot be fixed by the SDK (client), but has to be fixed at the service level. Here's a related forum post that shows that the CloudFront team is aware of the issue, and they'll post to this thread when it has been addressed: https://forums.aws.amazon.com/thread.jspa?messageID=580347

**Comment by taz77** [comment]
Would love to see Frankfurt support the same signing as all of the other regions. Frankfurt right now is completely useless.

**Comment by alexmatveev** [comment]
@mtdowling @taz77  Please see http://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4

"http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html explains how to enable V4 in the various SDKs, assuming you are using an SDK that has that capability."
