### ISSUE TITLE
Cannot upload documents to Cloudsearch

### ISSUE THREAD

**Issue by SteveEdson** [aws/aws-sdk-php#495]
Not sure if I am going wrong somewhere, or if this is an issue with the PHP SDK, but I cannot upload documents.

Here is a sample of the code I am running,

```php
$aws = Aws::factory($awsConfig);
 
$cs = $aws->get('CloudSearch');
 
$domain = $cs->getDomainClient('my_domain');
 
$res = $domain->uploadDocuments([
    'documents' => EntityBody::fromString($json),
    'contentType' => 'application/json'
]);
```

but when it tries to upload documents, I get the following error:

> PHP Fatal error:  Uncaught exception 'Aws\Common\Exception\InstanceProfileCredentialsException' with message 'Error retrieving credentials from the instance profile metadata server. When you are not running inside of Amazon EC2, you must provide your AWS access key ID and secret access key in the "key" and "secret" options when creating a client or provide an instantiated Aws\Common\Credentials\CredentialsInterface object. (Client error response
[status code] 404
[reason phrase] Not Found
[url] http://169.254.169.254/latest/meta-data/iam/security-credentials/)'

my access policy looks like this

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": [
        "cloudsearch:suggest",
        "cloudsearch:search"
      ]
    },
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::XXXXXXXXXXXX:user/MY_USERNAME"
      },
      "Action": "cloudsearch:*"
    }
  ]
}
```

Any help would be appreciated.

Thanks.

**Comment by jeremeamia** [comment]
When you call `getDomainClient()`, you'll need to provide your credentials somehow. We do not automatically use the ones from the general CloudSearch client you call `getDomainClient()` from, since they may not necessarily be the ones your domain is configured to use. See the section of our user guide on the [`getDomainClient()` helper method](http://docs.aws.amazon.com/aws-sdk-php/guide/latest/service-cloudsearchdomain.html#helper-method) for more details. If you have any more questions, feel free to reopen the issue. Thanks.

**Comment by SteveEdson** [comment]
I assumed the credentials were passed through automatically like in other services. I've got it working now though, thanks again for your help!

**Comment by cristal2431** [comment]
Does this function ` getDomainClient()` exist in v3 ?
