### ISSUE TITLE
Problem with very long request (cURL)

### ISSUE THREAD

**Issue by DrySs** [aws/aws-sdk-php#499]
When using PHP SDK to reach AWS services, I noticed that's every request take a looooong time to be executed. I generated logs with xDebug and parse it with CacheGrind.

For example:
- Aws\S3\S3Client->getObjectAcl take 493ms to be executed
- Aws\S3\S3Client->putObjectAcl take 180ms to be executed
- Aws\CloudFront\CloudFrontClient->listCloudFrontOriginAccessIdentities take 984ms (!!)
- Aws\CloudFront\CloudFrontClient->listDistributions take 269ms
- Aws\CloudFront\CloudFrontClient->listStreamlingDistributions take 208 ms

As in my application I can do many requests, all this time are cumulated.
I have in total, for one page, 3 745ms (!!) of loading time, all needed for AWS requests.

How is this possible?
Any idea on how to fix it?

**Comment by jeremeamia** [comment]
If you have any questions about the expected latency of those operations, you should ask on the [AWS forums](https://forums.aws.amazon.com/index.jspa).

For some general things to consider about the SDK, make sure to take a look at some of our [performance tips](http://docs.aws.amazon.com/aws-sdk-php/guide/latest/performance.html). Measuring performance with xdebug can be problematic, because enabling xdebug, in general, slows down the execution of the code.

You could also consider doing those CloudFront requests concurrently. See [Executing Commands in Parallel](http://docs.aws.amazon.com/aws-sdk-php/guide/latest/feature-commands.html#parallel-commands) from our user guide.

**Comment by DrySs** [comment]
Thanks for your reply :)

I am the only one to have this kind of slow latency?
I know that xdebug slows down, but even without xdebug, request are really slow...

If I go deeper in xdebug report, it's always coming from cURL operations, with big big load time...

**Comment by mtdowling** [comment]
The amount of latency for a request greatly depends on your connection and the region you're connecting to. Most of the request times you posted don't seem out of the norm to me (e.g., 208 ms). The longer CloudFront times could be related to the geographical distance between your client and the server. You'd need to analyze your connection to the CloudFront endpoint to see why there is latency (e.g., traceroute, tcpdump, etc.).

One thing to keep in mind when contacting services is to use a region that's closest to your servers so that the distance that data needs to travel is reduced (thereby reducing latency).

As @jeremeamia  stated, you can also reduce the total amount of time needed to send these requests by sending them concurrently.

**Comment by DrySs** [comment]
I'm in France and trying to request Ireland, there is no region closer to Paris than Ireland's one...
208 ms for a request is veeeeeeeryyyy looooong.

If you have to do many calls to API (not concurrently, because your process have logical order), it can take many seconds to load a page!

**Comment by ferozfirru** [comment]
hi , i too having slow issues with my php-aws-sdk-v3 , the auto-loader itself taking aroung 0.5 seconds and 2MB memory consumption. im using only s3client from this Aws-sdk no other features, please tell me how to make it run faster? can i load only s3 related modules in autoloader?
