### ISSUE TITLE
"x-amz-content-sha256" header issue 

### ISSUE THREAD

**Issue by tellsaqib** [aws/aws-sdk-php#509]
The seems a bug in V4 signing. Requests are failing for Frankfurt region.
For e.g. If I try this code
   
 ```php
$client = Aws::factory(array(
            'key' => $key,
            'secret' => $secret
            'region' => 'eu-central-1',
            'signature' => new SignatureV4()
                )
)->get('s3', true);
    
$response = $client->deleteMatchingObjects($bucketName, $folderPrefix);
```
It returns 

```
Uncaught Aws\S3\Exception\S3Exception: AWS Error Code: UnsignedContentSHA256NotAllowed, Status Code: 400, AWS Request ID: 89EBFEF4DB214659, AWS Error Type: client, AWS Error Message: The provided 'x-amz-content-sha256' header must be a valid SHA256., User-Agent: aws-sdk-php2/2.7.22 Guzzle/3.9.2 curl/7.25.0 PHP/5.4.3 ITR thrown in \aws2-7-22\Aws\Common\Exception\NamespaceExceptionFactory.php on line 91
```

**Comment by jeremeamia** [comment]
A few questions:

1. Is the bucket's location actually `eu-central-1`?
1. Are your `key` and `secret` correct?
1. Does this happen when you you do not set the `signature` config option? (Note: you shouldn't need to do that because the SDK knows to use SignatureV4 for the Frankfurt region.)
1. Can you get a full stack trace from the exception? The `deleteMatchingObjects()` method encapsulates a number of operations, and it's hard to tell where the problem might be with just this information alone.

**Comment by jeremeamia** [comment]
It loos like you are setting the `signature` config option incorrectly.

1. You shouldn't need to provide this configuration value at all, because the SDK will automatically use the correct signature based on the service you are using and region you are specifying.
2. That is the wrong object anyway. It would need to be an instance of `Aws/S3/S3SignatureV4`, but like I said in (1), you should not need to set this explicitly.
