### ISSUE TITLE
Examples of setting Private Hosted Zone CNAME record

### ISSUE THREAD

**Issue by BardiaAfshin** [aws/aws-sdk-php#513]
I have a Cloudformation script that generates some elastic load balancer, and I want to create a CNAME on Route53 with the Private DNS name of the generated elastic load balancer to a preset name

ie:
elb-asd9f87asd98f7a9.us-east1.computer-amazonaws.com TO friendly-elb-name.myshortcust.dev

Two questions:
1. How do I go about doing the above with what I've mentioned programmatically with aws sdk php
2. Is there a better, easier way? Example, it would be nicer if I can set the ELB DNS name in the cloudformation script itself.

Thoughts?

**Comment by jeremeamia** [comment]
Hello!

1. I'm not familiar enough with the specifics of the Route 53 API to give you specific advice on what your parameters should be, but you'll need to use the [`Route53Client::changeResourceRecordSets` method](http://docs.aws.amazon.com/aws-sdk-php/latest/class-Aws.Route53.Route53Client.html#_changeResourceRecordSets). [This example](http://docs.aws.amazon.com/Route53/latest/APIReference/CreateAliasRRSAPI.html) from Route 53's API docs seems like it might be conceptually close to what you are trying to do. If you need additional guidance on how to use the Route 53 service, you should visit [their forum](https://forums.aws.amazon.com/forum.jspa?forumID=87).
2. That question would be better suited for the [AWS CloudFormation forum](https://forums.aws.amazon.com/forum.jspa?forumID=92), since they are going to be able to provide the best help for writing CloudFormation templates.

I'm going to go ahead and close this issue since you will need to head over to the AWS forums to get your questions answered. If you end up needing any specific help with the SDK related to these questions, feel free to reopen this issue.
