### ISSUE TITLE
Large file support syncing S3 to NTFS (and others)

### ISSUE THREAD

**Issue by wittiws** [aws/aws-sdk-php#578]
A call to `downloadBucket` with `'allow_resumable' => TRUE,` does not function properly on a 2.52 GB file. It continues to append to the file with each subsequent sync call, even when the file size far exceeds the file being downloaded. The sync functions properly on other files in the same folder, although the next-largest file in the synced folder is 1.29 GB.

This implies connection to a known issue with [filesize](http://php.net/manual/en/function.filesize.php), which relates to the OS returning a 32-bit signed integer. If that is the source of the problem, then the sync likely fails with files as small as 2.1 GB That man page also has a filesize calculator that does not rely on the file system, but replacing calls to filesize (or other stat-related functions) would be fairly invasive.

My temporary workaround is to move files exceeding 2.1 GB into a manually-synced folder so that the folder sync does not get stuck re-downloading (and appending to) the file each time, but that is not really a solution.

**Comment by mtdowling** [comment]
Yeah, this is a known issue with a 32-bit build of PHP (which is the only build available on Windows, and  I'm assuming you're using Windows based on the mention of NTFS). I agree that trying to work around this using something like the functions you mentioned would be invasive and most likely a massive loss in performance when calculating the size of a large file.

The Windows PHP site mentions this issue in the left column: http://windows.php.net/.

> x86_64 Builds
> The x64 builds of PHP for Windows should be considered experimental, and do not yet provide 64-bit
> integer or large file support. Please see this post for work ongoing to improve these builds.

It looks like even if you tried using a 64-bit version of PHP on Windows, it still would not support "large" files.

There really isn't anything we can do about this. This issue is documented in the FAQ: http://docs.aws.amazon.com/aws-sdk-php/v2/guide/faq.html#why-can-t-i-upload-or-download-files-greater-than-2gb

**Comment by mtdowling** [comment]
As this is a known issue in PHP and is documented as a limitation in the SDK documents, I'll go ahead and close this issue.
