### ISSUE TITLE
Amazon S3 Set Signature If V4

### ISSUE THREAD

**Issue by sobytes** [aws/aws-sdk-php#582]
Having the following issues, i am calling this function
~~~
$bucket = 'bucket';
$client = S3Client::factory(array(
    'key'    => 'key',
    'secret' => 'secret'
));

try
{

    //Check Bucket Region Important
    $result = $client->getBucketLocation(array(
        // Bucket is required
        'Bucket' => $bucket
    ))->toArray();

    $region = $result['Location'];

    if(!empty($region)){
        if($region != 'EU'){
            $client->setRegion($region);
        }
    }

    $iterator = $client -> listObjects(array(
        'Bucket' => $bucket,
        'Delimiter' => '/'
    ));
}
catch (Exception $e)
{
    echo json_encode(array("error" => $e -> getMessage()));
}

die();
~~~

Which is outputting.

{"error":"The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256."}

How do i get the signature and then set it to v4 if its in the region eu-central-1

I cant set it in the factory call because it maybe different everytime?

Any help thanks

**Comment by mtdowling** [comment]
You need to set a region when creating the client. If you do this, then the SDK will automatically use the correct signature version:

```php
$client = S3Client::factory(array(
    'key'    => 'key',
    'secret' => 'secret',
    'region' => 'eu-central-1'
));
```

Setting the region on the client after it is created will not change the signature method used by the client.

**Comment by sobytes** [comment]
Hi @mtdowling 

The problem i have is i can't do that because the region maybe different every time depending on where the user has setup their region, so i need to do everything based on user settings.

Thats why i am calling 
~~~
//Check Bucket Region Important
    $result = $client->getBucketLocation(array(
        // Bucket is required
        'Bucket' => $bucket
    ))->toArray();

    $region = $result['Location'];

    if(!empty($region)){
        if($region != 'EU'){
            $client->setRegion($region);
        }
    }
~~~

And setting the region there.

Which works fine but had this issue today with a user using v4 signature?

Thanks

**Comment by mtdowling** [comment]
Amazon S3 regions have recently become "region aware", meaning you actually need to know the region you are contacting before you send requests. This limitation was introduced because some regions require signature version 4. In the past, you could send a request a "s3.amazonaws.com" and it would mostly "just work" thanks to CNAMEs or redirects taking you to the correct regionalized bucket. However, with the addition of sigv4 only regions (e.g., "eu-central-1"), it is now not possible to rely on this behavior as sigv4 regions must be signed explicitly for the region you are contacting (for canonicalizing the signature). 

The good news is that you can call `getBucketLocation` against any region endpoint and it will give you the actual region a bucket is stored in. You then need to use a client that has been configured to use that region when sending requests to those buckets. There are various ways you could achieve this; one thing that comes to mind is decorating S3Client, getting the region of a bucket before sending requests, using a client that is scoped for the given region, and returning the result. You could cache previously created clients to avoid having to create clients over and over.

**Comment by sobytes** [comment]
Hi @mtdowling,

Thanks for this and this now works.
~~~
$client = S3Client::factory(array(
		 'key'    => 'key',
                  'secret' => 'secret'
		));
		$result = $client->getBucketLocation(array(
		    'Bucket' => $bucket
		))->toArray();

		$region = $result['Location'];

		$client = S3Client::factory(array(
		    'key'    => 'key',
                    'secret' => 'secret'
		    'region' => $region
		)); 
~~~

Which is obviously not the correct way to handle this could you give a correct example.

Thanks

**Comment by mtdowling** [comment]
That's a perfectly valid way to do this. My idea of decorating S3Client would wrap this up a bit more nicely and allow you to reuse previously created client instances, but it's essentially the same strategy.

**Comment by sobytes** [comment]
Ok great thanks @mtdowling

**Comment by mtdowling** [comment]
No problem.
