### ISSUE TITLE
Fatal error in SDK v3.0

### ISSUE THREAD

**Issue by moerphie** [aws/aws-sdk-php#598]
hi,
since i've updated the aws-php-sdk to the latest release 3.0, the following code returns a fatal error.
```php
<?php
require 'vendor/autoload.php'; 
 
$client = new \Aws\S3\S3Client([ 'version' => 'latest', 'key' => AWS_KEY, 'secret' => AWS_SECRET_KEY, 'region' => AWS_REGION ]);
 
try{
	$response = $client->putObject([ 'Bucket' => AWS_BUCKET, 'Key' => 'filename', 'SourceFile' => 'path_to_file', 'ACL' => 'private', 'ServerSideEncryption' => 'AES256' ]);
}
catch(\Aws\S3\Exception\S3Exception $e){
	echo $e->getMessage();
}
```
returns:
*Fatal error: Uncaught exception 'Aws\Exception\CredentialsException' with message 'Error retrieving credentials from the instance profile metadata server. (cURL error 28: Connection timed out after 1001 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html))' in /www/htdocs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php:79 Stack trace: #0 /www/htdocs/vendor/guzzlehttp/promises/src/Promise.php(199): Aws\Credentials\InstanceProfileProvider->Aws\Credentials{closure}(Array) #1 /www/htdocs/vendor/guzzlehttp/promises/src/Promise.php(152): GuzzleHttp\Promise\Promise::callHandler(2, Array, Array) #2 /www/htdocs/vendor/guzzlehttp/promises/src/TaskQueue.php(60): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise{closure}() #3 /www/htdocs/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(96): GuzzleHttp\Promise\TaskQueue->run() #4 /www/htdocs/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(123): GuzzleHttp\Handler\CurlMultiHandler in /www/htdocs/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php on line 79*

what's wrong?

regards.

**Comment by jeremeamia** [comment]
The V3 SDK is not picking up the credentials you specified, because we do not support using `'key'` and `'secret'` in the same way as V2. This [segment of the Migration Guide](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/migration.html#client-configuration-has-changed) explains why and links to the [Configuration](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html) page where you can find the correct settings. TL;TR: `'key'` and `'secret'` should be nested under `'credentials'` (e.g., `[..., 'credentials' => ['key' => AWS_KEY, 'secret' => AWS_SECRET_KEY], ...]`),
