### ISSUE TITLE
issue with v2.8 lambda->invoke

### ISSUE THREAD

**Issue by ravenbyron** [aws/aws-sdk-php#664]
I am having an issue with calling lambda->invoke (code below) I am getting 

```
PHP Fatal error:  Only variables can be passed by reference in .../vendor/guzzle/guzzle/src/Guzzle/Service/Command/LocationVisitor/Response/JsonVisitor.php on line 35
```

We are using php 5.3.23 and are stuck there for now. Am I doing something wrong or is it a bug?

```
lambda->invoke(array(
            'FunctionName' => $this->function_name,
            'InvocationType' => 'RequestResponse',
            'LogType' => 'None',
            'Payload' => $json
        ));
```

**Comment by jeskew** [comment]
Hi @ravenbyron,

I'm having a hard time reproducing that error. Could you [attach a debug log to your lambda client](http://docs.aws.amazon.com/aws-sdk-php/guide/latest/faq.html#how-can-i-see-what-data-is-sent-over-the-wire) and share the output?

**Comment by ravenbyron** [comment]
Here is the output with the debug turned on 


```
# Response:
HTTP/1.1 200 OK
Content-Type: application/json
Date: Sat, 04 Jul 2015 01:09:37 GMT
x-amzn-Remapped-Content-Length: 0
x-amzn-RequestId: 56bad745-21e9-11e5-956e-f5e7a51b657d
Content-Length: 18
Connection: keep-alive

"{\"rank\":\"1\"}"

# Errors: 0
```

**Comment by ravenbyron** [comment]
So this helped me realize that my lambda function was sending a json string to context.succeed instead of an object so it was getting double json'ed. I was able to fix my lambda code and this works now but not sure if this is still a bug.

**Comment by jeskew** [comment]
So [the line that was throwing the error](https://github.com/guzzle/guzzle/blob/v3.8.1/src/Guzzle/Service/Command/LocationVisitor/Response/JsonVisitor.php#L35) is trying to call a method with a signature of `($object, &$scalar)` with what it assumes to be an array member. Pass-by-reference is allowed for array members but not for substrings, which is what happens when `$value[$key]` gets called on a string instead of an array.
