### ISSUE TITLE
Docs refer to 2x version of SDK on AWS website

### ISSUE THREAD

**Issue by cdnsteve** [aws/aws-sdk-php#675]
Refers to old version, note we're on version 3x.
Please update docs:
http://docs.aws.amazon.com/aws-sdk-php/guide/latest/installation.html

Step 1 says:

```
{
    "require": {
        "aws/aws-sdk-php": "2.*"
    }
}
```

**Comment by jeremeamia** [comment]
Even though the URL to the docs says "latest", those are actually the docs for Version 2, so that is correct. We are working on deprecating all the "latest" links. The links you should use for each version of the SDK are the following:

- Version 3:
    - User Guide: http://docs.aws.amazon.com/aws-sdk-php/v3/guide/
    - API Reference: http://docs.aws.amazon.com/aws-sdk-php/v3/api/
- Version 2:
    - User Guide: http://docs.aws.amazon.com/aws-sdk-php/v2/guide/
    - API Reference: http://docs.aws.amazon.com/aws-sdk-php/v2/api/

These links are what we use on our GitHub README and product home page.
