### ISSUE TITLE
Argument mis-matches between S3's putObject() and MultiPartUploader() in v3

### ISSUE THREAD

**Issue by onethumb** [aws/aws-sdk-php#712]
The immediate problem is that the `S3Client` expects `Bucket` and `Key`, whereas the `MultiPartUploader` expect `bucket` and `key`.  

The larger problem is that important arguments aren't available via `MultiPartUploader`, like `Metadata` which is fairly critical for many workloads that use `Metadata` to set a consistent hash or identifier, given that we can't predict what the `ETag` returned from an S3 multi-part upload will be.

There's some oddness around `Content-Type`, too, where it looks like it's hard-coding it based on filename extension:  https://github.com/aws/aws-sdk-php/blob/master/src/S3/MultipartUploader.php#L190-L194 

Are there plans to bring `MultiPartUploader` to parity with `S3Client::putObject()`'s arguments?

**Comment by mtdowling** [comment]
I think that we could update the MultipartUploader to accept Bucket/bucket, Key/key, ACL/acl.

`Metadata` and other options are meant to be applied using the [callback configuration options](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-multipart-upload.html#configuration). You can observe operations before they are sent and mutate them as needed. For example, `before_initiate` is a function that is called with the [CreateMultipartUpload](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#createmultipartupload) command that is about to be executed.

```php
$uploader = new MultipartUploader($s3Client, $source, [
    'bucket' => 'your-bucket',
    'key'    => 'my-file.zip',
    'before_initiate' => function (Aws\Command $command) {
        $command['Metadata']['xyz'] = '123';
        echo 'Initiating';
    }
]);
```

*Note: when providing a `state` that is already initiated, the `before_initiate` callback is not invoked.*

These callbacks are used to modify specific operations sent by a multipart uploader because different options can be applied at different steps in the upload process (i.e., `CreateMultipartUpload`, `UploadPart`, `CompleteMultipartUpload`). We also wanted users to be able to observe and modify operations before they are executed, which also allows them to implement custom things like progress bars (when the size of the upload is known). Because callbacks allow custom parameters per/operation, allows you to observe the state of an upload as it progresses, and you can provide different parameters per operation, we decided to make the API of customizing uploads be exposed through the callbacks. Note that we made `acl` an abstracted top-level parameter (an intentional inconsistency with the rest of the parameters) because it's extremely important that users always know what ACL they are applying to their objects.

I think we could add more content to the multipart uploader user guide to make this more clear.

> There's some oddness around Content-Type, too, where it looks like it's hard-coding it based on filename extension

The `ContentType` parameter is set by default on multipart uploads using the same logic that is used in other parts of the SDK (this is pretty typical in HTTP clients and high level abstractions). You can modify what content-type is applied using the `before_initiate` callback.

> Are there plans to bring MultiPartUploader to parity with S3Client::putObject()'s arguments?

While it supports them using callbacks, you might be interested in a more abstracted uploader that exposes a consistent API between PutObject and MultipartUploader: https://github.com/aws/aws-sdk-php/blob/master/src/S3/S3Client.php#L278.  This helper function is also great because you can call it indifferently with different sized files, and the abstraction will choose whether or not to use a single put object or a multipart upload based on the size (all of which are configurable thresholds).

**Comment by onethumb** [comment]
Oh, awesome reply, and awesome functionality.

I rescind everything other than that the case of the args should be consistent.  :)

**Comment by mtdowling** [comment]
Great :smile: 

Just so we can track it, here are the action items we'll take away from this issue:

1. Make the bucket, key, and acl parameters take both API parameter form and the existing lowercase form.
2. Update the multipart upload documentation to show how to customize operations and how to use the callback functions.

**Comment by jeskew** [comment]
I updated the multipart uploader documentation to show what you can do with `before_{operation}` callbacks and altered the constructor to take case-insensitive options in its config array.
