### ISSUE TITLE
http://169.254.169.254/latest/meta-data/iam/security-credentials/ failed to open stream:

### ISSUE THREAD

**Issue by vov4ik08** [aws/aws-sdk-php#731]
Hi! When i try using aws-php-sdk i see this error:
http://169.254.169.254/latest/meta-data/iam/security-credentials/): failed to open stream:

please help me

**Comment by jeskew** [comment]
Are you using an EC2 instance?

**Comment by vov4ik08** [comment]
no, ec3

**Comment by jeskew** [comment]
Do you mean S3?

Make sure you're providing credentials to your application. [This can be done in several ways](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html), such as by setting environment variables, placing them in an ini file, and passing them in directly when constructing a client. When no credentials are provided in the client constructor, the SDK will first look for credentials in the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` and then for an ini file at `~/.aws/credentials`. If no credentials have been found by that point, the SDK will attempt to contact the EC2 instance metadata service, which is the operation you see failing.

**Comment by vov4ik08** [comment]
yes s3, but not help
my code
```
<?php
require 'vendor/autoload.php';

use Aws\S3\S3Client;

// Instantiate an Amazon S3 client.
$s3 = new S3Client([
    'version' => 'latest',
    'region'  => 'us-west-2'
]);

// Upload a publicly accessible file. The file size and type are determined by the SDK.
try {
    $s3->putObject([
        'Bucket' => '.....t',
        'Key'    => '.....',
        'Body'   => fopen('c:\\test.txt', 'r'),
        'ACL'    => 'public-read',
    ]);
} catch (Aws\Exception\S3Exception $e) {
    echo "There was an error uploading the file.\n";
}
```
This problem reproduced after today update aws-php-sdk

**Comment by jeskew** [comment]
How are you supplying credentials to the SDK?

**Comment by vov4ik08** [comment]
in the IAM console.

**Comment by jeskew** [comment]
So this code *is* running on an Ec2 instance?

**Comment by vov4ik08** [comment]
i do not know, i try only for s3, 2 weeks ago, everything worked and ip 169.254.169.254 not ping

**Comment by jeskew** [comment]
The fact that the instance metadata service is unreachable indicates that your code is not running on an Ec2 instance. This means that you will need to find a way to provide credentials to the instance of `S3Client`, either by passing them in directly or by setting up an ini file or environment variables as described [here](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html).

It's possible that everything was working before because the appropriate environment variables were being set by Apache or Nginx or because there was an ini file at `~/.aws/credentials` that has since been removed.

**Comment by vov4ik08** [comment]
Thanks, I'll try and accomplish your goal

**Comment by gerry650** [comment]
https://teams.live.com/meet/93777936629755?p=tfFivpV3TCuUmA1rLl
