### ISSUE TITLE
Add '@method' Declarations on Clients on 3.x

### ISSUE THREAD

**Issue by donatj** [aws/aws-sdk-php#754]
2.x of the AWS SDK had phpdoc `@method` declarations on its *Client objects.  

3.x lacks these declarations, therefore making tools that do static analysis such as for autocompletion simply show these methods as missing.

I would be willing to do the foot work to move these over from 2.x but feel like you guys would better be able to autogenerate them?

This is a huge downside of upgrading to 3.x which we went ahead with a couple weeks back.  It has been a continuous frustration.

### 2.x:

![2x](https://cloud.githubusercontent.com/assets/133747/9693622/655e8db2-5317-11e5-9fcc-ebfc982ad4cc.png)

```php
<?php

[...]

/**
 * Client to interact with Amazon Simple Queue Service
 *
 * @method Model addPermission(array $args = array()) {@command Sqs AddPermission}
 * @method Model changeMessageVisibility(array $args = array()) {@command Sqs ChangeMessageVisibility}
 * @method Model changeMessageVisibilityBatch(array $args = array()) {@command Sqs ChangeMessageVisibilityBatch}
 * @method Model createQueue(array $args = array()) {@command Sqs CreateQueue}
 * @method Model deleteMessage(array $args = array()) {@command Sqs DeleteMessage}
 * @method Model deleteMessageBatch(array $args = array()) {@command Sqs DeleteMessageBatch}
 * @method Model deleteQueue(array $args = array()) {@command Sqs DeleteQueue}
 * @method Model getQueueAttributes(array $args = array()) {@command Sqs GetQueueAttributes}
 * @method Model getQueueUrl(array $args = array()) {@command Sqs GetQueueUrl}
 * @method Model listDeadLetterSourceQueues(array $args = array()) {@command Sqs ListDeadLetterSourceQueues}
 * @method Model listQueues(array $args = array()) {@command Sqs ListQueues}
 * @method Model purgeQueue(array $args = array()) {@command Sqs PurgeQueue}
 * @method Model receiveMessage(array $args = array()) {@command Sqs ReceiveMessage}
 * @method Model removePermission(array $args = array()) {@command Sqs RemovePermission}
 * @method Model sendMessage(array $args = array()) {@command Sqs SendMessage}
 * @method Model sendMessageBatch(array $args = array()) {@command Sqs SendMessageBatch}
 * @method Model setQueueAttributes(array $args = array()) {@command Sqs SetQueueAttributes}
 * @method ResourceIteratorInterface getListQueuesIterator(array $args = array()) The input array uses the parameters of the ListQueues operation
 *
 * @link http://docs.aws.amazon.com/aws-sdk-php/v2/guide/service-sqs.html User guide
 * @link http://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.Sqs.SqsClient.html API docs
 */
class SqsClient extends AbstractClient
{
```

### 3.x:

![3x](https://cloud.githubusercontent.com/assets/133747/9693618/600afec2-5317-11e5-8678-5451ff28a024.png)

```php
<?php
namespace Aws\Sqs;

use Aws\AwsClient;
use Aws\CommandInterface;
use Aws\Sqs\Exception\SqsException;
use GuzzleHttp\Psr7\Uri;
use Psr\Http\Message\RequestInterface;

/**
 * Client used to interact Amazon Simple Queue Service (Amazon SQS)
 */
class SqsClient extends AwsClient
{
```

**Comment by mtdowling** [comment]
Version 3 of the SDK is far more dynamic that version 2-- you can now more easily change the version of an API you are interacting with at runtime, and you could even use multiple API versions of the same client in the same process (as different instances of the client). When services bump their API versions, they sometimes add new operations or remove old operations. Because clients are not associated with a specific API version but rather just a service in general, generating a static list of `@method` annotations could lead to clients having inaccurate autocompletions when you use different API versions of a service.

We're open to suggestions here if it's possible to provide more context on the operations that would be listed in the `@method` list.

Another idea we've talked about is creating a PHPStorm plugin that could autocomplete a client based on the API version. There could be other nice possibilities for the plugin if we could use the model data of the version being used by the client in the plugin. This might require that when you use a variable you have to hint to the IDE the service and API version being utilized, but we're not sure yet.

**Comment by donatj** [comment]
Do the parameters to the methods ever change based on API versions? If not, you get a [description](http://www.phpdoc.org/docs/latest/references/phpdoc/tags/method.html) on `@method` docs and I would see throwing a simple `API v2 only` or `API v3+ only` or such in the description as sufficent.

While a PhpStorm plugin would be nice, it doesn't help out with tools we use to analyze PRs like Scrutinizer.

**Comment by jeskew** [comment]
That's a fair point about Scrutinizer. Are you getting a lot of 'unknown method' type warnings on PRs?

**Comment by kkopachev** [comment]
I had to use createCommand/execute to avoid warnings about unknown methods.
Missing `@method` phpdocs usually makes me think there is no such method and there is no magic call method as well.

**Comment by donatj** [comment]
Yup ;)

![screen shot 2015-09-04 at 16 01 36](https://cloud.githubusercontent.com/assets/133747/9694430/3f3ff4b6-531e-11e5-97d3-0c75eb7e066e.png)

**Comment by jeskew** [comment]
Method annotations on clients were added back in #760 and should go out with the next release.
