### ISSUE TITLE
Possible bug with deleteMarkers....

### ISSUE THREAD

**Issue by byustephen** [aws/aws-sdk-php#779]
On version 2.8.17 I'm having trouble getting the delete marker to act appropriately. 

According to the docs, if I call deleteObject on an item, part of the guzzle response is the delete marker which I can get by doing this:

    $isDeleted = (bool) $result->get('DeleteMarker');

Yet my deleteMarker is ALWAYS false, even when the file is successfully deleted. Shouldn't the delete marker show true if the file is deleted? (my versioning is off for this bucket). 

If this is an issue, should I update to the latest 3.* version, and would that fix it?

**Comment by jeskew** [comment]
The 'DeleteMarker' property does not indicate whether your call to deleteObject succeeded. (If you did not receive an error response, you can assume your deletion succeeded.) If you have turned on versioning on your bucket, calling deleteObject will set the current version of an object to a [delete marker](http://docs.aws.amazon.com/AmazonS3/latest/dev/DeleteMarker.html). You can remove a delete marker by calling deleteObject on an object and providing the marker's version ID, [which will effectively restore your object to its last version prior to being deleted](http://docs.aws.amazon.com/AmazonS3/latest/dev/RemDelMarker.html). This would be the only situation in which 'DeleteMarker' would be true -- when the target of your deleteObject call is itself a delete marker.

**Comment by byustephen** [comment]
Thanks for the heads up.

**Comment by byustephen** [comment]
Thank you for letting me know. I was expecting to know if a file was successfully deleted, and it seemed that the delete marker was the likely place. 

Then what do you recommend for knowing that the file was removed? Should I just try to get meta data on the file, and if no meta data then that confirms it is gone?

Also, why does the deleteObject response not throw an issue when it tries to delete a file it is not there? The response shows the exact same thing whether the file was deleted, or if I try to delete the same file but it is not there. 

Thanks for taking the time to answer this.

**Comment by jeskew** [comment]
DeleteObject is supposed to be completely idempotent, so returning the same response whether or not a file still exists is by design. DeleteObject should return an error response (400- or 500-level) if your request did not succeed.

If you need to make sure that the file has been completely removed before taking another action, you can call [`doesObjectExist`](http://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.S3.S3Client.html#_doesObjectExist) in a loop until it returns `false`. V3 offers an [`objectNotExists`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#waiters) waiter that accomplishes this.

**Comment by byustephen** [comment]
Thank for the excellent reply. I'm good, so you can close this thread.
