### ISSUE TITLE
S3 - Posibility to set path in endpoint

### ISSUE THREAD

**Issue by bgruszka** [aws/aws-sdk-php#793]
I try to set AWS S3 Client with local/dev version of S3 server (https://github.com/scireum/s3ninja). I observed that before sending, request path is stripped.

For example - I have endpoint http://localhost:9444/s3

Request is sent to: http://localhost:9444/bucket (without /s3) - should be http://localhost:9444/s3/bucket.

**Comment by jeskew** [comment]
Try adding a trailing slash to the localhost endpoint (as described [in the Guzzle docs] (http://docs.guzzlephp.org/en/latest/quickstart.html#creating-a-client)).  Without a trailing slash, relative URLs should replace the final element in the base URL.

**Comment by bgruszka** [comment]
Ok. I tried, but the result is the same.

endpoint http://localhost:9444/s3/ finished with request to http://localhost:9444/bucket (without /s3)

**Comment by jeremeamia** [comment]
I'm pretty sure the SDK cannot support that by default. The SDK does transformations on the URL based on S3's requirements and is probably not treating the `"s3/"` as part of the base endpoint, since it is not a part of the host.

**Comment by mtdowling** [comment]
I think the bucket_endpoint option of the S3 constructor would work here, but you would not be able to use the client to contact multiple buckets. It's basically a fixed bucket endpoint: http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.S3.S3Client.html#___construct

**Comment by jeskew** [comment]
@jeremeamia is correct; there is no native support for this behavior in the SDK. Because the S3 API is defined with URLs beginning with `'/'` (e.g., [`createBucket` is mapped to `/{Bucket}`](https://github.com/aws/aws-sdk-php/blob/master/src/data/s3/2006-03-01/api-2.json#L62) and [`putObject` is mapped to `/{Bucket}/{Key+}`](https://github.com/aws/aws-sdk-php/blob/master/src/data/s3/2006-03-01/api-2.json#L559)), you cannot use a subfolder as an S3 endpoint.

**Comment by roborourke** [comment]
This is possible in the node sdk, and the client endpoint object contains the path property. I don't really get why it should be stripped out for a custom endpoint.
