### ISSUE TITLE
Difference between SDK and API

### ISSUE THREAD

**Issue by kirkbushell** [aws/aws-sdk-php#871]
Hi - I'm getting some weird differences between SDK and API use for elastic transcoder. For example, I'm seeing this error: 

[InvalidArgumentException]
  Found 2 errors while validating the input provided for the CreateJob operation:
  [Outputs][PresetId] must be an associative array. Found string(20) "1351620000001-000010"
  [Outputs][Key] must be an associative array. Found string(5) "Video"

But the docs say they both must be strings?

**Comment by jeskew** [comment]
What version are you using?

**Comment by kirkbushell** [comment]
AWS sdk version: 3.11.7

**Comment by jeskew** [comment]
`Outputs` takes an array of associative arrays, each of which can have a string at `Key` and a string at `PresetId`. Your method call should look a bit like this:
```php
$out = $ets->createJob([
    // ...
    'Outputs' => [
        [
            // ...
            'Key' => 'key',
            'PresetId' => 'Id',
        ],
    ],
]);
```

I'll admit that "[Outputs][PresetId] must be an associative array" is a bit confusing, but it's saying that each value under [Outputs] needs to be an associative array so that you can specify multiple output targets.

**Comment by kirkbushell** [comment]
Ohhhhh. I thought it wsa saying that the presetId itself needed to be an array!

Thanks :)
