### ISSUE TITLE
How to set streamWrapper flags for error reporting?

### ISSUE THREAD

**Issue by tot-ra** [aws/aws-sdk-php#879]
I'm using latest Amazon S3 client library v3.12.2 to check if bucket file exists, but error does not get thrown. Overall, authentication and normal download/upload works fine, but when I check for a missing file, I don't get any errors or S3Exception/AwsException or Guzzle exceptions..

is_file("s3://tmp-local/library/12/126/1/9d312aa3333ee90ce7a03199d6a40332/original.JPG/");
When I do a debug, I see that \Aws\S3\StreamWrapper registers php stream wrapper with flag value "1"

stream_wrapper_register($protocol, get_called_class(), STREAM_IS_URL);
Later on, I end up with a StreamWrapper::triggerError() call which now has $flags set to 2, which is STREAM_URL_STAT_QUIET. This goes into return false section and I never receive an exception.

Question is - how can can I get error to be thrown? Is there a way to set default flags?

![2016-01-13 12 25 06](https://cloud.githubusercontent.com/assets/445122/12292440/ce90aeba-b9f5-11e5-86e1-940a63fafb6d.png)

(Re-posted to http://stackoverflow.com/questions/34764540/how-to-set-streamwrapper-flags-for-error-reporting )

**Comment by jeskew** [comment]
The flags passed to `url_stat` (and subsequently to `triggerError`) are set by the PHP engine, and `STREAM_URL_STAT_QUIET` is set because `is_file`, `file_exists`, and `is_dir` are not supposed to trigger errors when a file does not exist -- they are just supposed to return `false`. 

The `is_file`, `file_exists`, and `is_dir` functions should never throw exceptions when a path is not found, so the stream wrapper might not be a good fit for your application if you rely on exceptions being thrown. The [`HeadObject`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#headobject) command will throw an exception if a key does not exist, so that might be the method you want to use.
