### ISSUE TITLE
Question regarding performance

### ISSUE THREAD

**Issue by dcsg** [aws/aws-sdk-php#882]
Hi,

Before we decided to upgrade AWS SDK to v3 we did some profiling to understand what was the main issues and we figured out that `Guzzle\Http\Curl\CurlMulti::executeHandles` was what taking to much time to run which make sense. After acknowledge that I tried to understand what impact would an upgrade have regarding this and from what I read was expectable from Guzzle 3 to 4 up to 30% performance improvement. So we decided to upgrade in order to see the performance of it and the results were bad. So saying this I did perform the same test for AWS 2.6.* with Guzzle 3.9.* and the same for AWS 3.13.* and Guzzle 6.1.* and here is the results:

## Test 1

* PHP 5.5.30
* xdebug off
* Symfony 2.6.*
* Curl 7.19.7
* Guzzle 3.9.3
* AWS SDK PHP 2.7.18

![image](https://cloud.githubusercontent.com/assets/744921/12418470/6c386e2c-bea7-11e5-8e62-0321d83ca65e.png)

## Test 2

* PHP 5.5.30
* xdebug off
* Symfony 2.6.*
* Curl 7.19.7
* Guzzle 6.1.1
* AWS SDK PHP Symfony 1.1.0
* AWS SDK PHP 3.13.0

![image](https://cloud.githubusercontent.com/assets/744921/12418456/54190004-bea7-11e5-8f16-99546754aa35.png)

#### Expectations

My expectation was that the execution of curl would perform better which it did but not significantly but then it got much worst in terms of memory consumption. My question is, is possible something in our configuration could have any impact on this to not perform better?

The reason I opened it here is because the tests performed were to connect directly to DynamoDB to retrieve data.

/cc @mtdowling

**Comment by jeskew** [comment]
I don't think you'll be able to see improvement on the metrics you're examining.

In the left hand chart, you're measuring wall clock time, and in both cases, the function the Guzzle uses to wait for a response comes in at ~85 seconds. It's about five seconds faster in the Guzzle 6 example, but in both cases what's being measured is network I/O time. Which is to say, no significant improvement is likely because that number is dependent on the performance of DynamoDB, which does not change between the first and second example.

In the right hand chart, what appears to be tracked is total memory used without taking memory freed into account. `Guzzle\Psr7\Stream::read` is a wrapper for `fread`. [A small amount of data is read from a stream with `fread` and immediately returned](https://github.com/guzzle/psr7/blob/master/src/Stream.php#L205), which will cause the PHP engine to use and free `$length` bytes of memory. If you pipe a 2 GB stream through a wrapper, then 2 GB of memory will be "used", with peak memory usage never exceeding what's necessary to read a single chunk.

If you don't think that's an accurate characterization of the test you're running, code you share the code used for your benchmark? We regularly run a suite of performance tests to check for memory leaks on large downloads and uploads (you can view a graph of the most recent results [here](https://blackfire.io/profiles/c85bb00b-963e-4892-824b-3e64b627d6fd/graph)), and I haven't seen the Guzzle stream classes hold on to any memory that should have been freed.

**Comment by jeskew** [comment]
Closing, as I believe I've answered your question about memory usage. Please feel free to reopen if you have any further questions or concerns.
