### ISSUE TITLE
Exception: Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by steefaan** [aws/aws-sdk-php#891]
If I use `3.x` release of this SDK and create a `S3Client()` instance ALL my test cases fail with the exception mentoined above. Unfortunately it doesn't tell me where the error is. I only get the following error message:

```
383) Comments\Test\TestCase\Controller\CommentsControllerTest::testAjaxAddFailure
Exception: Serialization of 'Closure' is not allowed
```

It took me a while to isolate this issue as best as possible and it seems to be an issue in here: https://github.com/aws/aws-sdk-php/blob/255013bbf2f06a764ee3717fe75bf57e6458c134/src/ClientResolver.php#L210-L254

My configuration looks like:

```
$s3Client = new S3Client([
    'version' => 'latest',
    'region'  => 'YOUR_REGION',
    'credentials' => [
        'secret' => 'YOUR_SECRET',
        'key' => 'YOUR_KEY'
    ]
]);
```

If I use `2.x` release of this SDK with the following configuration:

```
$s3Client = S3Client::factory([
    'version' => 'latest',
    'region'  => 'YOUR_REGION',
    'credentials' => [
        'secret' => 'YOUR_SECRET',
        'key' => 'YOUR_KEY'
    ]
]);
```

everything works fine and the error is gone.

Some details about my environment:

PHP 5.6.16-2
PHPUnit 4.x but also tested with 5.x
Framework: CakePHP 3.x

**Comment by jeskew** [comment]
Clients are not serializable due to the closures used in their configuration arrays. Does your test work if you don't serialize a client?

**Comment by GrahamCampbell** [comment]
Are you using process isolation in phpunit. That's known to cause issues that look exactly like that if a test errors.

**Comment by jeskew** [comment]
@steefaan Does Graham's comment sound related?

**Comment by steefaan** [comment]
@jeskew I need some more time to test it because I need to observe a deadline and have no time to test it against SDK 3.x now, because it works for 2.x and I have opened and issue for the next version to migrate to 3.x.

If you want to close this issue, you can do this, I would reopen it if it doesn't work. I will also post an answer as soon as I have tried it.

**Comment by jeskew** [comment]
I was able to reproduce this error by including a client in a data provider and running a test with the `--process-isolation` flag. I believe you would see a similar error if a client resides in any part of [global state](https://phpunit.de/manual/current/en/fixtures.html#fixtures.global-state) that PHPUnit attempts to share between isolated processes.

Given the degree to which this library relies on closures and allows users to pass in closures as configuration parameters, I don't see a backwards-compatible way to make clients safely serializable. I think it would be appropriate to add a `__sleep` method to `Aws\AwsClient` that immediately throws an exception so that this failure case is more clear.
