### ISSUE TITLE
Integrating the SDK with React's event loop

### ISSUE THREAD

**Issue by joshdifabio** [aws/aws-sdk-php#901]
I need to integrate the SDK with React's event loop but am having difficulties. I'm able to inject a custom HTTP handler into the SDK client which I tick using the React event loop, but with this approach the SDK client does not raise exceptions on error responses as it does usually. What am I doing wrong?

```php
$httpHandler = new \GuzzleHttp\Handler\CurlMultiHandler();
$eventLoop->addPeriodicTimer(0, [$httpHandler, 'tick']);
if (function_exists('curl_exec')) {
    $httpHandler = \GuzzleHttp\Handler\Proxy::wrapSync($httpHandler, new \GuzzleHttp\Handler\CurlHandler());
}

$client = new DynamoDbClient([
    'region' => 'eu-west-1',
    'profile' => 'default',
    'version' => 'latest',
    'http_handler' => \GuzzleHttp\HandlerStack::create($httpHandler),
]);
```

**Comment by jeskew** [comment]
Converting HTTP responses into exceptions is something that's normally handled by a Guzzle client. Rather than passing your handler stack directly to an SDK client as its `http_handler`, you could use it to [create a Guzzle client](http://guzzle.readthedocs.org/en/latest/handlers-and-middleware.html#handlers):
```php
$httpHandler = new \GuzzleHttp\Handler\CurlMultiHandler();
$eventLoop->addPeriodicTimer(0, [$httpHandler, 'tick']);
if (function_exists('curl_exec')) {
    $httpHandler = \GuzzleHttp\Handler\Proxy::wrapSync($httpHandler, new \GuzzleHttp\Handler\CurlHandler());
}

$guzzleClient = new \GuzzleHttp\Client([
    'handler' => \GuzzleHttp\HandlerStack::create($httpHandler),
]);
```

With that Guzzle client, you can create an HTTP handler that converts Guzzle exceptions to a standardized form expected by SDK middleware:
```php
$handler = new \Aws\Handler\GuzzleV6\GuzzleHandler($guzzleClient);

$client = new DynamoDbClient([
    'region' => 'eu-west-1',
    'profile' => 'default',
    'version' => 'latest',
    'http_handler' => $handler,
]);
```

Hope that helps! Please feel free to reopen if you have any questions or concerns.

**Comment by jeremeamia** [comment]
You may also want to check out this: https://github.com/WyriHaximus/react-guzzle-psr7
