### ISSUE TITLE
Marshaller (Marshaler->marshalJson) fails for JSON documents with empty string ("") at any level.

### ISSUE THREAD

**Issue by neilghosh** [aws/aws-sdk-php#920]
One can deal with replacing a special character when the empty string is in top level attribute . While saving a JSON document as a M data type it does the marshaller in PHP AWS SDK does not even work if there is an empty string "" at any level of a JSON. I could recursively replace all of them and put the "" back while doing a get but this would be expensive in case of complex nested JSON structures.

**Comment by jeskew** [comment]
This behavior is not a bug but [intentional client-side validation](https://github.com/aws/aws-sdk-php/blob/master/src/DynamoDb/Marshaler.php#L140). According to [the DynamoDB documentation](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html), items with empty string attributes will be rejected as invalid by the service.

**Comment by neilghosh** [comment]
I think I should have been clear that , I am talking about the empty top level attribute. Consider the following example 

`Marshaler->marshalJson(
'{
  "key01": {
    "subkey": ""
  }
}'
);`

This returns the error as well. 

For PutItem the attribute itself is not "" but its somewhere inside the complex value. 

I understand Storing it as a map actually exposes all the values in all level for querying. If the intention is to now allow empty string at any depth, I would have no choice but to store the json as string. Not sure if its more efficient if my intention is to always query the whole value from the key. But it defeats the purpose of document storage where the use case may require few values to be empty . If the business logic prunes it before sending to DynamoDB , there is no way to retrive it back.

**Comment by jeskew** [comment]
Unfortunately, DynamoDB does not allow empty strings at any level of a document. 

When trying to run a `PutItem` command with a map containing an empty string, for example:
```php
$ddb->putItem([
    ...
    'Item' => [
        ....
        'arbitraryData' => ['M' => ['Key' => ['S' => '']]],
    ]
]);
```
an error will be returned from the service. I ran the code above and got the following error: `Error executing "PutItem" on "https://dynamodb.us-east-1.amazonaws.com"; AWS HTTP error: Client error response [url] https://dynamodb.us-east-1.amazonaws.com [status code] 400 [reason phrase] Bad Request ValidationException (client): One or more parameter values were invalid: An AttributeValue may not contain an empty string - `

If you need to save an empty value, I believe your best option would be to use `null` instead of an empty string. DynamoDB does support saving fields with a type of `null`.

**Comment by Pierozi** [comment]
I meet the same issue, i don't think patch Marshaler is a good idea because it's application side decision to have or not empty string.

You can easily replace your empty string by null with : 
```php

array_walk_recursive($data, function(& $item) {
    if ('' === $item) {
        $item = null;
    }
});
```

**Comment by theqdev** [comment]
I know these are some old issues, but they still pop up in Google. 

FYI: DynamoDb and Marshaler does now allow empty strings by default.

https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-dynamodb-now-supports-empty-values-for-non-key-string-and-binary-attributes-in-dynamodb-tables/

https://github.com/aws/aws-sdk-php/commit/68c1058c31da76c889f39af36daf69b246eec2a8
