### ISSUE TITLE
Feature request:  Marshaler:  option to convert empty strings to null

### ISSUE THREAD

**Issue by bkdotcom** [aws/aws-sdk-php#926]
Via https://github.com/aws/aws-sdk-php/issues/920

@jeskew said
>  If you need to save an empty value, I believe your best option would be to use null instead of an empty string. DynamoDB does support saving fields with a type of `null`.

Best option would be if DynamoDb supported empty strings.    :|
Second best option would be if there was a marshaler config/option to convert empty strings to null for me.

I encountered this issue on my very first putItem attempt.

        if ($type === 'string') {
            if ($value === '') {
                if (!$this->options['nullEmptyStrings') {
                    // default behavior for those that prefer failure
                    return $this->handleInvalid('empty strings are invalid');
                }
                $type =  'NULL';   // easy peasy, thank you SDK
            } else {
                return ['S' => $value];
            }
        }

**Comment by jeskew** [comment]
I would need to look into what would happen if the affected field was part of an index. You wouldn't technically be saving a string field with a null value but rather a null field with no value. Instead of setting `$value` to `null`, you would instead want to return `['NULL' => true]`.

**Comment by bkdotcom** [comment]
> Instead of setting $value to null, you would instead want to return ['NULL' => true].

d'oh.. you are correct...  I updated my snippet

**Comment by jeskew** [comment]
Simply casting empty strings to a null value wouldn't work in all cases. If the key containing an empty string is part of an index, then changing its type will result in a server-side validation exception based on the type mismatch. Dynamo strictly enforces the type of values used in indices. Secondly, this would be problematic for string sets, which can only contain strongly-typed string attributes, not null values. 

This change would allow users to save empty strings, but only if they weren't part of a set or defined in the table's (or any index's) key schema. It would also persist values that couldn't be effectively round-tripped: when unmarshalling a null value, should it be converted to `null` or to an empty string? Encountering a `null` where a string was expected might break code that relies on an implicit schema, especially if the same table is being used by multiple applications written in different languages.

**Comment by jeskew** [comment]
I took a look at how the `:nil_as_empty_string` feature is implemented in [aws-sdk-ruby-record](https://github.com/awslabs/aws-sdk-ruby-record/blob/add3b9859a815187be7651b20f1332858f1d3afd/spec/aws-record/record/attributes/string_marshaler_spec.rb#L21), and I don't think it's appropriate for a generic marshaller/unmarshaller. In a data mapper library, a marshaller would have enough context to know if casting an empty string to null is a safe action -- it could use the defined metadata to figure out whether the string is an attribute or part of a set and whether the key was used in an index -- and more importantly it could figure out when unmarshalling whether a given null field should be unmarshalled to `null` or to an empty string. 

Since the marshaller in the PHP SDK works on fields and set members, not full records, I don't think it could be rewritten to support an 'emptyStringAsNull' option without significantly changing the class's interface. If you know that your use case is safely only saving empty strings as non-indexed attributes, you can perform this transformation on the data provided to the marshaller:
```php
$data = array_walk_recursive($data, function (&$leaf) {
    if ('' === $leaf) {
        $leaf = null;
    }
});
```

**Comment by bkdotcom** [comment]
thanks for investigating the possibility

**Comment by asalem** [comment]
Well you can do by passing nullify_invalid to marshaler: 
new Marshaler(['nullify_invalid'=>true]);

**Comment by theqdev** [comment]
I know these are sold old issues, but they still pop up in Google. 

FYI: DynamoDb and Marshaler does now allow empty strings by default anymore.

https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-dynamodb-now-supports-empty-values-for-non-key-string-and-binary-attributes-in-dynamodb-tables/

https://github.com/aws/aws-sdk-php/commit/68c1058c31da76c889f39af36daf69b246eec2a8
