### ISSUE TITLE
Firehose increases CPU usage by significant margin.

### ISSUE THREAD

**Issue by henderjon** [aws/aws-sdk-php#938]
This might be more of a question than an issue...

In using the Firehose SDK to capture page views on our site, our EC2 instances run ~20% hotter (CPU) than when using a different collection mechanism (I've also built a connector for Elasticache Redis that has no noticeable effect on the CPU).

Is this because the SDK is doing that much more work? Is this because the Firehose potion of the SDK is newish? AWS' docs don't discuss the effects (potential latency?) of crossing the thresholds of 2000 items or 5MB but even so, I'm confident that we're not anywhere near those numbers.

**Comment by jeskew** [comment]
There are a few things the SDK is doing on any given request that are CPU intensive. Amazon Kinesis Firehose is [only accessible via HTTPS endpoints](http://docs.aws.amazon.com/general/latest/gr/rande.html#fh_region), so each `PutRecord` call performs communication over TLS. Additionally, each request is signed (i.e., converted to a canonical form, the SHA-256 HMAC of which is used as the Authorization HTTP header). You could run a profile to see exactly where CPU time is being spent, but TLS and request signing are the most likely culprits.

The [Redis protocol](http://redis.io/topics/protocol), however, is a simple TCP-based protocol that is designed to be cheap to parse and serialize. [Redis' security model](http://redis.io/topics/security) is based on restricted network access rather than encryption or signatures, so by using Elasticache inside a VPC you avoid the CPU overhead of TLS communication, HTTP message serialization, and HTTP message signing. You should expect Redis to take comparatively little CPU.

For Firehose, have you looked into using [`PutRecordBatch`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-firehose-2015-08-04.html#putrecordbatch) to send multiple updates at once? That would probably be a more efficient approach.

**Comment by jeskew** [comment]
I think you should see some improvements by moving to batch puts. Please feel free to reopen if you have any questions or concerns.
