### ISSUE TITLE
Is there a way to abort a putObject()

### ISSUE THREAD

**Issue by harpreetsb** [aws/aws-sdk-php#950]
In our project we have created API that handles upload and gives it($_FILES object) to s3.
Now Jquery uploader, that we use has function to abort.
even though the ajax is aborted the PHP to S3 keeps uploading stuff.
we are using 
```php
$result = $s3->putObject(array(
			        'Bucket'       => 'lyfboat',
			        'Key'          => $attachment_name,
			        'SourceFile'   => $source_file,
			        'ACL'          => $this->acl,
			        'StorageClass' => $this->storage_class,
			    ));
		    return $result['ObjectURL'];

```
how can i abort this.

**Comment by jeskew** [comment]
Hi @harpreetsb,

If you use `putObjectAsync` instead of `putObject`, `$result` will be a [promise](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/promises.html#promises-in-the-sdk) that will be fulfilled with the result of the `PutObject` command or rejected with an exception. Promises have a `cancel` method, but whether calling `cancel` has any effect would depend on a few factors, including the state of the promise at the time of the call (only pending promises can be cancelled).

Calling `cancel` will not delete the object from a bucket if the upload is already complete, so you may need to complete clean up steps beyond a simple cancellation to fully abort an upload.
